
var m_count = 0;
m_items = new Array(
"<h3>ti.catalog.msp430</h3>",
"<h4>MSP430BT5190</h4>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Base Address </th><th> Interrupt </th></tr>",
   "<tr><td> 0        </td><td> Timer0_A5   </td><td> 0x340         </td><td> 54 </td></tr>",
   "<tr><td> 1        </td><td> Timer1_A3   </td><td> 0x380         </td><td> 49 </td></tr>",
   "<tr><td> 2        </td><td> Timer0_B7   </td><td> 0x3C0         </td><td> 60 </td></tr>",
 "</table>",
"<h4>MSP430F51x1</h4>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Base Address </th><th> Interrupt </th></tr>",
   "<tr><td> 0        </td><td> Timer0_A3   </td><td> 0x3C0         </td><td> 52 </td></tr>",
 "</table>",
"<h4>MSP430F51x2</h4>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Base Address </th><th> Interrupt </th></tr>",
   "<tr><td> 0        </td><td> Timer0_A3   </td><td> 0x3C0         </td><td> 52 </td></tr>",
 "</table>",
"<h4>MSP430F521x</h4>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Base Address </th><th> Interrupt </th></tr>",
   "<tr><td> 0        </td><td> Timer0_A5   </td><td> 0x340         </td><td> 53 </td></tr>",
   "<tr><td> 1        </td><td> Timer1_A3   </td><td> 0x380         </td><td> 49 </td></tr>",
   "<tr><td> 2        </td><td> Timer2_A3   </td><td> 0x400         </td><td> 44 </td></tr>",
   "<tr><td> 3        </td><td> Timer0_B7   </td><td> 0x3C0         </td><td> 59 </td></tr>",
 "</table>",
"<h4>MSP430F522x</h4>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Base Address </th><th> Interrupt </th></tr>",
   "<tr><td> 0        </td><td> Timer0_A5   </td><td> 0x340         </td><td> 53 </td></tr>",
   "<tr><td> 1        </td><td> Timer1_A3   </td><td> 0x380         </td><td> 49 </td></tr>",
   "<tr><td> 2        </td><td> Timer2_A3   </td><td> 0x400         </td><td> 44 </td></tr>",
   "<tr><td> 3        </td><td> Timer0_B7   </td><td> 0x3C0         </td><td> 59 </td></tr>",
 "</table>",
"<h4>MSP430F530x</h4>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Base Address </th><th> Interrupt </th></tr>",
   "<tr><td> 0        </td><td> Timer0_A5   </td><td> 0x340         </td><td> 53 </td></tr>",
   "<tr><td> 1        </td><td> Timer1_A3   </td><td> 0x380         </td><td> 49 </td></tr>",
   "<tr><td> 2        </td><td> Timer2_A3   </td><td> 0x400         </td><td> 44 </td></tr>",
   "<tr><td> 3        </td><td> Timer0_B7   </td><td> 0x3C0         </td><td> 59 </td></tr>",
 "</table>",
"<h4>MSP430F5310</h4>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Base Address </th><th> Interrupt </th></tr>",
   "<tr><td> 0        </td><td> Timer0_A5   </td><td> 0x340         </td><td> 53 </td></tr>",
   "<tr><td> 1        </td><td> Timer1_A3   </td><td> 0x380         </td><td> 49 </td></tr>",
   "<tr><td> 2        </td><td> Timer2_A3   </td><td> 0x400         </td><td> 44 </td></tr>",
   "<tr><td> 3        </td><td> Timer0_B7   </td><td> 0x3C0         </td><td> 59 </td></tr>",
 "</table>",
"<h4>MSP430F532x</h4>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Base Address </th><th> Interrupt </th></tr>",
   "<tr><td> 0        </td><td> Timer0_A5   </td><td> 0x340         </td><td> 53 </td></tr>",
   "<tr><td> 1        </td><td> Timer1_A3   </td><td> 0x380         </td><td> 49 </td></tr>",
   "<tr><td> 2        </td><td> Timer2_A3   </td><td> 0x400         </td><td> 44 </td></tr>",
   "<tr><td> 3        </td><td> Timer0_B7   </td><td> 0x3C0         </td><td> 59 </td></tr>",
 "</table>",
"<h4>MSP430F533x</h4>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Base Address </th><th> Interrupt </th></tr>",
   "<tr><td> 0        </td><td> Timer0_A5   </td><td> 0x340         </td><td> 53 </td></tr>",
   "<tr><td> 1        </td><td> Timer1_A3   </td><td> 0x380         </td><td> 49 </td></tr>",
   "<tr><td> 2        </td><td> Timer2_A3   </td><td> 0x400         </td><td> 44 </td></tr>",
   "<tr><td> 3        </td><td> Timer0_B7   </td><td> 0x3C0         </td><td> 59 </td></tr>",
 "</table>",
"<h4>MSP430F534x</h4>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Base Address </th><th> Interrupt </th></tr>",
   "<tr><td> 0        </td><td> Timer0_A5   </td><td> 0x340         </td><td> 53 </td></tr>",
   "<tr><td> 1        </td><td> Timer1_A3   </td><td> 0x380         </td><td> 49 </td></tr>",
   "<tr><td> 2        </td><td> Timer2_A3   </td><td> 0x400         </td><td> 44 </td></tr>",
   "<tr><td> 3        </td><td> Timer0_B7   </td><td> 0x3C0         </td><td> 59 </td></tr>",
 "</table>",
"<h4>MSP430F535x</h4>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Base Address </th><th> Interrupt </th></tr>",
   "<tr><td> 0        </td><td> Timer0_A5   </td><td> 0x340         </td><td> 53 </td></tr>",
   "<tr><td> 1        </td><td> Timer1_A3   </td><td> 0x380         </td><td> 49 </td></tr>",
   "<tr><td> 2        </td><td> Timer2_A3   </td><td> 0x400         </td><td> 40 </td></tr>",
   "<tr><td> 3        </td><td> Timer0_B7   </td><td> 0x3C0         </td><td> 59 </td></tr>",
 "</table>",
"<h4>MSP430F541x</h4>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Base Address </th><th> Interrupt </th></tr>",
   "<tr><td> 0        </td><td> Timer0_A5   </td><td> 0x340         </td><td> 54 </td></tr>",
   "<tr><td> 1        </td><td> Timer1_A3   </td><td> 0x380         </td><td> 49 </td></tr>",
   "<tr><td> 2        </td><td> Timer0_B7   </td><td> 0x3C0         </td><td> 60 </td></tr>",
 "</table>",
"<h4>MSP430F543x</h4>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Base Address </th><th> Interrupt </th></tr>",
   "<tr><td> 0        </td><td> Timer0_A5   </td><td> 0x340         </td><td> 54 </td></tr>",
   "<tr><td> 1        </td><td> Timer1_A3   </td><td> 0x380         </td><td> 49 </td></tr>",
   "<tr><td> 2        </td><td> Timer0_B7   </td><td> 0x3C0         </td><td> 60 </td></tr>",
 "</table>",
"<h4>MSP430F550x</h4>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Base Address </th><th> Interrupt </th></tr>",
   "<tr><td> 0        </td><td> Timer0_A5   </td><td> 0x340         </td><td> 53 </td></tr>",
   "<tr><td> 1        </td><td> Timer1_A3   </td><td> 0x380         </td><td> 49 </td></tr>",
   "<tr><td> 2        </td><td> Timer2_A3   </td><td> 0x400         </td><td> 44 </td></tr>",
   "<tr><td> 3        </td><td> Timer0_B7   </td><td> 0x3C0         </td><td> 59 </td></tr>",
 "</table>",
"<h4>MSP430F551x</h4>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Base Address </th><th> Interrupt </th></tr>",
   "<tr><td> 0        </td><td> Timer0_A5   </td><td> 0x340         </td><td> 53 </td></tr>",
   "<tr><td> 1        </td><td> Timer1_A3   </td><td> 0x380         </td><td> 49 </td></tr>",
   "<tr><td> 2        </td><td> Timer2_A3   </td><td> 0x400         </td><td> 44 </td></tr>",
   "<tr><td> 3        </td><td> Timer0_B7   </td><td> 0x3C0         </td><td> 59 </td></tr>",
 "</table>",
"<h4>MSP430F552x</h4>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Base Address </th><th> Interrupt </th></tr>",
   "<tr><td> 0        </td><td> Timer0_A5   </td><td> 0x340         </td><td> 53 </td></tr>",
   "<tr><td> 1        </td><td> Timer1_A3   </td><td> 0x380         </td><td> 49 </td></tr>",
   "<tr><td> 2        </td><td> Timer2_A3   </td><td> 0x400         </td><td> 44 </td></tr>",
   "<tr><td> 3        </td><td> Timer0_B7   </td><td> 0x3C0         </td><td> 59 </td></tr>",
 "</table>",
"<h4>MSP430F563x</h4>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Base Address </th><th> Interrupt </th></tr>",
   "<tr><td> 0        </td><td> Timer0_A5   </td><td> 0x340         </td><td> 53 </td></tr>",
   "<tr><td> 1        </td><td> Timer1_A3   </td><td> 0x380         </td><td> 49 </td></tr>",
   "<tr><td> 2        </td><td> Timer2_A3   </td><td> 0x400         </td><td> 40 </td></tr>",
   "<tr><td> 3        </td><td> Timer0_B7   </td><td> 0x3C0         </td><td> 59 </td></tr>",
 "</table>",
"<h4>MSP430F565x</h4>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Base Address </th><th> Interrupt </th></tr>",
   "<tr><td> 0        </td><td> Timer0_A5   </td><td> 0x340         </td><td> 53 </td></tr>",
   "<tr><td> 1        </td><td> Timer1_A3   </td><td> 0x380         </td><td> 49 </td></tr>",
   "<tr><td> 2        </td><td> Timer2_A3   </td><td> 0x400         </td><td> 40 </td></tr>",
   "<tr><td> 3        </td><td> Timer0_B7   </td><td> 0x3C0         </td><td> 59 </td></tr>",
 "</table>",
"<h4>MSP430F643x</h4>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Base Address </th><th> Interrupt </th></tr>",
   "<tr><td> 0        </td><td> Timer0_A5   </td><td> 0x340         </td><td> 53 </td></tr>",
   "<tr><td> 1        </td><td> Timer1_A3   </td><td> 0x380         </td><td> 49 </td></tr>",
   "<tr><td> 2        </td><td> Timer2_A3   </td><td> 0x400         </td><td> 40 </td></tr>",
   "<tr><td> 3        </td><td> Timer0_B7   </td><td> 0x3C0         </td><td> 59 </td></tr>",
 "</table>",
"<h4>MSP430F645x</h4>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Base Address </th><th> Interrupt </th></tr>",
   "<tr><td> 0        </td><td> Timer0_A5   </td><td> 0x340         </td><td> 53 </td></tr>",
   "<tr><td> 1        </td><td> Timer1_A3   </td><td> 0x380         </td><td> 49 </td></tr>",
   "<tr><td> 2        </td><td> Timer2_A3   </td><td> 0x400         </td><td> 40 </td></tr>",
   "<tr><td> 3        </td><td> Timer0_B7   </td><td> 0x3C0         </td><td> 59 </td></tr>",
 "</table>",
"<h4>MSP430F663x</h4>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Base Address </th><th> Interrupt </th></tr>",
   "<tr><td> 0        </td><td> Timer0_A5   </td><td> 0x340         </td><td> 53 </td></tr>",
   "<tr><td> 1        </td><td> Timer1_A3   </td><td> 0x380         </td><td> 49 </td></tr>",
   "<tr><td> 2        </td><td> Timer2_A3   </td><td> 0x400         </td><td> 40 </td></tr>",
   "<tr><td> 3        </td><td> Timer0_B7   </td><td> 0x3C0         </td><td> 59 </td></tr>",
 "</table>",
"<h4>MSP430F665x</h4>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Base Address </th><th> Interrupt </th></tr>",
   "<tr><td> 0        </td><td> Timer0_A5   </td><td> 0x340         </td><td> 53 </td></tr>",
   "<tr><td> 1        </td><td> Timer1_A3   </td><td> 0x380         </td><td> 49 </td></tr>",
   "<tr><td> 2        </td><td> Timer2_A3   </td><td> 0x400         </td><td> 40 </td></tr>",
   "<tr><td> 3        </td><td> Timer0_B7   </td><td> 0x3C0         </td><td> 59 </td></tr>",
 "</table>",
"<h4>MSP430F67x</h4>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Base Address </th><th> Interrupt </th></tr>",
   "<tr><td> 0        </td><td> Timer0_A3   </td><td> 0x340         </td><td> 55 </td></tr>",
   "<tr><td> 1        </td><td> Timer1_A2   </td><td> 0x380         </td><td> 49 </td></tr>",
   "<tr><td> 2        </td><td> Timer2_A2   </td><td> 0x400         </td><td> 46 </td></tr>",
   "<tr><td> 3        </td><td> Timer3_A2   </td><td> 0x440         </td><td> 43 </td></tr>",
 "</table>",
"<h4>MSP430FR58x/MSP430FR59xx</h4>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Base Address </th><th> Interrupt </th></tr>",
   "<tr><td> 0        </td><td> Timer0_A3   </td><td> 0x340         </td><td> 45 </td></tr>",
   "<tr><td> 1        </td><td> Timer1_A3   </td><td> 0x380         </td><td> 41 </td></tr>",
   "<tr><td> 2        </td><td> Timer2_A2   </td><td> 0x400         </td><td> 38 </td></tr>",
   "<tr><td> 3        </td><td> Timer3_A2   </td><td> 0x440         </td><td> 35 </td></tr>",
   "<tr><td> 4        </td><td> Timer0_B7   </td><td> 0x3C0         </td><td> 51 </td></tr>",
 "</table>",
"<!-- -->"
);

// gen below code only 1 time
while (m_count < m_items.length) {
    document.write(m_items[m_count]);
    m_count++;
}
