/*
 *  Do not modify this file; it is automatically 
 *  generated and any modifications will be overwritten.
 *
 * @(#) xdc-D21
 */

#ifndef xdc_rov_support__
#define xdc_rov_support__


/*
 * ======== module xdc.rov.support.ScalarStructs ========
 */

typedef struct xdc_rov_support_ScalarStructs_S_Bits8 xdc_rov_support_ScalarStructs_S_Bits8;
typedef struct xdc_rov_support_ScalarStructs_S_Bits16 xdc_rov_support_ScalarStructs_S_Bits16;
typedef struct xdc_rov_support_ScalarStructs_S_Bits32 xdc_rov_support_ScalarStructs_S_Bits32;
typedef struct xdc_rov_support_ScalarStructs_S_Char xdc_rov_support_ScalarStructs_S_Char;
typedef struct xdc_rov_support_ScalarStructs_S_UChar xdc_rov_support_ScalarStructs_S_UChar;
typedef struct xdc_rov_support_ScalarStructs_S_Double xdc_rov_support_ScalarStructs_S_Double;
typedef struct xdc_rov_support_ScalarStructs_S_Float xdc_rov_support_ScalarStructs_S_Float;
typedef struct xdc_rov_support_ScalarStructs_S_Fxn xdc_rov_support_ScalarStructs_S_Fxn;
typedef struct xdc_rov_support_ScalarStructs_S_IArg xdc_rov_support_ScalarStructs_S_IArg;
typedef struct xdc_rov_support_ScalarStructs_S_UArg xdc_rov_support_ScalarStructs_S_UArg;
typedef struct xdc_rov_support_ScalarStructs_S_Int xdc_rov_support_ScalarStructs_S_Int;
typedef struct xdc_rov_support_ScalarStructs_S_UInt xdc_rov_support_ScalarStructs_S_UInt;
typedef struct xdc_rov_support_ScalarStructs_S_Int8 xdc_rov_support_ScalarStructs_S_Int8;
typedef struct xdc_rov_support_ScalarStructs_S_UInt8 xdc_rov_support_ScalarStructs_S_UInt8;
typedef struct xdc_rov_support_ScalarStructs_S_Int16 xdc_rov_support_ScalarStructs_S_Int16;
typedef struct xdc_rov_support_ScalarStructs_S_UInt16 xdc_rov_support_ScalarStructs_S_UInt16;
typedef struct xdc_rov_support_ScalarStructs_S_Int32 xdc_rov_support_ScalarStructs_S_Int32;
typedef struct xdc_rov_support_ScalarStructs_S_UInt32 xdc_rov_support_ScalarStructs_S_UInt32;
typedef struct xdc_rov_support_ScalarStructs_S_Long xdc_rov_support_ScalarStructs_S_Long;
typedef struct xdc_rov_support_ScalarStructs_S_ULong xdc_rov_support_ScalarStructs_S_ULong;
typedef struct xdc_rov_support_ScalarStructs_S_LLong xdc_rov_support_ScalarStructs_S_LLong;
typedef struct xdc_rov_support_ScalarStructs_S_ULLong xdc_rov_support_ScalarStructs_S_ULLong;
typedef struct xdc_rov_support_ScalarStructs_S_LDouble xdc_rov_support_ScalarStructs_S_LDouble;
typedef struct xdc_rov_support_ScalarStructs_S_Ptr xdc_rov_support_ScalarStructs_S_Ptr;
typedef struct xdc_rov_support_ScalarStructs_S_SizeT xdc_rov_support_ScalarStructs_S_SizeT;
typedef struct xdc_rov_support_ScalarStructs_S_Short xdc_rov_support_ScalarStructs_S_Short;
typedef struct xdc_rov_support_ScalarStructs_S_UShort xdc_rov_support_ScalarStructs_S_UShort;
typedef struct xdc_rov_support_ScalarStructs_S_String xdc_rov_support_ScalarStructs_S_String;
typedef struct xdc_rov_support_ScalarStructs_S_VaList xdc_rov_support_ScalarStructs_S_VaList;


#endif /* xdc_rov_support__ */ 
