/home/gtbldadm/nightlybuilds/mmwave_sdk/ti/utils/cli/src/cli.c File Reference
cli.c File Reference
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <xdc/std.h>
#include <ti/sysbios/knl/Task.h>
#include <ti/common/sys_common.h>
#include <ti/drivers/uart/UART.h>
#include <ti/utils/cli/cli.h>
#include <ti/utils/cli/include/cli_internal.h>
Functions
static int32_t CLI_help (int32_t argc, char *argv[])
static void CLI_task (UArg arg0, UArg arg1)
void CLI_write (const char *format,...)
int32_t CLI_open (CLI_Cfg *ptrCLICfg)
int32_t CLI_close (void)
Variables
CLI_MCB gCLI
Global variable which tracks the CLI MCB.
Function Documentation
int32_t CLI_close (void)
Description
This is the function which is used to close the CLI module
Return values
Success - 0
Error - <0
Definition at line 354 of file cli.c.
References gCLI.
static int32_t CLI_help (int32_t argc, char * argv[]) static
Description
The function is the HELP generated by the CLI Module
Return values
Not Applicable.
Definition at line 84 of file cli.c.
References CLI_MMWaveExtensionHelp(), CLI_write(), and gCLI.
Referenced by CLI_open().
int32_t CLI_open (CLI_Cfg * ptrCLICfg)
Description
This is the function which is used to initialize and setup the CLI
Parameters
[in] ptrCLICfg Pointer to the CLI configuration
Return values
Success - 0
Error - <0
Definition at line 281 of file cli.c.
References CLI_help(), CLI_MMWaveExtensionInit(), CLI_task(), and gCLI.
Referenced by MmwDemo_CLIInit().
static void CLI_task (UArg arg0, UArg arg1) static
Description
This is the CLI Execution Task
Return values
Not Applicable.
Definition at line 122 of file cli.c.
References CLI_MMWaveExtensionHandler(), CLI_write(), and gCLI.
Referenced by CLI_open().
void CLI_write (const char * format, ...)
Description
Logging function which can log the messages to the CLI console
Parameters
[in] format Format string
Return values
Not Applicable.
Definition at line 242 of file cli.c.
References gCLI.
Referenced by _MmwDemo_debugAssert(), CLI_help(), CLI_MMWaveADCCfg(), CLI_MMWaveAdvFrameCfg(), CLI_MMWaveBPMCfgAdvanced(), CLI_MMWaveChannelCfg(), CLI_MMWaveChirpCfg(), CLI_MMWaveContModeCfg(), CLI_MMWaveDataOutputMode(), CLI_MMWaveExtensionHandler(), CLI_MMWaveExtensionHelp(), CLI_MMWaveFrameCfg(), CLI_MMWaveLowPowerCfg(), CLI_MMWaveProfileCfg(), CLI_MMWaveSubFrameCfg(), CLI_MMWaveVersion(), CLI_task(), MmwDemo_CLIADCBufCfg(), MmwDemo_CLIAnalogMonitorCfg(), MmwDemo_CLICalibDcRangeSig(), MmwDemo_CLICfarCfg(), MmwDemo_CLIChirpQualityRxSatMonCfg(), MmwDemo_CLIChirpQualitySigImgMonCfg(), MmwDemo_CLIClutterRemoval(), MmwDemo_CLICompRangeBiasAndRxChanPhaseCfg(), MmwDemo_CLIGuiMonSel(), MmwDemo_CLIMeasureRangeBiasAndRxChanPhaseCfg(), MmwDemo_CLIMultiObjBeamForming(), MmwDemo_CLIPeakGroupingCfg(), MmwDemo_eventCallbackFxn(), and MmwDemo_measurementResultOutput().
Variable Documentation
CLI_MCB gCLI
Global variable which tracks the CLI MCB.
Definition at line 68 of file cli.c.
Referenced by CLI_close(), CLI_help(), CLI_MMWaveBPMCfgAdvanced(), CLI_MMWaveChirpCfg(), CLI_MMWaveFlushCfg(), CLI_MMWaveProfileCfg(), CLI_open(), CLI_task(), and CLI_write().
Copyright 2018, Texas Instruments Incorporated