/home/gtbldadm/nightlybuilds/mmwave_sdk/ti/utils/cli/src/cli_mmwave.c File Reference
cli_mmwave.c File Reference
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <ti/common/sys_common.h>
#include <ti/common/mmwave_sdk_version.h>
#include <ti/drivers/uart/UART.h>
#include <ti/control/mmwavelink/mmwavelink.h>
#include <ti/control/mmwave/mmwave.h>
#include <ti/utils/cli/cli.h>
#include <ti/utils/cli/include/cli_internal.h>
Functions
static int32_t CLI_MMWaveVersion (int32_t argc, char *argv[])
static int32_t CLI_MMWaveFlushCfg (int32_t argc, char *argv[])
static int32_t CLI_MMWaveDataOutputMode (int32_t argc, char *argv[])
static int32_t CLI_MMWaveChannelCfg (int32_t argc, char *argv[])
static int32_t CLI_MMWaveADCCfg (int32_t argc, char *argv[])
static int32_t CLI_MMWaveProfileCfg (int32_t argc, char *argv[])
static int32_t CLI_MMWaveChirpCfg (int32_t argc, char *argv[])
static int32_t CLI_MMWaveFrameCfg (int32_t argc, char *argv[])
static int32_t CLI_MMWaveAdvFrameCfg (int32_t argc, char *argv[])
static int32_t CLI_MMWaveSubFrameCfg (int32_t argc, char *argv[])
static int32_t CLI_MMWaveLowPowerCfg (int32_t argc, char *argv[])
static int32_t CLI_MMWaveContModeCfg (int32_t argc, char *argv[])
static int32_t CLI_MMWaveBPMCfgAdvanced (int32_t argc, char *argv[])
int32_t CLI_MMWaveExtensionInit (CLI_Cfg *ptrCLICfg)
int32_t CLI_MMWaveExtensionHandler (int32_t argc, char *argv[])
void CLI_MMWaveExtensionHelp (void)
void CLI_getMMWaveExtensionConfig (MMWave_CtrlCfg *ptrCtrlCfg)
void CLI_getMMWaveExtensionOpenConfig (MMWave_OpenCfg *ptrOpenCfg)
Variables
CLI_CmdTableEntry gCLIMMWaveExtensionTable []
This is the mmWave extension table added to the CLI.
MMWave_CtrlCfg gCLIMMWaveControlCfg
Global MMWave configuration tracked by the module.
MMWave_OpenCfg gCLIMMWaveOpenCfg
Global MMWave open configuration tracked by the module.
Function Documentation
void CLI_getMMWaveExtensionConfig (MMWave_CtrlCfg * ptrCtrlCfg)
Description
This is an API provided by the CLI mmWave extension handler to get the mmWave control configuration.
Parameters
[out] ptrCtrlCfg Pointer to the control configuration populated by the API
Return values
Not applicable
Definition at line 1083 of file cli_mmwave.c.
References gCLIMMWaveControlCfg.
Referenced by MmwDemo_doSensorStart().
void CLI_getMMWaveExtensionOpenConfig (MMWave_OpenCfg * ptrOpenCfg)
Description
This is an API provided by the CLI mmWave extension handler to get the mmWave control configuration.
Parameters
[out] ptrOpenCfg Pointer to the open configuration populated by the API
Return values
Not applicable
Definition at line 1103 of file cli_mmwave.c.
References gCLIMMWaveOpenCfg.
Referenced by MmwDemo_doSensorOpen().
static int32_t CLI_MMWaveADCCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for the ADC configuration command
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 440 of file cli_mmwave.c.
References CLI_write(), and gCLIMMWaveOpenCfg.
static int32_t CLI_MMWaveAdvFrameCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for the advanced frame configuration command
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 701 of file cli_mmwave.c.
References CLI_write(), and gCLIMMWaveControlCfg.
static int32_t CLI_MMWaveBPMCfgAdvanced (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for the BPM configuration.
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 902 of file cli_mmwave.c.
References CLI_write(), gCLI, and gCLIMMWaveControlCfg.
static int32_t CLI_MMWaveChannelCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for the channel configuration command
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 399 of file cli_mmwave.c.
References CLI_write(), and gCLIMMWaveOpenCfg.
static int32_t CLI_MMWaveChirpCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for the chirp configuration command
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 579 of file cli_mmwave.c.
References CLI_write(), gCLI, and gCLIMMWaveControlCfg.
static int32_t CLI_MMWaveContModeCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for the continuous mode
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 856 of file cli_mmwave.c.
References CLI_write(), and gCLIMMWaveControlCfg.
static int32_t CLI_MMWaveDataOutputMode (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for the DFE Data Output mode.
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 341 of file cli_mmwave.c.
References CLI_write(), and gCLIMMWaveControlCfg.
int32_t CLI_MMWaveExtensionHandler (int32_t argc, char * argv[])
Description
This is the mmWave extension handler which executes mmWave extension commands. This is invoked by the main CLI wrapper only if the extension was enabled.
Parameters
[in] argc Number of detected arguments
[in] argv Detected arguments
Return values
0 - Matching mmWave extension command found
-1 - No Matching mmWave extension command
Definition at line 986 of file cli_mmwave.c.
References CLI_write(), and gCLIMMWaveExtensionTable.
Referenced by CLI_task().
void CLI_MMWaveExtensionHelp (void)
Description
This is the mmWave extension handler which is invoked by the CLI Help command handler only if the extension was enabled.
Return values
Not applicable
Definition at line 1041 of file cli_mmwave.c.
References CLI_write(), and gCLIMMWaveExtensionTable.
Referenced by CLI_help().
int32_t CLI_MMWaveExtensionInit (CLI_Cfg * ptrCLICfg)
Description
This is the mmWave extension initialization API
Return values
Success - 0
Error - <0
Definition at line 954 of file cli_mmwave.c.
References gCLIMMWaveControlCfg.
Referenced by CLI_open().
static int32_t CLI_MMWaveFlushCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for the flush configuration command
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 305 of file cli_mmwave.c.
References gCLI, gCLIMMWaveControlCfg, and gCLIMMWaveOpenCfg.
static int32_t CLI_MMWaveFrameCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for the frame configuration command
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 648 of file cli_mmwave.c.
References CLI_write(), and gCLIMMWaveControlCfg.
static int32_t CLI_MMWaveLowPowerCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for the low power command
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 817 of file cli_mmwave.c.
References CLI_write(), and gCLIMMWaveOpenCfg.
static int32_t CLI_MMWaveProfileCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for the profile configuration command
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 481 of file cli_mmwave.c.
References CLI_write(), gCLI, and gCLIMMWaveControlCfg.
static int32_t CLI_MMWaveSubFrameCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for the subframe configuration command. Only valid when used in conjunction with the advanced frame configuration.
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 754 of file cli_mmwave.c.
References CLI_write(), and gCLIMMWaveControlCfg.
static int32_t CLI_MMWaveVersion (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for the version command
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 248 of file cli_mmwave.c.
References CLI_write().
Variable Documentation
MMWave_CtrlCfg gCLIMMWaveControlCfg
Global MMWave configuration tracked by the module.
Definition at line 219 of file cli_mmwave.c.
Referenced by CLI_getMMWaveExtensionConfig(), CLI_MMWaveAdvFrameCfg(), CLI_MMWaveBPMCfgAdvanced(), CLI_MMWaveChirpCfg(), CLI_MMWaveContModeCfg(), CLI_MMWaveDataOutputMode(), CLI_MMWaveExtensionInit(), CLI_MMWaveFlushCfg(), CLI_MMWaveFrameCfg(), CLI_MMWaveProfileCfg(), and CLI_MMWaveSubFrameCfg().
CLI_CmdTableEntry gCLIMMWaveExtensionTable[]
This is the mmWave extension table added to the CLI.
Definition at line 89 of file cli_mmwave.c.
Referenced by CLI_MMWaveExtensionHandler(), and CLI_MMWaveExtensionHelp().
MMWave_OpenCfg gCLIMMWaveOpenCfg
Global MMWave open configuration tracked by the module.
Definition at line 225 of file cli_mmwave.c.
Referenced by CLI_getMMWaveExtensionOpenConfig(), CLI_MMWaveADCCfg(), CLI_MMWaveChannelCfg(), CLI_MMWaveFlushCfg(), and CLI_MMWaveLowPowerCfg().
Copyright 2018, Texas Instruments Incorporated