xwr14xx/mmw/config_hwa_util.h File Reference
config_hwa_util.h File Reference
Hardware Accelerator Configuration Utility APIs.
#include <ti/drivers/hwa/hwa.h>
Macros
#define HWAUTIL_NUM_PARAM_SETS_1D 4
#define HWAUTIL_NUM_PARAM_SETS_2D 8
#define HWAUTIL_NUM_PARAM_SETS_CFAR 1
#define HWAUTIL_NUM_PARAM_SETS_ANGLE 1
#define HWAUTIL_NUM_PARAM_SETS_2DDET_SINGLEBIN 1
Functions
void HWAutil_configRangeFFT (HWA_Handle handle, uint32_t paramSetStartIdx, uint32_t numAdcSamples, uint32_t numRangeBins, uint8_t numRxAnt, uint32_t windowOffsetBytes, uint8_t dmaTriggerSourcePing, uint8_t dmaTriggerSourcePong, uint8_t dmaDestChannelPing, uint8_t dmaDestChannelPong, uint16_t hwaMemAdcBufOffset, uint16_t hwaMemDestPingOffset, uint16_t hwaMemDestPongOffset, uint8_t hwaTriggerMode)
Configures ParameterSet for Range FFT on ADC samples from DFE.
void HWAutil_configDopplerFFT (HWA_Handle handle, uint32_t paramSetStartIdx, uint32_t dopplerFftSize, uint8_t numVirtualAnt, uint32_t numRangeBinsPerIter, uint32_t windowOffsetBytes, uint8_t dmaTriggerSourcePing, uint8_t dmaTriggerSourcePong, uint8_t dmaDestChannelPing, uint8_t dmaDestChannelPong, uint16_t hwaMemSourcePingOffset, uint16_t hwaMemSourcePongOffset, uint16_t hwaMemDestPingOffset, uint16_t hwaMemDestPongOffset, uint32_t option)
Configures ParameterSet for Range FFT on ADC samples from DFE.
void HWAutil_configDopplerFFTSingleRangeBin (HWA_Handle handle, uint32_t paramSetStartIdx, uint32_t dopplerFftSize, uint8_t numVirtualAnt, uint32_t windowOffsetBytes, uint8_t dmaTriggerSource, uint16_t hwaMemAzimSource, uint16_t hwaMemAzimDest)
Configures ParameterSet for single range in 2D FFT on 1D FFT data from radarCube.
void HWAutil_configCFAR (HWA_Handle handle, uint32_t paramSetStartIdx, uint32_t numRangeBins, uint32_t numDopplerBins, uint32_t winLen, uint32_t guardLen, uint32_t noiseDivRightShift, uint8_t peakGrouping, uint8_t cyclicMode, uint8_t nAvgMode, uint16_t detObjectListSize, uint8_t dmaTriggerSource, uint8_t dmaDestChannel, uint16_t hwaSourceBufOffset, uint16_t hwaDestBufOffset)
Configures ParameterSet for CFAR detection (The CFAR detection runs along range bins).
void HWAutil_configAngleEstAzimuth (HWA_Handle handle, uint32_t paramSetStartIdx, uint32_t numVirtualAnt, uint32_t fftOutSize, uint32_t numIter, uint16_t hwaSourceBufOffset, uint16_t hwaDestBufOffset)
Configures ParameterSet for azimuth-FFT processing.
void HWAutil_configAngleEstAzimuthElevation (HWA_Handle handle, uint32_t paramSetStartIdx, uint32_t numVirtualAntAzim, uint32_t numVirtualAntElev, uint32_t fftOutSize, uint32_t numIter, uint16_t hwaSourceAzimBufOffset, uint32_t hwaSourceElevBufOffset, uint16_t hwaDestAzimAbsBufOffset, uint16_t hwaDestAzimCplxBufOffset, uint16_t hwaDestElevCplxBufOffset)
Configures ParameterSet for azimuth/elevation-FFT processing.
Detailed Description
Hardware Accelerator Configuration Utility APIs.
NOTE: (C) Copyright 2016 Texas Instruments, Inc.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Texas Instruments Incorporated nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file config_hwa_util.h.
Macro Definition Documentation
#define HWAUTIL_NUM_PARAM_SETS_1D 4
Definition at line 45 of file config_hwa_util.h.
Referenced by HWAutil_configRangeFFT(), MmwDemo_config1D_HWA(), MmwDemo_config2D_HWA(), MmwDemo_configAngleEstimation_HWA(), MmwDemo_configCFAR_HWA(), and MmwDemo_configDetectedObj2DFFT_HWA().
#define HWAUTIL_NUM_PARAM_SETS_2D 8
Definition at line 46 of file config_hwa_util.h.
Referenced by HWAutil_configDopplerFFT(), MmwDemo_config2D_HWA(), MmwDemo_configAngleEstimation_HWA(), MmwDemo_configCFAR_HWA(), and MmwDemo_configDetectedObj2DFFT_HWA().
#define HWAUTIL_NUM_PARAM_SETS_2DDET_SINGLEBIN 1
Definition at line 49 of file config_hwa_util.h.
#define HWAUTIL_NUM_PARAM_SETS_ANGLE 1
Definition at line 48 of file config_hwa_util.h.
Referenced by MmwDemo_configDetectedObj2DFFT_HWA().
#define HWAUTIL_NUM_PARAM_SETS_CFAR 1
Definition at line 47 of file config_hwa_util.h.
Referenced by MmwDemo_configAngleEstimation_HWA(), and MmwDemo_configDetectedObj2DFFT_HWA().
Function Documentation
void HWAutil_configAngleEstAzimuth (HWA_Handle handle, uint32_t paramSetStartIdx, uint32_t numVirtualAnt, uint32_t fftOutSize, uint32_t numIter, uint16_t hwaSourceBufOffset, uint16_t hwaDestBufOffset)
Configures ParameterSet for azimuth-FFT processing.
Parameters
[in] handle HWA driver handle
[in] paramSetStartIdx HWA parameter set start index
[in] numVirtualAnt number of Virtual antennas (num_tx x num_rx)
[in] fftOutSize Azimuth FFT length
[in] numIter number of vectors on which angle-FFT has to be computed
[in] hwaSourceBufOffset HWA memory offset with input data
[in] hwaDestBufOffset HWA memory offset with computed angle-FFTs
Definition at line 664 of file config_hwa_util.c.
References log2Approx(), and MmwDemo_debugAssert.
Referenced by MmwDemo_configAngleEstimation_HWA().
void HWAutil_configAngleEstAzimuthElevation (HWA_Handle handle, uint32_t paramSetStartIdx, uint32_t numVirtualAntAzim, uint32_t numVirtualAntElev, uint32_t fftOutSize, uint32_t numIter, uint16_t hwaSourceAzimBufOffset, uint32_t hwaSourceElevBufOffset, uint16_t hwaDestAzimAbsBufOffset, uint16_t hwaDestAzimCplxBufOffset, uint16_t hwaDestElevCplxBufOffset)
Configures ParameterSet for azimuth/elevation-FFT processing.
Parameters
[in] handle HWA driver handle
[in] paramSetStartIdx HWA parameter set start index
[in] numVirtualAntAzim number of Azimuth Virtual antennas (num_azimuth_tx x num_rx)
[in] numVirtualAntElev number of Elevation Virtual antennas (num_elevation_tx x num_rx)
[in] fftOutSize Azimuth FFT length
[in] numIter number of vectors on which angle-FFT has to be computed
[in] hwaSourceAzimBufOffset HWA memory offset with azimuth input data
[in] hwaSourceElevBufOffset HWA memory offset with elevation input data
[in] hwaDestAzimAbsBufOffset HWA memory offset with computed azimuth-FFTs (log magnitude values)
[in] hwaDestAzimCplxBufOffset HWA memory offset with computed azimuth-FFTs (complex values)
[in] hwaDestElevCplxBufOffset HWA memory offset with computed elevation-FFTs (complex values)
Definition at line 714 of file config_hwa_util.c.
References log2Approx(), and MmwDemo_debugAssert.
Referenced by MmwDemo_configAngleEstimation_HWA().
void HWAutil_configCFAR (HWA_Handle handle, uint32_t paramSetStartIdx, uint32_t numRangeBins, uint32_t numDopplerBins, uint32_t winLen, uint32_t guardLen, uint32_t noiseDivRightShift, uint8_t peakGrouping, uint8_t cyclicMode, uint8_t nAvgMode, uint16_t detObjectListSize, uint8_t dmaTriggerSource, uint8_t dmaDestChannel, uint16_t hwaSourceBufOffset, uint16_t hwaDestBufOffset)
Configures ParameterSet for CFAR detection (The CFAR detection runs along range bins).
Parameters
[in] handle HWA driver handle
[in] paramSetStartIdx HWA parameter set start index
[in] numRangeBins Number of range bins
[in] numDopplerBins NUmber of Doppler bins
[in] winLen window length in CFAR
[in] guardLen guard length in CFAR
[in] noiseDivRightShift noiseDiv factor expressed as right shift in CFAR
[in] peakGrouping peakGrouping flag in CFAR
[in] cyclicMode cyclic mode in CFAR
[in] nAvgMode noise averaging mode in CFAR
[in] detObjectListSize maximum size of list of detected objects
[in] dmaTriggerSource DMA trigger source channel
[in] dmaDestChannel DMA destination channel
[in] hwaSourceBufOffset HWA memory offset with input data: log magnitude 2nd D FFT matrix
[in] hwaDestBufOffset HWA memory offset with CFAR output results: List of detected objects as array of structures cfarDetOutput_t
Definition at line 585 of file config_hwa_util.c.
References MmwDemo_debugAssert.
Referenced by MmwDemo_configCFAR_HWA().
void HWAutil_configDopplerFFT (HWA_Handle handle, uint32_t paramSetStartIdx, uint32_t dopplerFftSize, uint8_t numVirtualAnt, uint32_t numRangeBinsPerIter, uint32_t windowOffsetBytes, uint8_t dmaTriggerSourcePing, uint8_t dmaTriggerSourcePong, uint8_t dmaDestChannelPing, uint8_t dmaDestChannelPong, uint16_t hwaMemSourcePingOffset, uint16_t hwaMemSourcePongOffset, uint16_t hwaMemDestPingOffset, uint16_t hwaMemDestPongOffset, uint32_t option)
Configures ParameterSet for Range FFT on ADC samples from DFE.
Parameters
[in] handle HWA driver handle
[in] paramSetStartIdx HWA parameter set start index
[in] dopplerFftSize Doppler FFT size
[in] numVirtualAnt Number of Rx virtual antennas
[in] numRangeBinsPerIter Number of range bins per iteration (currently has to be 2)
[in] windowOffsetBytes Window offset in bytes (for pre-FFT windowing)
[in] dmaTriggerSourcePing DMA trigger source channel for Ping param set (Ping param set calculates 2nd D FFT for two rows, (even pair of rows))
[in] dmaTriggerSourcePong DMA trigger source channel for Pong param sets (Pong param set calculates 2nd D FFT for two rows, (odd pair of rows))
[in] dmaDestChannelPing DMA destination channel for Ping param sets
[in] dmaDestChannelPong DMA destination channel for Pong param sets
[in] hwaMemSourcePingOffset HWA memory offset with Ping input data, two rows (range bins) of 1st D FFT symbols
[in] hwaMemSourcePongOffset HWA memory offset with Pong input data, two rows (range bins) with 1st D FFT symbols
[in] hwaMemDestPingOffset HWA memory offset with Ping output data, two rows (range bins) with 2nd D FFT complex symbols, followed by two rows (range bins) with summed log magnitude 2nd D FFT symbols across all antennas
[in] hwaMemDestPongOffset HWA memory offset with Ping output data, two rows (range bins) with 2nd D FFT complex symbols, followed by two rows (range bins) with summed log magnitude 2nd D FFT symbols across all antennas
[in] option Option to seperate/combine 2DFFT and Log-Mag operation. By combining 2DFFT and Log-Mag operation, high precision can be achieved. 0 - seperate, 1 - combine
Definition at line 233 of file config_hwa_util.c.
References DATA_PATH_CHAIN_SEPARATE_LOGMAG, HWAUTIL_NUM_PARAM_SETS_2D, log2Approx(), and MmwDemo_debugAssert.
Referenced by HWAutil_configRangeFFT(), and MmwDemo_config2D_HWA().
void HWAutil_configDopplerFFTSingleRangeBin (HWA_Handle handle, uint32_t paramSetStartIdx, uint32_t dopplerFftSize, uint8_t numVirtualAnt, uint32_t windowOffsetBytes, uint8_t dmaTriggerSource, uint16_t hwaMemAzimSource, uint16_t hwaMemAzimDest)
Configures ParameterSet for single range in 2D FFT on 1D FFT data from radarCube.
Parameters
[in] handle HWA driver handle
[in] paramSetStartIdx HWA parameter set start index
[in] dopplerFftSize Doppler FFT size
[in] numVirtualAnt Number of Rx virtual antennas
[in] windowOffsetBytes Window offset in bytes (for pre-FFT windowing)
[in] dmaTriggerSource DMA trigger source channel for Ping param set (Ping param set calculates 2nd D FFT for two rows, (even pair of rows))
[in] hwaMemAzimSource HWA memory offset with single range bin input data of 1D FFT symbols
[in] hwaMemAzimDest HWA memory offset with single range bin 2D FFT output data
Definition at line 517 of file config_hwa_util.c.
References log2Approx().
Referenced by MmwDemo_configDetectedObj2DFFT_HWA().
void HWAutil_configRangeFFT (HWA_Handle handle, uint32_t paramSetStartIdx, uint32_t numAdcSamples, uint32_t numRangeBins, uint8_t numRxAnt, uint32_t windowOffsetBytes, uint8_t dmaTriggerSourcePing, uint8_t dmaTriggerSourcePong, uint8_t dmaDestChannelPing, uint8_t dmaDestChannelPong, uint16_t hwaMemAdcBufOffset, uint16_t hwaMemDestPingOffset, uint16_t hwaMemDestPongOffset, uint8_t hwaTriggerMode)
Configures ParameterSet for Range FFT on ADC samples from DFE.
Parameters
[in] handle HWA driver handle
[in] paramSetStartIdx HWA parameter set start index
[in] numAdcSamples Number of ADC samples
[in] numRangeBins Number of range bins (1st D FFT size)
[in] numRxAnt Number of Rx antennas
[in] windowOffsetBytes Window offset in bytes (for pre-FFT windowing)
[in] dmaTriggerSourcePing DMA trigger source channel for Ping param sets
[in] dmaTriggerSourcePong DMA trigger source channel for Pong param sets
[in] dmaDestChannelPing DMA destination channel for Ping param sets
[in] dmaDestChannelPong DMA destination channel for Pong param sets
[in] hwaMemAdcBufOffset HWA memory offset ADC buffer
[in] hwaMemDestPingOffset HWA memory offset for Ping destination
[in] hwaMemDestPongOffset HWA memory offset for Pong destination
[in] hwaTriggerMode HWA trigger mode
Definition at line 84 of file config_hwa_util.c.
References HWAutil_configDopplerFFT(), HWAUTIL_NUM_PARAM_SETS_1D, log2Approx(), and MmwDemo_debugAssert.
Referenced by MmwDemo_config1D_HWA().
Copyright 2018, Texas Instruments Incorporated