xwr14xx/mmw/config_edma_util.h File Reference
config_edma_util.h File Reference
EDMA Configuration Utility API definitions.
#include <ti/drivers/edma/edma.h>
Functions
int32_t EDMAutil_configHwaOneHotSignature (EDMA_Handle handle, uint8_t chId, bool isEventTriggered, uint32_t *pSrcAddress, uint32_t *pDestAddress, uint16_t aCount, uint16_t bCount, uint16_t cCount, uint16_t linkChId)
int32_t EDMAutil_configHwaTranspose (EDMA_Handle handle, uint8_t chId, uint16_t linkChId, uint8_t chainChId, uint32_t *pSrcAddress, uint32_t *pDestAddress, uint8_t numAnt, uint16_t numRangeBins, uint16_t numChirpsPerFrame, bool isIntermediateChainingEnabled, bool isFinalChainingEnabled, bool isTransferCompletionEnabled, EDMA_transferCompletionCallbackFxn_t transferCompletionCallbackFxn, uintptr_t transferCompletionCallbackFxnArg)
int32_t EDMAutil_configHwaContiguous (EDMA_Handle handle, uint8_t chId, bool isEventTriggered, uint8_t linkChId, uint8_t chainChId, uint32_t *pSrcAddress, uint32_t *pDestAddress, uint16_t numBytes, uint16_t numBlocks, uint16_t srcIncrBytes, uint16_t dstIncrBytes, bool isIntermediateChainingEnabled, bool isFinalChainingEnabled, bool isTransferCompletionEnabled, EDMA_transferCompletionCallbackFxn_t transferCompletionCallbackFxn, uintptr_t transferCompletionCallbackFxnArg)
int32_t EDMAutil_configSyncAwithChaining (EDMA_Handle handle, uint8_t *srcBuff, uint8_t *dstBuff, uint8_t chId, uint8_t chainId, bool isEventTriggered, uint16_t shadowParamId, uint16_t aCount, uint16_t bCount, int16_t srcBIdx, int16_t dstBIdx, uint8_t eventQueueId, bool isFinalTransferInterruptEnabled, bool isFinalChainingEnabled, EDMA_transferCompletionCallbackFxn_t transferCompletionCallbackFxn, uintptr_t transferCompletionCallbackFxnArg)
Detailed Description
EDMA Configuration Utility API definitions.
NOTE: (C) Copyright 2016 Texas Instruments, Inc.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Texas Instruments Incorporated nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file config_edma_util.h.
Function Documentation
int32_t EDMAutil_configHwaContiguous (EDMA_Handle handle, uint8_t chId, bool isEventTriggered, uint8_t linkChId, uint8_t chainChId, uint32_t * pSrcAddress, uint32_t * pDestAddress, uint16_t numBytes, uint16_t numBlocks, uint16_t srcIncrBytes, uint16_t dstIncrBytes, bool isIntermediateChainingEnabled, bool isFinalChainingEnabled, bool isTransferCompletionEnabled, EDMA_transferCompletionCallbackFxn_t transferCompletionCallbackFxn, uintptr_t transferCompletionCallbackFxnArg)
Description
Utility function for configuring EDMA for a contiguous (as opposed to transpose) transfer.
Parameters
[in] handle EDMA handle.
[in] chId Channel ID
[in] isEventTriggered true if chId is event triggered else false.
[in] linkChId Link Channel Id (or rather PaRAM Id) for shadow linking (reloading to prevent reprogramming).
[in] chainChId Chain Channel Id, chId will be chained to this.
[in] pSrcAddress Pointer to source address.
[in] pDestAddress Pointer to destination address.
[in] numBytes Number of bytes, determines aCount (the 1st dimension of transfer).
[in] numBlocks Number of blocks, determines bCount (the 2nd dimension of transfer).
[in] srcIncrBytes Source increment bytes, determines sourceBindex (jump in source address in bytes after every 1st dimension (aCount related) transfer).
[in] dstIncrBytes Destination increment bytes, determines destinatinoBindex (jump in destination address in bytes after every 1st dimension (aCount related) transfer).
[in] isIntermediateChainingEnabled Set to 'true' if intermediate transfer chaining is to be enabled.
[in] isFinalChainingEnabled Set to 'true' if final transfer chaining to be enabled.
[in] isTransferCompletionEnabled Set to 'true' if final transfer completion indication is to be enabled.
[in] transferCompletionCallbackFxn Transfer completion call back function.
[in] transferCompletionCallbackFxnArg Argument for transfer completion call back function.
Return values
EDMA driver error code, see "EDMA_ERROR_CODES" in EDMA API.
Definition at line 213 of file config_edma_util.c.
References EDMA_setup_shadow_link(), and MmwDemo_debugAssert.
Referenced by MmwDemo_config2D_EDMA(), MmwDemo_config2DSingleBin_EDMA(), and MmwDemo_configCFAR_EDMA().
int32_t EDMAutil_configHwaOneHotSignature (EDMA_Handle handle, uint8_t chId, bool isEventTriggered, uint32_t * pSrcAddress, uint32_t * pDestAddress, uint16_t aCount, uint16_t bCount, uint16_t cCount, uint16_t linkChId)
Description
Utility function for configuring a simple EDMA transfer used for transferring a specific 32-bit word (from a table of 16 words each containing a 1-hot signature) to the HWA's DMA completion register. The counts and addresses can be obtained from HWA APIs issued for configuring HWA. This is used to implement the DMA based trigger mode of the HWACC (search for "DMA based trigger" in the HWACC spec document)
Parameters
[in] handle EDMA handle.
[in] chId Channel ID
[in] isEventTriggered true if chId is event triggered else false
[in] pSrcAddress Pointer to source address.
[in] pDestAddress Pointer to destination address.
[in] aCount A count.
[in] bCount B count.
[in] cCount C count.
[in] linkChId Link Channel Id (or rather PaRAM Id) for shadow linking (reloading to prevent reprogramming).
Return values
EDMA driver error code, see "EDMA_ERROR_CODES" in EDMA API.
Definition at line 85 of file config_edma_util.c.
References EDMA_setup_shadow_link(), and MmwDemo_debugAssert.
Referenced by MmwDemo_config1D_EDMA(), MmwDemo_config2D_EDMA(), MmwDemo_config2DSingleBin_EDMA(), and MmwDemo_configCFAR_EDMA().
int32_t EDMAutil_configHwaTranspose (EDMA_Handle handle, uint8_t chId, uint16_t linkChId, uint8_t chainChId, uint32_t * pSrcAddress, uint32_t * pDestAddress, uint8_t numAnt, uint16_t numRangeBins, uint16_t numChirpsPerFrame, bool isIntermediateChainingEnabled, bool isFinalChainingEnabled, bool isTransferCompletionEnabled, EDMA_transferCompletionCallbackFxn_t transferCompletionCallbackFxn, uintptr_t transferCompletionCallbackFxnArg)
Description
Utility function for configuring EDMA for a transpose transfer (used to write 1D-FFT output to L3 in a transpose fashion).
Parameters
[in] handle EDMA handle.
[in] chId Channel ID
[in] linkChId Link Channel Id (or rather PaRAM Id) for shadow linking (reloading to prevent reprogramming).
[in] chainChId Chain Channel Id, chId will be chained to this.
[in] pSrcAddress Pointer to source address.
[in] pDestAddress Pointer to destination address.
[in] numAnt Number of receive antennae.
[in] numRangeBins Number of range bins.
[in] numChirpsPerFrame Number of chirps per frame.
[in] isIntermediateChainingEnabled Set to 'true' if intermediate transfer chaining is to be enabled.
[in] isFinalChainingEnabled Set to 'true' if final transfer chaining to be enabled.
[in] isTransferCompletionEnabled Set to 'true' if final transfer completion indication is to be enabled.
[in] transferCompletionCallbackFxn Transfer completion call back function.
[in] transferCompletionCallbackFxnArg Argument for transfer completion call back function.
Return values
EDMA driver error code, see "EDMA_ERROR_CODES" in EDMA API.
Definition at line 144 of file config_edma_util.c.
References EDMA_setup_shadow_link(), and MmwDemo_debugAssert.
Referenced by MmwDemo_config1D_EDMA().
int32_t EDMAutil_configSyncAwithChaining (EDMA_Handle handle, uint8_t * srcBuff, uint8_t * dstBuff, uint8_t chId, uint8_t chainId, bool isEventTriggered, uint16_t shadowParamId, uint16_t aCount, uint16_t bCount, int16_t srcBIdx, int16_t dstBIdx, uint8_t eventQueueId, bool isFinalTransferInterruptEnabled, bool isFinalChainingEnabled, EDMA_transferCompletionCallbackFxn_t transferCompletionCallbackFxn, uintptr_t transferCompletionCallbackFxnArg)
Description
Utility function for configuring EDMA for a Sync A transfer transfer.
Parameters
[in] handle EDMA handle.
[in] srcBuff Pointer to source buffer.
[in] dstBuff Pointer to destination buffer.
[in] chId Channel ID
[in] chainId Chain Channel Id, chId will be chained to this.
[in] isEventTriggered true if chId is event triggered else false.
[in] shadowParamId Shadow Param Id
[in] aCount A count.
[in] bCount B count.
[in] srcBIdx Source B index
[in] dstBIdx Destination B index
[in] eventQueueId Event Queue Id on which to schedule the transfer.
[in] isFinalTransferInterruptEnabled Set to 'true' if final transfer interrupt to be enabled
[in] isFinalChainingEnabled Set to 'true' if final transfer chaining to be enabled
[in] transferCompletionCallbackFxn Transfer completion call back function.
[in] transferCompletionCallbackFxnArg Transfer completion call back function argument.
Return values
EDMA driver error code, see "EDMA_ERROR_CODES" in EDMA API.
Definition at line 286 of file config_edma_util.c.
References EDMA_setup_shadow_link().
Referenced by MmwDemo_dataPathConfigCQEdma().
Copyright 2018, Texas Instruments Incorporated