xwr14xx/mmw/data_path.c File Reference
data_path.c File Reference
Implements Data path processing functionality.
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <xdc/std.h>
#include <xdc/cfg/global.h>
#include <xdc/runtime/IHeap.h>
#include <xdc/runtime/System.h>
#include <xdc/runtime/Error.h>
#include <xdc/runtime/HeapMin.h>
#include <xdc/runtime/Memory.h>
#include <ti/sysbios/BIOS.h>
#include <ti/sysbios/knl/Task.h>
#include <ti/sysbios/knl/Event.h>
#include <ti/sysbios/knl/Semaphore.h>
#include <ti/sysbios/knl/Clock.h>
#include <ti/sysbios/heaps/HeapBuf.h>
#include <ti/sysbios/heaps/HeapMem.h>
#include <ti/drivers/osal/DebugP.h>
#include <assert.h>
#include <ti/common/sys_common.h>
#include <ti/drivers/osal/SemaphoreP.h>
#include <ti/drivers/edma/edma.h>
#include <ti/drivers/esm/esm.h>
#include <ti/drivers/soc/soc.h>
#include <ti/demo/utils/rx_ch_bias_measure.h>
#include "config_edma_util.h"
#include "config_hwa_util.h"
#include "post_processing.h"
#include "data_path.h"
#include "mmw.h"
Macros
#define DebugP_ASSERT_ENABLED 1
#define SOC_MAX_NUM_RX_ANTENNAS 4
#define SOC_MAX_NUM_TX_ANTENNAS 3
Functions
int32_t MmwDemo_config2D_EDMA (MmwDemo_DataPathObj *obj)
void MmwDemo_config2D_HWA (MmwDemo_DataPathObj *obj)
void MmwDemo_dataPathTrigger2D (MmwDemo_DataPathObj *obj)
void MmwDemo_dataPathWait2D (MmwDemo_DataPathObj *obj)
int32_t MmwDemo_config1D_EDMA (MmwDemo_DataPathObj *obj)
int32_t MmwDemo_configCFAR_EDMA (MmwDemo_DataPathObj *obj)
void MmwDemo_configCFAR_HWA (MmwDemo_DataPathObj *obj)
void MmwDemo_dataPathTriggerCFAR (MmwDemo_DataPathObj *obj)
void MmwDemo_dataPathWaitCFAR (MmwDemo_DataPathObj *obj)
void MmwDemo_EDMA_transferCompletionCallbackFxn (uintptr_t arg, uint8_t transferCompletionCode)
void MmwDemo_dataPathHwaDoneIsrCallback (void *arg)
static MmwDemo_genWindow (uint32_t *win, uint32_t winIndx, float phi, uint32_t winType)
void MmwDemo_dataPathConfigCommon (MmwDemo_DataPathObj *obj)
void MmwDemo_hwaInit (MmwDemo_DataPathObj *obj)
void MmwDemo_edmaInit (MmwDemo_DataPathObj *obj)
void MmwDemo_EDMA_errorCallbackFxn (EDMA_Handle handle, EDMA_errorInfo_t *errorInfo)
void MmwDemo_EDMA_transferControllerErrorCallbackFxn (EDMA_Handle handle, EDMA_transferControllerErrorInfo_t *errorInfo)
void MmwDemo_hwaOpen (MmwDemo_DataPathObj *obj, SOC_Handle socHandle)
void MmwDemo_hwaClose (MmwDemo_DataPathObj *obj)
void MmwDemo_edmaOpen (MmwDemo_DataPathObj *obj)
void MmwDemo_edmaClose (MmwDemo_DataPathObj *obj)
void MmwDemo_dataPathObjInit (MmwDemo_DataPathObj *obj, MmwDemo_CliCfg_t *cliCfg, MmwDemo_CliCommonCfg_t *cliCommonCfg)
void MmwDemo_dataPathCfgBuffers (MmwDemo_DataPathObj *obj, MmwDemoMemPool_t *pool)
void MmwDemo_memPoolReset (MmwDemoMemPool_t *pool)
uint8_t * MmwDemo_memPoolAlloc (MmwDemoMemPool_t *pool, uint32_t size)
int32_t MmwDemo_config2DSingleBin_EDMA (MmwDemo_DataPathObj *obj, uint32_t srcBuffPtr, uint32_t dstBuffPtr)
void MmwDemo_dataPathTrigger2DSingleBin (MmwDemo_DataPathObj *obj)
void MmwDemo_config1D_HWA (MmwDemo_DataPathObj *obj)
void MmwDemo_dataPathTrigger1D (MmwDemo_DataPathObj *obj)
void MmwDemo_dataPathWait1D (MmwDemo_DataPathObj *obj)
void MmwDemo_configDetectedObj2DFFT_HWA (MmwDemo_DataPathObj *obj, uint32_t *dataInPtr, uint32_t *dataOutPtr)
void MmwDemo_configAngleEstimation_HWA (MmwDemo_DataPathObj *obj, uint32_t numObjOut)
void MmwDemo_dataPathWait2DFFTDetObj (MmwDemo_DataPathObj *obj)
void MmwDemo_dataPathTriggerAngleEstimation (MmwDemo_DataPathObj *obj)
void MmwDemo_dataPathWaitAngleEstimation (MmwDemo_DataPathObj *obj)
void MmwDemo_dcRangeSignatureCompensation (MmwDemo_DataPathObj *obj)
void MmwDemo_rxChanPhaseBiasCompensation (MmwDemo_DataPathObj *obj, uint32_t numObj, cmplx16ImRe_t *azimuthSymbols, cmplx16ImRe_t *elevationSymbols)
Function Name : MmwDemo_rxChanPhaseBiasCompensation.
void MmwDemo_process2D (MmwDemo_DataPathObj *obj)
void MmwDemo_processCfar (MmwDemo_DataPathObj *obj, uint16_t *numDetectedObjects)
void MmwDemo_processAngle (MmwDemo_DataPathObj *obj)
uint32_t MmwDemo_pow2roundup (uint32_t x)
void MmwDemo_dataPathDeleteSemaphore (MmwDemo_DataPathObj *obj)
Variables
mmwHwaBuf_t gMmwHwaMemBuf [MMW_HWA_NUM_MEM_BUFS]
Detailed Description
Implements Data path processing functionality.
NOTE: (C) Copyright 2016 Texas Instruments, Inc.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Texas Instruments Incorporated nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file data_path.c.
Macro Definition Documentation
#define DebugP_ASSERT_ENABLED 1
Definition at line 68 of file data_path.c.
#define SOC_MAX_NUM_RX_ANTENNAS 4
Definition at line 896 of file data_path.c.
Referenced by MmwDemo_dataPathCfgBuffers().
#define SOC_MAX_NUM_TX_ANTENNAS 3
Definition at line 897 of file data_path.c.
Referenced by MmwDemo_dataPathCfgBuffers().
Function Documentation
int32_t MmwDemo_config1D_EDMA (MmwDemo_DataPathObj * obj)
Description
Configures all 1D processing related EDMA configuration.
Parameters
[in] obj Pointer to data path object
Return values
EDMA error code, see EDMA API.
Definition at line 1031 of file data_path.c.
References MmwDemo_DataPathObj_t::edmaHandle, EDMAutil_configHwaOneHotSignature(), EDMAutil_configHwaTranspose(), MMW_EDMA_1D_PING_CH_ID, MMW_EDMA_1D_PING_CHAIN_CH_ID, MMW_EDMA_1D_PING_ONE_HOT_SHADOW_LINK_CH_ID, MMW_EDMA_1D_PING_SHADOW_LINK_CH_ID, MMW_EDMA_1D_PONG_CH_ID, MMW_EDMA_1D_PONG_CHAIN_CH_ID, MMW_EDMA_1D_PONG_ONE_HOT_SHADOW_LINK_CH_ID, MMW_EDMA_1D_PONG_SHADOW_LINK_CH_ID, MMW_HWA_1D_OUT_PING, MMW_HWA_1D_OUT_PONG, MMW_HWA_DMA_TRIGGER_SOURCE_1D_PING, MMW_HWA_DMA_TRIGGER_SOURCE_1D_PONG, MmwDemo_EDMA_transferCompletionCallbackFxn(), MmwDemo_DataPathObj_t::numChirpsPerFrame, MmwDemo_DataPathObj_t::numRangeBins, MmwDemo_DataPathObj_t::numRxAntennas, and MmwDemo_DataPathObj_t::radarCube.
Referenced by MmwDemo_dataPathConfigCommon().
void MmwDemo_config1D_HWA (MmwDemo_DataPathObj * obj)
Description
Configure HWA for 1D processing.
Parameters
[in] obj Pointer to data path obj.
Return values
none.
Definition at line 1302 of file data_path.c.
References ADDR_TRANSLATE_CPU_TO_HWA, DATA_PATH_STANDALONE, MmwDemo_DataPathObj_t::dataPathMode, MmwDemo_DataPathObj_t::hwaHandle, HWAutil_configRangeFFT(), HWAUTIL_NUM_PARAM_SETS_1D, MMW_HWA_1D_ADCBUF_INP, MMW_HWA_1D_OUT_PING, MMW_HWA_1D_OUT_PONG, MMW_HWA_DMA_DEST_CHANNEL_1D_PING, MMW_HWA_DMA_DEST_CHANNEL_1D_PONG, MMW_HWA_DMA_TRIGGER_SOURCE_1D_PING, MMW_HWA_DMA_TRIGGER_SOURCE_1D_PONG, MMW_HWA_START_POS_PARAMSETS_1D, MMW_HWA_WINDOWRAM_1D_OFFSET, MmwDemo_debugAssert, MmwDemo_DataPathObj_t::numAdcSamples, MmwDemo_DataPathObj_t::numChirpsPerFrame, MmwDemo_DataPathObj_t::numRangeBins, and MmwDemo_DataPathObj_t::numRxAntennas.
Referenced by MmwDemo_dataPathConfig(), and MmwDemo_dataPathTask().
int32_t MmwDemo_config2D_EDMA (MmwDemo_DataPathObj * obj)
Description
Configures all 2D processing related EDMA configuration.
Parameters
[in] obj Pointer to data path object
Return values
EDMA error code, see EDMA API.
Definition at line 211 of file data_path.c.
References DATA_PATH_CHAIN_SEPARATE_LOGMAG, MmwDemo_DataPathObj_t::datapathChainSel, MmwDemo_DataPathObj_t::edmaHandle, EDMAutil_configHwaContiguous(), EDMAutil_configHwaOneHotSignature(), MmwDemo_DataPathObj_t::hwaHandle, MMW_EDMA_2D_PING_CH_ID, MMW_EDMA_2D_PING_CHAIN_CH_ID1, MMW_EDMA_2D_PING_CHAIN_CH_ID2, MMW_EDMA_2D_PING_CHAIN_CH_ID3, MMW_EDMA_2D_PING_SHADOW_LINK_CH_ID1, MMW_EDMA_2D_PING_SHADOW_LINK_CH_ID2, MMW_EDMA_2D_PING_SHADOW_LINK_CH_ID3, MMW_EDMA_2D_PING_SHADOW_LINK_CH_ID4, MMW_EDMA_2D_PONG_CH_ID, MMW_EDMA_2D_PONG_CHAIN_CH_ID1, MMW_EDMA_2D_PONG_CHAIN_CH_ID2, MMW_EDMA_2D_PONG_CHAIN_CH_ID3, MMW_EDMA_2D_PONG_SHADOW_LINK_CH_ID1, MMW_EDMA_2D_PONG_SHADOW_LINK_CH_ID2, MMW_EDMA_2D_PONG_SHADOW_LINK_CH_ID3, MMW_EDMA_2D_PONG_SHADOW_LINK_CH_ID4, MMW_HWA_2D_INP_PING, MMW_HWA_2D_INP_PONG, MMW_HWA_2D_OUT_PING, MMW_HWA_2D_OUT_PONG, MMW_HWA_DMA_TRIGGER_SOURCE_2D_PING, MMW_HWA_DMA_TRIGGER_SOURCE_2D_PONG, MmwDemo_EDMA_transferCompletionCallbackFxn(), MmwDemo_DataPathObj_t::numDopplerBins, MmwDemo_DataPathObj_t::numRangeBins, MmwDemo_DataPathObj_t::numRangeBinsPerTransfer, MmwDemo_DataPathObj_t::numVirtualAntennas, MmwDemo_DataPathObj_t::radarCube, and MmwDemo_DataPathObj_t::rangeDopplerLogMagMatrix.
Referenced by MmwDemo_dataPathConfigCommon().
void MmwDemo_config2D_HWA (MmwDemo_DataPathObj * obj)
Description
Configure HWA for 2D processing.
Parameters
[in] obj Pointer to data path obj.
Return values
none.
Definition at line 777 of file data_path.c.
References ADDR_TRANSLATE_CPU_TO_HWA, MmwDemo_DataPathObj_t::datapathChainSel, MmwDemo_DataPathObj_t::hwaHandle, HWAutil_configDopplerFFT(), HWAUTIL_NUM_PARAM_SETS_1D, HWAUTIL_NUM_PARAM_SETS_2D, MMW_HWA_2D_INP_PING, MMW_HWA_2D_INP_PONG, MMW_HWA_2D_OUT_PING, MMW_HWA_2D_OUT_PONG, MMW_HWA_DMA_DEST_CHANNEL_2D_PING, MMW_HWA_DMA_DEST_CHANNEL_2D_PONG, MMW_HWA_DMA_TRIGGER_SOURCE_2D_PING, MMW_HWA_DMA_TRIGGER_SOURCE_2D_PONG, MMW_HWA_WINDOWRAM_1D_OFFSET, MmwDemo_debugAssert, MmwDemo_DataPathObj_t::numAdcSamples, MmwDemo_DataPathObj_t::numDopplerBins, MmwDemo_DataPathObj_t::numRangeBins, MmwDemo_DataPathObj_t::numRangeBinsPerTransfer, and MmwDemo_DataPathObj_t::numVirtualAntennas.
Referenced by MmwDemo_process2D().
int32_t MmwDemo_config2DSingleBin_EDMA (MmwDemo_DataPathObj * obj, uint32_t srcBuffPtr, uint32_t dstBuffPtr)
Description
Configures EDMA to prepare for single range bin 2D FFT. It copies a signle bin 1D FFT symbols from radarCube to HWA memory. Then triggers 2D FFT in HWA.
Parameters
[in] obj Pointer to data path object
[in] srcBuffPtr Source buffer address for Single bin 2D FFT operation
[in] dstBuffPtr HWA memory offset to single bin 2D FFT
Return values
EDMA error code, see EDMA API.
Definition at line 1212 of file data_path.c.
References MmwDemo_DataPathObj_t::edmaHandle, EDMAutil_configHwaContiguous(), EDMAutil_configHwaOneHotSignature(), MmwDemo_DataPathObj_t::hwaHandle, MMW_EDMA_2DFFT_SINGLERBIN_CH_ID, MMW_EDMA_2DFFT_SINGLERBIN_CHAIN_CH_ID, MMW_EDMA_2DFFT_SINGLERBIN_SHADOW_LINK_CH_ID, MMW_EDMA_2DFFT_SINGLERBIN_SHADOW_LINK_CH_ID2, MMW_HWA_DMA_TRIGGER_SINGLEBIN_2DFFT, MmwDemo_DataPathObj_t::numDopplerBins, and MmwDemo_DataPathObj_t::numVirtualAntennas.
Referenced by MmwDemo_configCFAR_EDMA(), and MmwDemo_processAngle().
void MmwDemo_configAngleEstimation_HWA (MmwDemo_DataPathObj * obj, uint32_t numObjOut)
Description
Configures HWA for angle (azimuth) estimation.
Parameters
[in] obj Pointer to data path object
[in] numObjOut Number of detected objects
Return values
NONE
Definition at line 1668 of file data_path.c.
References ADDR_TRANSLATE_CPU_TO_HWA, MmwDemo_DataPathObj_t::hwaHandle, HWAutil_configAngleEstAzimuth(), HWAutil_configAngleEstAzimuthElevation(), HWAUTIL_NUM_PARAM_SETS_1D, HWAUTIL_NUM_PARAM_SETS_2D, HWAUTIL_NUM_PARAM_SETS_CFAR, MMW_HWA_ANGLE_AZIM_ABS_OUT, MMW_HWA_ANGLE_AZIM_CPLX_OUT, MMW_HWA_ANGLE_AZIM_INP, MMW_HWA_ANGLE_ELEV_CPLX_OUT, MMW_HWA_ANGLE_ELEV_INP, MmwDemo_debugAssert, MmwDemo_DataPathObj_t::numAngleBins, MmwDemo_DataPathObj_t::numVirtualAntAzim, MmwDemo_DataPathObj_t::numVirtualAntElev, and MmwDemo_DataPathObj_t::numVirtualAntennas.
Referenced by MmwDemo_processAngle().
int32_t MmwDemo_configCFAR_EDMA (MmwDemo_DataPathObj * obj)
Description
Configures all CFAR processing related EDMA configuration.
Parameters
[in] obj Pointer to data path object
Return values
EDMA error code, see EDMA API.
Definition at line 1131 of file data_path.c.
References MmwDemo_DataPathObj_t::cfarDetectionOut, MmwDemo_DataPathObj_t::edmaHandle, EDMAutil_configHwaContiguous(), EDMAutil_configHwaOneHotSignature(), MmwDemo_DataPathObj_t::hwaHandle, MMW_EDMA_CFAR_INP_CH_ID, MMW_EDMA_CFAR_INP_CHAIN_CH_ID, MMW_EDMA_CFAR_INP_SHADOW_LINK_CH_ID1, MMW_EDMA_CFAR_INP_SHADOW_LINK_CH_ID2, MMW_EDMA_CFAR_OUT_CH_ID, MMW_EDMA_CFAR_OUT_CHAIN_CH_ID, MMW_EDMA_CFAR_OUT_SHADOW_LINK_CH_ID1, MMW_HWA_CFAR_INP, MMW_HWA_CFAR_OUT, MMW_HWA_DMA_TRIGGER_SOURCE_CFAR, MMW_MAX_OBJ_OUT, MmwDemo_config2DSingleBin_EDMA(), MmwDemo_EDMA_transferCompletionCallbackFxn(), MmwDemo_DataPathObj_t::numDopplerBins, MmwDemo_DataPathObj_t::numRangeBins, and MmwDemo_DataPathObj_t::rangeDopplerLogMagMatrix.
Referenced by MmwDemo_dataPathConfigCommon().
void MmwDemo_configCFAR_HWA (MmwDemo_DataPathObj * obj)
Description
Configures HWA for CFAR processing.
Parameters
[in] obj Pointer to data path object
Return values
NONE
Definition at line 1459 of file data_path.c.
References ADDR_TRANSLATE_CPU_TO_HWA, MmwDemo_DataPathObj_t::cliCfg, MmwDemo_DataPathObj_t::hwaHandle, HWAutil_configCFAR(), HWAUTIL_NUM_PARAM_SETS_1D, HWAUTIL_NUM_PARAM_SETS_2D, MMW_HWA_CFAR_INP, MMW_HWA_CFAR_OUT, MMW_HWA_DMA_DEST_CHANNEL_CFAR, MMW_HWA_DMA_TRIGGER_SOURCE_CFAR, MMW_HWA_MAX_CFAR_DET_OBJ_LIST_SIZE, MmwDemo_debugAssert, MmwDemo_DataPathObj_t::numDopplerBins, and MmwDemo_DataPathObj_t::numRangeBins.
Referenced by MmwDemo_processCfar().
void MmwDemo_configDetectedObj2DFFT_HWA (MmwDemo_DataPathObj * obj, uint32_t * dataInPtr, uint32_t * dataOutPtr)
Description
Configures HWA for angle (azimuth) estimation on top of detected objects.
Parameters
[in] obj Pointer to data path object
[in] dataInPtr HWA memory offset for input data of single range bin 2DFFT
[in] dataOutPtr HWA memory offset for out data of single range bin 2DFFT
Return values
NONE
Definition at line 1594 of file data_path.c.
References ADDR_TRANSLATE_CPU_TO_HWA, MmwDemo_DataPathObj_t::hwaHandle, HWAutil_configDopplerFFTSingleRangeBin(), HWAUTIL_NUM_PARAM_SETS_1D, HWAUTIL_NUM_PARAM_SETS_2D, HWAUTIL_NUM_PARAM_SETS_ANGLE, HWAUTIL_NUM_PARAM_SETS_CFAR, MMW_HWA_DMA_TRIGGER_SINGLEBIN_2DFFT, MMW_HWA_WINDOWRAM_1D_OFFSET, MmwDemo_DataPathObj_t::numAdcSamples, MmwDemo_DataPathObj_t::numDopplerBins, and MmwDemo_DataPathObj_t::numVirtualAntennas.
Referenced by MmwDemo_dataPathWaitCFAR(), and MmwDemo_processAngle().
void MmwDemo_dataPathCfgBuffers (MmwDemo_DataPathObj * obj, MmwDemoMemPool_t * pool)
Description
Allocate buffers needed for data path.
Definition at line 926 of file data_path.c.
References MmwDemo_DataPathObj_t::azimuthStaticHeatMap, MmwDemo_DataPathObj_t::cfarDetectionOut, MmwDemo_DataPathObj_t::cliCfg, MmwDemo_DataPathObj_t::dcRangeSigMean, MMW_MAX_OBJ_OUT, MmwDemo_debugAssert, MMWDEMO_MEMORY_ALLOC_DOUBLE_WORD_ALIGN, MmwDemo_memPoolAlloc(), MmwDemo_memPoolReset(), MmwDemo_DataPathObj_t::numDopplerBins, MmwDemo_DataPathObj_t::numRangeBins, MmwDemo_DataPathObj_t::numVirtualAntAzim, MmwDemo_DataPathObj_t::numVirtualAntennas, MmwDemo_DataPathObj_t::radarCube, MmwDemo_DataPathObj_t::rangeDopplerLogMagMatrix, SOC_MAX_NUM_RX_ANTENNAS, and SOC_MAX_NUM_TX_ANTENNAS.
Referenced by MmwDemo_dataPathConfig().
void MmwDemo_dataPathConfigCommon (MmwDemo_DataPathObj * obj)
Description
Common configuration of data path processing, required to be done only once. Configures all of EDMA and window RAM of HWA.
Parameters
[in] obj Pointer to data path obj.
Return values
none.
Definition at line 491 of file data_path.c.
References MmwDemo_DataPathObj_t::HWA_done_semHandle, MmwDemo_DataPathObj_t::hwaHandle, MMW_WIN_BLACKMAN, MMW_WIN_HANNING, MmwDemo_config1D_EDMA(), MmwDemo_config2D_EDMA(), MmwDemo_configCFAR_EDMA(), MmwDemo_dataPathHwaDoneIsrCallback(), MmwDemo_debugAssert, MmwDemo_genWindow(), MmwDemo_DataPathObj_t::numAdcSamples, MmwDemo_DataPathObj_t::numDopplerBins, and PI_.
Referenced by MmwDemo_dataPathConfig().
void MmwDemo_dataPathDeleteSemaphore (MmwDemo_DataPathObj * obj)
Description
Delete semaphores.
Definition at line 2323 of file data_path.c.
References MmwDemo_DataPathObj_t::EDMA_1Ddone_semHandle, MmwDemo_DataPathObj_t::EDMA_2Ddone_semHandle, MmwDemo_DataPathObj_t::EDMA_CFARdone_semHandle, and MmwDemo_DataPathObj_t::HWA_done_semHandle.
void MmwDemo_dataPathHwaDoneIsrCallback (void * arg)
Description
HWA processing completion call back function as per HWA API. Depending on the programmed transfer completion codes, posts HWA done semaphore.
Definition at line 193 of file data_path.c.
Referenced by MmwDemo_dataPathConfigCommon().
void MmwDemo_dataPathObjInit (MmwDemo_DataPathObj * obj, MmwDemo_CliCfg_t * cliCfg, MmwDemo_CliCommonCfg_t * cliCommonCfg)
Description
Initializes data path object with supplied cli config pointer. The cli config points to permanent storage outside of data path object that data path object can refer to anytime during the lifetime of data path object. Data path default values that are not required to come through CLI commands are also set in this function.
Definition at line 908 of file data_path.c.
References MmwDemo_DataPathObj_t::cliCfg, MmwDemo_DataPathObj_t::cliCommonCfg, DATA_PATH_CHAIN_COMBINED_LOGMAG, and MmwDemo_DataPathObj_t::datapathChainSel.
Referenced by MmwDemo_dataPathInit().
void MmwDemo_dataPathTrigger1D (MmwDemo_DataPathObj * obj)
Description
Trigger HWA for 1D processing.
Parameters
[in] obj Pointer to data path obj.
Return values
none.
Definition at line 1382 of file data_path.c.
References MmwDemo_DataPathObj_t::hwaHandle, MMW_HWA_DMA_TRIGGER_SOURCE_1D_PING, MMW_HWA_DMA_TRIGGER_SOURCE_1D_PONG, and MmwDemo_debugAssert.
Referenced by MmwDemo_dataPathConfig(), and MmwDemo_dataPathTask().
void MmwDemo_dataPathTrigger2D (MmwDemo_DataPathObj * obj)
Description
Trigger 2D processing.
Parameters
[in] obj Pointer to data path obj.
Return values
none.
Definition at line 847 of file data_path.c.
References MmwDemo_DataPathObj_t::edmaHandle, MmwDemo_DataPathObj_t::hwaHandle, MMW_EDMA_2D_PING_CHAIN_CH_ID2, MMW_EDMA_2D_PONG_CHAIN_CH_ID2, and MmwDemo_debugAssert.
Referenced by MmwDemo_process2D().
void MmwDemo_dataPathTrigger2DSingleBin (MmwDemo_DataPathObj * obj)
Description
Trigger Single range bin 2D FFT processing.
Parameters
[in] obj Pointer to data path object
Return values
NONE
Definition at line 1279 of file data_path.c.
References MmwDemo_DataPathObj_t::edmaHandle, MmwDemo_DataPathObj_t::hwaHandle, MMW_EDMA_2DFFT_SINGLERBIN_CH_ID, and MmwDemo_debugAssert.
Referenced by MmwDemo_processAngle().
void MmwDemo_dataPathTriggerAngleEstimation (MmwDemo_DataPathObj * obj)
Description
Trigger Angle estimation processing.
Parameters
[in] obj Pointer to data path object
Return values
NONE
Definition at line 1771 of file data_path.c.
References MmwDemo_DataPathObj_t::hwaHandle, and MmwDemo_debugAssert.
Referenced by MmwDemo_processAngle().
void MmwDemo_dataPathTriggerCFAR (MmwDemo_DataPathObj * obj)
Description
Trigger CFAR processing.
Parameters
[in] obj Pointer to data path object
Return values
NONE
Definition at line 1532 of file data_path.c.
References MmwDemo_DataPathObj_t::edmaHandle, MmwDemo_DataPathObj_t::hwaHandle, MMW_EDMA_CFAR_INP_CH_ID, and MmwDemo_debugAssert.
Referenced by MmwDemo_processCfar().
void MmwDemo_dataPathWait1D (MmwDemo_DataPathObj * obj)
Description
Waits for 1D processing to finish. This is a blocking function.
Parameters
[in] obj Pointer to data path object
Return values
NONE
Definition at line 1422 of file data_path.c.
References MmwDemo_DataPathObj_t::EDMA_1Ddone_semHandle, MmwDemo_DataPathObj_t::HWA_done_semHandle, and MmwDemo_debugAssert.
Referenced by MmwDemo_dataPathTask().
void MmwDemo_dataPathWait2D (MmwDemo_DataPathObj * obj)
Description
Waits for 2D processing to finish. This is a blocking function.
Parameters
[in] obj Pointer to data path object
Return values
NONE
Definition at line 874 of file data_path.c.
References MmwDemo_DataPathObj_t::EDMA_2Ddone_semHandle, MmwDemo_DataPathObj_t::HWA_done_semHandle, and MmwDemo_debugAssert.
Referenced by MmwDemo_process2D().
void MmwDemo_dataPathWait2DFFTDetObj (MmwDemo_DataPathObj * obj)
Description
Wait for angle estimation to complete. This is a blocking function.
Parameters
[in] obj Pointer to data path object
Return values
NONE
Definition at line 1748 of file data_path.c.
References MmwDemo_DataPathObj_t::HWA_done_semHandle.
Referenced by MmwDemo_processAngle().
void MmwDemo_dataPathWaitAngleEstimation (MmwDemo_DataPathObj * obj)
Description
Wait for angle estimation to complete. This is a blocking function.
Parameters
[in] obj Pointer to data path object
Return values
NONE
Definition at line 1795 of file data_path.c.
References MmwDemo_DataPathObj_t::HWA_done_semHandle, and MmwDemo_debugAssert.
Referenced by MmwDemo_processAngle().
void MmwDemo_dataPathWaitCFAR (MmwDemo_DataPathObj * obj)
Description
Waits for CFAR processing to finish. This is a blocking function.
Parameters
[in] obj Pointer to data path object
Return values
NONE
Definition at line 1558 of file data_path.c.
References MmwDemo_DataPathObj_t::EDMA_CFARdone_semHandle, MmwDemo_DataPathObj_t::HWA_done_semHandle, MmwDemo_configDetectedObj2DFFT_HWA(), and MmwDemo_debugAssert.
Referenced by MmwDemo_processCfar().
void MmwDemo_dcRangeSignatureCompensation (MmwDemo_DataPathObj * obj)
Description
Compensation of DC range antenna signature
Return values
Not Applicable.
Definition at line 1817 of file data_path.c.
References MmwDemo_DataPathObj_t::cliCfg, MmwDemo_DataPathObj_t::dcRangeSigCalibCntr, MmwDemo_DataPathObj_t::dcRangeSigMean, cmplx16ImRe_t_::imag, MmwDemo_DataPathObj_t::log2NumAvgChirps, MmwDemo_DataPathObj_t::numDopplerBins, MmwDemo_DataPathObj_t::numRangeBins, MmwDemo_DataPathObj_t::numVirtualAntennas, MmwDemo_DataPathObj_t::radarCube, and cmplx16ImRe_t_::real.
Referenced by MmwDemo_dataPathTask().
void MmwDemo_EDMA_errorCallbackFxn (EDMA_Handle handle, EDMA_errorInfo_t * errorInfo)
Description
Call back function for EDMA CC (Channel controller) error as per EDMA API. Declare fatal error if happens, the output errorInfo can be examined if code gets trapped here.
Definition at line 664 of file data_path.c.
References MmwDemo_debugAssert.
Referenced by MmwDemo_edmaOpen().
void MmwDemo_EDMA_transferCompletionCallbackFxn (uintptr_t arg, uint8_t transferCompletionCode)
Description
EDMA transfer completion call back function as per EDMA API. Depending on the programmed transfer completion codes, posts the corresponding done/completion semaphore. Per current design, a single semaphore could have been used as the 1D, 2D and CFAR stages are sequential, this code gives some flexibility if some design change in future.
Definition at line 161 of file data_path.c.
References MmwDemo_DataPathObj_t::EDMA_1Ddone_semHandle, MmwDemo_DataPathObj_t::EDMA_2Ddone_semHandle, MmwDemo_DataPathObj_t::EDMA_CFARdone_semHandle, MmwDemo_debugAssert, MMWDEMO_EDMA_TRANSFER_COMPLETION_CODE_1D_DONE, MMWDEMO_EDMA_TRANSFER_COMPLETION_CODE_2D_DONE, and MMWDEMO_EDMA_TRANSFER_COMPLETION_CODE_CFAR_DONE.
Referenced by MmwDemo_config1D_EDMA(), MmwDemo_config2D_EDMA(), and MmwDemo_configCFAR_EDMA().
void MmwDemo_EDMA_transferControllerErrorCallbackFxn (EDMA_Handle handle, EDMA_transferControllerErrorInfo_t * errorInfo)
Description
Call back function for EDMA transfer controller error as per EDMA API. Declare fatal error if happens, the output errorInfo can be examined if code gets trapped here.
Definition at line 676 of file data_path.c.
References MmwDemo_debugAssert.
Referenced by MmwDemo_edmaOpen().
void MmwDemo_edmaClose (MmwDemo_DataPathObj * obj)
Description
Close EDMA.
Definition at line 764 of file data_path.c.
References MmwDemo_DataPathObj_t::edmaHandle.
void MmwDemo_edmaInit (MmwDemo_DataPathObj * obj)
Description
Init EDMA.
Definition at line 617 of file data_path.c.
References MmwDemo_DataPathObj_t::EDMA_1Ddone_semHandle, MmwDemo_DataPathObj_t::EDMA_2Ddone_semHandle, MmwDemo_DataPathObj_t::EDMA_CFARdone_semHandle, MmwDemo_DataPathObj_t::EDMA_errorInfo, MmwDemo_DataPathObj_t::EDMA_transferControllerErrorInfo, MmwDemo_DataPathObj_t::HWA_done_semHandle, and MmwDemo_debugAssert.
Referenced by MmwDemo_dataPathInit().
void MmwDemo_edmaOpen (MmwDemo_DataPathObj * obj)
Description
Open EDMA.
Definition at line 727 of file data_path.c.
References MmwDemo_DataPathObj_t::edmaHandle, MmwDemo_debugAssert, MmwDemo_EDMA_errorCallbackFxn(), and MmwDemo_EDMA_transferControllerErrorCallbackFxn().
Referenced by MmwDemo_dataPathOpen().
static MmwDemo_genWindow (uint32_t * win, uint32_t winIndx, float phi, uint32_t winType) inline static
Description
Function to generate a single FFT window sample.
Parameters
[out] win Pointer to output calculated window sample.
[in] winIndx Index of window to generate sample at.
[in] phi Pre-calculated constant by caller as (2*pi/(window length - 1)).
[in] winType Type of window, one of MMW_WIN_BLACKMAN, MMW_WIN_HANNING, or MMW_WIN_RECT.
Return values
none.
Definition at line 120 of file data_path.c.
References MMW_WIN_BLACKMAN, MMW_WIN_HANNING, MMW_WIN_RECT, and ONE_Q17.
Referenced by MmwDemo_dataPathConfigCommon().
void MmwDemo_hwaClose (MmwDemo_DataPathObj * obj)
Description
Close HWA instance.
Definition at line 707 of file data_path.c.
References MmwDemo_DataPathObj_t::hwaHandle, and MmwDemo_debugAssert.
void MmwDemo_hwaInit (MmwDemo_DataPathObj * obj)
Description
Init HWA.
Definition at line 606 of file data_path.c.
Referenced by MmwDemo_dataPathInit().
void MmwDemo_hwaOpen (MmwDemo_DataPathObj * obj, SOC_Handle socHandle)
Description
Open HWA instance.
Definition at line 687 of file data_path.c.
References MmwDemo_DataPathObj_t::hwaHandle, and MmwDemo_debugAssert.
Referenced by MmwDemo_dataPathOpen().
uint8_t* MmwDemo_memPoolAlloc (MmwDemoMemPool_t * pool, uint32_t size)
Description
Utility function for allocating from a static memory pool.
Precondition
It is assumed that no allocation from l3 will need better than 32-bit alignment (structures with 64-bit prohibited) and so for simplicity, size is assumed to be multiple of 4 bytes
Parameters
[in] pool Handle to pool structure.
[in] size Size in bytes to be allocated.
Return values
pointer to beginning of allocated block. NULL indicates could notice allocate.
Definition at line 1005 of file data_path.c.
References MmwDemoMemPool_t::base, MmwDemoMemPool_t::indx, and MmwDemoMemPool_t::size.
Referenced by MmwDemo_dataPathCfgBuffers().
void MmwDemo_memPoolReset (MmwDemoMemPool_t * pool)
Description
Utility function for reseting memory pool.
Parameters
[in] pool Handle to pool structure.
Return values
none.
Definition at line 984 of file data_path.c.
References MmwDemoMemPool_t::indx.
Referenced by MmwDemo_dataPathCfgBuffers().
uint32_t MmwDemo_pow2roundup (uint32_t x)
Description
Power of 2 round up function.
Definition at line 2308 of file data_path.c.
Referenced by MmwDemo_parseProfileAndChirpConfig().
void MmwDemo_process2D (MmwDemo_DataPathObj * obj)
Description
2D process chain.
Definition at line 2003 of file data_path.c.
References MmwDemo_config2D_HWA(), MmwDemo_dataPathTrigger2D(), and MmwDemo_dataPathWait2D().
Referenced by MmwDemo_dataPathTask().
void MmwDemo_processAngle (MmwDemo_DataPathObj * obj)
Description
Angle estimation process chain.
Definition at line 2031 of file data_path.c.
References angleEstimationAzimElev(), MmwDemo_DataPathObj_t::azimuthStaticHeatMap, MmwDemo_DataPathObj_t::cfarDetectionOut, MmwDemo_DataPathObj_t::cliCfg, DATA_PATH_CHAIN_SEPARATE_LOGMAG, MmwDemo_DataPathObj_t::datapathChainSel, DOPPLER_IDX_TO_SIGNED, MEM_BARRIER(), MMW_HWA_2DFFT_SINGLERBIN_INP, MMW_HWA_2DFFT_SINGLERBIN_OUT, MMW_HWA_ANGLE_AZIM_ABS_OUT, MMW_HWA_ANGLE_AZIM_CPLX_OUT, MMW_HWA_ANGLE_AZIM_INP, MMW_HWA_ANGLE_ELEV_CPLX_OUT, MMW_HWA_ANGLE_ELEV_INP, MMW_HWA_CFAR_OUT, MmwDemo_azimHeapMapDopplerCompensation(), MmwDemo_config2DSingleBin_EDMA(), MmwDemo_configAngleEstimation_HWA(), MmwDemo_configDetectedObj2DFFT_HWA(), MmwDemo_dataPathTrigger2DSingleBin(), MmwDemo_dataPathTriggerAngleEstimation(), MmwDemo_dataPathWait2DFFTDetObj(), MmwDemo_dataPathWaitAngleEstimation(), MmwDemo_dopplerCompensation(), MmwDemo_peakGrouping(), MmwDemo_rxChanPhaseBiasCompensation(), MmwDemo_DataPathObj_t::numChirpsPerFrame, MmwDemo_DataPathObj_t::numDopplerBins, MmwDemo_DataPathObj_t::numHwaCfarDetections, MmwDemo_DataPathObj_t::numObjOut, MmwDemo_DataPathObj_t::numRangeBins, MmwDemo_DataPathObj_t::numRxAntennas, MmwDemo_DataPathObj_t::numTxAntennas, MmwDemo_DataPathObj_t::numVirtualAntAzim, MmwDemo_DataPathObj_t::numVirtualAntElev, MmwDemo_DataPathObj_t::numVirtualAntennas, MmwDemo_DataPathObj_t::objOut, MmwDemo_DataPathObj_t::radarCube, MmwDemo_DataPathObj_t::rangeDopplerLogMagMatrix, MmwDemo_DataPathObj_t::rangeResolution, and MmwDemo_DataPathObj_t::xyzOutputQFormat.
Referenced by MmwDemo_dataPathTask().
void MmwDemo_processCfar (MmwDemo_DataPathObj * obj, uint16_t * numDetectedObjects)
Description
CFAR process chain.
Definition at line 2015 of file data_path.c.
References MmwDemo_DataPathObj_t::hwaHandle, MmwDemo_configCFAR_HWA(), MmwDemo_dataPathTriggerCFAR(), MmwDemo_dataPathWaitCFAR(), and MmwDemo_DataPathObj_t::numHwaCfarDetections.
Referenced by MmwDemo_dataPathTask().
void MmwDemo_rxChanPhaseBiasCompensation (MmwDemo_DataPathObj * obj, uint32_t numObj, cmplx16ImRe_t * azimuthSymbols, cmplx16ImRe_t * elevationSymbols)
Function Name : MmwDemo_rxChanPhaseBiasCompensation.
Description : Compensation of rx channel phase bias
Parameters
[in] obj Data path object
[in] numObj Number of detected points
[in,out] azimuthSymbols Symbols of Azimuth antennas
[in,out] elevationSymbols Symbols of Elevation antennas
Returns
void
Definition at line 1931 of file data_path.c.
References MmwDemo_DataPathObj_t::compRxChanCfg, cmplx16ImRe_t_::imag, MMWDEMO_SATURATE_HIGH, MMWDEMO_SATURATE_LOW, MmwDemo_DataPathObj_t::numVirtualAntAzim, MmwDemo_DataPathObj_t::numVirtualAntElev, and cmplx16ImRe_t_::real.
Referenced by MmwDemo_processAngle().
Variable Documentation
mmwHwaBuf_t gMmwHwaMemBuf[MMW_HWA_NUM_MEM_BUFS]
HWA memory buffer to produce the M0,M1,M2,M3 partition addresses and link to the HWA section in the linker command file.
Definition at line 105 of file data_path.c.
Copyright 2018, Texas Instruments Incorporated