xwr14xx/mmw/main.c File Reference
main.c File Reference
This is the main file which implements the millimeter wave Demo.
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <xdc/std.h>
#include <xdc/cfg/global.h>
#include <xdc/runtime/IHeap.h>
#include <xdc/runtime/System.h>
#include <xdc/runtime/Error.h>
#include <xdc/runtime/Memory.h>
#include <ti/sysbios/BIOS.h>
#include <ti/sysbios/knl/Task.h>
#include <ti/sysbios/knl/Event.h>
#include <ti/sysbios/knl/Semaphore.h>
#include <ti/sysbios/knl/Clock.h>
#include <ti/sysbios/heaps/HeapBuf.h>
#include <ti/sysbios/heaps/HeapMem.h>
#include <ti/sysbios/family/arm/v7a/Pmu.h>
#include <ti/sysbios/family/arm/v7r/vim/Hwi.h>
#include <ti/sysbios/utils/Load.h>
#include <ti/common/sys_common.h>
#include <ti/common/mmwave_sdk_version.h>
#include <ti/drivers/soc/soc.h>
#include <ti/drivers/esm/esm.h>
#include <ti/drivers/crc/crc.h>
#include <ti/drivers/gpio/gpio.h>
#include <ti/drivers/mailbox/mailbox.h>
#include <ti/control/mmwave/mmwave.h>
#include <ti/drivers/osal/DebugP.h>
#include <ti/drivers/uart/UART.h>
#include <ti/utils/cli/cli.h>
#include <ti/demo/io_interface/mmw_output.h>
#include "config_edma_util.h"
#include "config_hwa_util.h"
#include "post_processing.h"
#include "mmw.h"
#include "data_path.h"
#include "mmw_lvds_stream.h"
#include <ti/demo/io_interface/mmw_config.h>
#include <ti/demo/utils/rx_ch_bias_measure.h>
#include <ti/demo/utils/mmwDemo_monitor.h>
Macros
#define MMW_DEMO_CQ_SIGIMG_ADDR_OFFSET 0U
#define MMW_DEMO_CQ_RXSAT_ADDR_OFFSET 0x400U
Functions
uint32_t log2Approx (uint32_t x)
void MmwDemo_CLIInit (void)
void MmwDemo_mmWaveCtrlTask (UArg arg0, UArg arg1)
void MmwDemo_dataPathInit (MmwDemo_DataPathObj *obj)
void MmwDemo_dataPathConfig (void)
void MmwDemo_dataPathOpen (MmwDemo_DataPathObj *obj)
void MmwDemo_dataPathStop (MmwDemo_DataPathObj *obj)
void MmwDemo_getAngleBinsAtPeak (uint32_t numObj, MmwDemo_detectedObj *objOut, uint16_t *pAngleBins)
void MmwDemo_transmitProcessedOutput (UART_Handle uartHandle, MmwDemo_DataPathObj *obj)
Transmits detection data over UART.
void MmwDemo_initTask (UArg arg0, UArg arg1)
void MmwDemo_dataPathTask (UArg arg0, UArg arg1)
int32_t MmwDemo_eventCallbackFxn (uint16_t msgId, uint16_t sbId, uint16_t sbLen, uint8_t *payload)
void MmwDemo_sleep (void)
void _MmwDemo_debugAssert (int32_t expression, const char *file, int32_t line)
void MmwDemo_ADCBufOpen (MmwDemo_DataPathObj *obj)
int32_t MmwDemo_ADCBufConfig (MmwDemo_DataPathObj *dataPathObj)
void MmwDemo_EDMA_CQTransferCompletionCallbackFxn (uintptr_t arg, uint8_t transferCompletionCode)
int32_t MmwDemo_dataPathConfigCQEdma (MmwDemo_DataPathObj *obj)
int32_t MmwDemo_dataPathConfigCQ (MmwDemo_DataPathObj *ptrDataPathObj)
bool MmwDemo_parseProfileAndChirpConfig (MmwDemo_DataPathObj *dataPathObj)
void MmwDemo_measurementResultOutput (MmwDemo_DataPathObj *obj)
int32_t MmwDemo_dataPathStart (void)
void MmwDemo_configLVDSHwData (MmwDemo_DataPathObj *dataPathObj)
void MmwDemo_transferLVDSUserData (MmwDemo_DataPathObj *dataPathObj)
static void MmwDemo_frameStartIntHandler (uintptr_t arg)
int main (void)
Variables
mmwHwaBuf_t gMmwHwaMemBuf [MMW_HWA_NUM_MEM_BUFS]
uint8_t gMmwL3 [SOC_XWR14XX_MSS_L3RAM_SIZE]
rlRfRxSaturationCqData_t gCQRxSatMonMemory
rlRfSigImgPowerCqData_t gCQRxSigImgMemory
MmwDemoMemPool_t gMmwL3heap
MmwDemo_MCB gMmwMCB
Global Variable for tracking information required by the mmw Demo.
Detailed Description
This is the main file which implements the millimeter wave Demo.
NOTE: (C) Copyright 2016 Texas Instruments, Inc.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Texas Instruments Incorporated nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file main.c.
Macro Definition Documentation
#define MMW_DEMO_CQ_RXSAT_ADDR_OFFSET 0x400U
Definition at line 702 of file main.c.
Referenced by MmwDemo_dataPathConfigCQ().
#define MMW_DEMO_CQ_SIGIMG_ADDR_OFFSET 0U
Definition at line 701 of file main.c.
Referenced by MmwDemo_dataPathConfigCQ().
Function Documentation
void _MmwDemo_debugAssert (int32_t expression, const char * file, int32_t line)
Description
Send assert information through CLI.
Definition at line 773 of file main.c.
References CLI_write().
uint32_t log2Approx (uint32_t x)
Definition at line 56 of file config_hwa_util.c.
Referenced by MmwDemo_parseProfileAndChirpConfig().
int main (void)
Description
Entry point into the Millimeter Wave Demo
Return values
Not Applicable.
Definition at line 2397 of file main.c.
References MmwDemo_MCB_t::cfg, MmwDemo_debugAssert, MmwDemo_initTask(), and MmwDemo_MCB_t::socHandle.
int32_t MmwDemo_ADCBufConfig (MmwDemo_DataPathObj * dataPathObj)
Description
Configures ADCBuf and returns the number of RxAntennas
Definition at line 814 of file main.c.
References MmwDemo_DataPathObj_t::adcbufHandle, MmwDemo_MCB_t::cfg, MmwDemo_DataPathObj_t::cliCfg, MmwDemo_debugAssert, MmwDemo_DataPathObj_t::numAdcSamples, and SYS_COMMON_NUM_RX_CHANNEL.
Referenced by MmwDemo_dataPathConfig().
void MmwDemo_ADCBufOpen (MmwDemo_DataPathObj * obj)
Description
Get a handle for ADCBuf.
Definition at line 785 of file main.c.
References MmwDemo_DataPathObj_t::adcbufHandle, and MmwDemo_debugAssert.
Referenced by MmwDemo_dataPathOpen().
void MmwDemo_CLIInit (void)
Description
This is the CLI Execution Task
Return values
Not Applicable.
Definition at line 708 of file mmw_cli.c.
References CLI_open(), MmwDemo_MCB_t::commandUartHandle, MmwDemo_MCB_t::ctrlHandle, MmwDemo_CLIADCBufCfg(), MmwDemo_CLIAnalogMonitorCfg(), MmwDemo_CLICalibDcRangeSig(), MmwDemo_CLICfarCfg(), MmwDemo_CLIChirpQualityRxSatMonCfg(), MmwDemo_CLIChirpQualitySigImgMonCfg(), MmwDemo_CLIClutterRemoval(), MmwDemo_CLICompRangeBiasAndRxChanPhaseCfg(), MmwDemo_CLIGuiMonSel(), MmwDemo_CLIMeasureRangeBiasAndRxChanPhaseCfg(), MmwDemo_CLIMultiObjBeamForming(), MmwDemo_CLIPeakGroupingCfg(), MmwDemo_CLISensorStart(), MmwDemo_CLISensorStop(), and MmwDemo_debugAssert.
Referenced by MmwDemo_initTask().
void MmwDemo_configLVDSHwData (MmwDemo_DataPathObj * dataPathObj)
Description
Configures LVDS/CBUFF HW session for transmitting ADC data
Parameters
[in] dataPathObj Pointer to datapath object
Return values
Not Applicable.
Definition at line 1693 of file main.c.
References MmwDemo_LVDSStream_MCB::hwSessionHandle, MmwDemo_MCB_t::lvdsStream, MmwDemo_debugAssert, MmwDemo_LVDSStreamDeleteHwSession(), and MmwDemo_LVDSStreamHwConfig().
Referenced by MmwDemo_dataPathConfig().
void MmwDemo_dataPathConfig (void)
Description
The function is used to configure the data path based on the chirp profile. After this function is executed, the data path processing will ready to go when the ADC buffer starts receiving samples corresponding to the chirps.
Return values
Not Applicable.
Definition at line 1731 of file main.c.
References MmwDemo_DataPathObj_t::cliCfg, MmwDemo_DataPathObj_t::cliCommonCfg, MmwDemo_MCB_t::dataPathObj, MmwDemo_ADCBufConfig(), MmwDemo_config1D_HWA(), MmwDemo_configLVDSHwData(), MmwDemo_dataPathCfgBuffers(), MmwDemo_dataPathConfigCommon(), MmwDemo_dataPathConfigCQ(), MmwDemo_dataPathTrigger1D(), MmwDemo_debugAssert, MmwDemo_LVDSStreamDelete(), and MmwDemo_parseProfileAndChirpConfig().
Referenced by MmwDemo_doSensorStart().
int32_t MmwDemo_dataPathConfigCQ (MmwDemo_DataPathObj * ptrDataPathObj)
Description
Function to configure CQ.
Parameters
[in] ptrDataPathObj Pointer to data path object.
Return values
0 if no error, else error (there will be system prints for these).
Definition at line 1059 of file main.c.
References MmwDemo_DataPathObj_t::adcbufHandle, MmwDemo_dataPathCQ_t::anaMonCfg, MmwDemo_DataPathObj_t::cliCommonCfg, MmwDemo_DataPathObj_t::datapathCQ, gCQRxSatMonMemory, gCQRxSigImgMemory, MMW_DEMO_CQ_RXSAT_ADDR_OFFSET, MMW_DEMO_CQ_SIGIMG_ADDR_OFFSET, MmwDemo_dataPathConfigCQEdma(), MmwDemo_debugAssert, MmwDemo_dataPathCQ_t::rxSatData, MmwDemo_dataPathCQ_t::rxSatMonCfg, MmwDemo_dataPathCQ_t::satMonAddr, MmwDemo_dataPathCQ_t::satMonTotalSize, MmwDemo_dataPathCQ_t::sigImgData, MmwDemo_dataPathCQ_t::sigImgMonAddr, MmwDemo_dataPathCQ_t::sigImgMonCfg, MmwDemo_dataPathCQ_t::sigImgMonTotalSize, and MmwDemo_DataPathObj_t::validProfileIdx.
Referenced by MmwDemo_dataPathConfig().
int32_t MmwDemo_dataPathConfigCQEdma (MmwDemo_DataPathObj * obj)
Description
Configures all CQ EDMA channels and param sets used in data path processing
Parameters
[in] obj Pointer to data path object
Return values
-1 if error, 0 for no error
Definition at line 958 of file main.c.
References MmwDemo_dataPathCQ_t::anaMonCfg, MmwDemo_DataPathObj_t::datapathCQ, EDMA_TPCC0_REQ_DFE_CHIRP_AVAIL, MmwDemo_DataPathObj_t::edmaHandle, EDMAutil_configSyncAwithChaining(), MMW_EDMA_CH_RX_SATURATION_MON, MmwDemo_EDMA_CQTransferCompletionCallbackFxn(), MmwDemo_dataPathCQ_t::rxSatData, MmwDemo_dataPathCQ_t::satMonAddr, MmwDemo_dataPathCQ_t::satMonTotalSize, MmwDemo_dataPathCQ_t::sigImgData, MmwDemo_dataPathCQ_t::sigImgMonAddr, and MmwDemo_dataPathCQ_t::sigImgMonTotalSize.
Referenced by MmwDemo_dataPathConfigCQ().
void MmwDemo_dataPathInit (MmwDemo_DataPathObj * obj)
Description
This function is called at the init time from MmwDemo_initTask. It initializes drivers: ADCBUF, HWA, EDMA, and semaphores used by MmwDemo_dataPathTask
Return values
Not Applicable.
Definition at line 1798 of file main.c.
References MmwDemo_MCB_t::cliCfg, MmwDemo_MCB_t::cliCommonCfg, MmwDemo_dataPathObjInit(), MmwDemo_edmaInit(), and MmwDemo_hwaInit().
Referenced by MmwDemo_initTask().
void MmwDemo_dataPathOpen (MmwDemo_DataPathObj * obj)
Definition at line 1812 of file main.c.
References MmwDemo_ADCBufOpen(), MmwDemo_edmaOpen(), MmwDemo_hwaOpen(), and MmwDemo_MCB_t::socHandle.
Referenced by MmwDemo_initTask().
int32_t MmwDemo_dataPathStart (void)
Description
The function is used to trigger the Front end to start generating chirps.
Return values
Not Applicable.
Definition at line 1645 of file main.c.
References MmwDemo_MCB_t::ctrlHandle, MmwDemo_MCB_t::dataPathObj, MmwDemo_DataPathObj_t::datapathStopped, MmwDemo_DataPathObj_t::frameStartIntCounter, MmwDemo_LVDSStream_MCB::hwFrameDoneCount, MmwDemo_DataPathObj_t::interFrameProcToken, MmwDemo_MCB_t::lvdsStream, MmwDemo_debugAssert, and MmwDemo_LVDSStream_MCB::swFrameDoneCount.
Referenced by MmwDemo_doSensorFrameStart(), and MmwDemo_doSensorStart().
void MmwDemo_dataPathStop (MmwDemo_DataPathObj * obj)
Description
The function is used to Stop data path.
Return values
Not Applicable.
Definition at line 1830 of file main.c.
References MmwDemo_DataPathObj_t::datapathStopped, MmwDemo_DataPathObj_t::interFrameProcToken, and MmwDemo_notifyDathPathStop().
Referenced by MmwDemo_doSensorStop().
void MmwDemo_dataPathTask (UArg arg0, UArg arg1)
Description
The task is used for data path processing and to transmit the detected objects through the UART output port.
Return values
Not Applicable.
Definition at line 2016 of file main.c.
References MmwDemo_timingInfo::activeFrameCPULoad, calcNoiseFloor(), MmwDemo_DataPathObj_t::cliCfg, MmwDemo_DataPathObj_t::cliCommonCfg, MmwDemo_MCB_t::dataPathObj, MmwDemo_DataPathObj_t::datapathStopped, MmwDemo_DataPathObj_t::dcRangeForcedDisableCntr, MmwDemo_DataPathObj_t::frameStart_semHandle, cmplx16ImRe_t_::imag, MmwDemo_timingInfo::interFrameCPULoad, MmwDemo_timingInfo::interFrameProcCycles, MmwDemo_timingInfo::interFrameProcessingEndTime, MmwDemo_DataPathObj_t::interFrameProcToken, MmwDemo_MCB_t::loggingUartHandle, MmwDemo_config1D_HWA(), MmwDemo_dataPathTrigger1D(), MmwDemo_dataPathWait1D(), MmwDemo_dcRangeSignatureCompensation(), MmwDemo_measurementResultOutput(), MmwDemo_notifyDathPathStop(), MmwDemo_process2D(), MmwDemo_processAngle(), MmwDemo_processCfar(), MmwDemo_transferLVDSUserData(), MmwDemo_transmitProcessedOutput(), MmwDemo_DataPathObj_t::noiseEnergy, MmwDemo_DataPathObj_t::numDopplerBins, MmwDemo_DataPathObj_t::numHwaCfarDetections, MmwDemo_DataPathObj_t::numRangeBins, MmwDemo_DataPathObj_t::numRxAntennas, MmwDemo_DataPathObj_t::numTxAntennas, MmwDemo_DataPathObj_t::numVirtualAntennas, MmwDemo_DataPathObj_t::radarCube, MmwDemo_DataPathObj_t::rangeDopplerLogMagMatrix, MmwDemo_DataPathObj_t::rangeResolution, cmplx16ImRe_t_::real, cmplx32ImRe_t_::real, SYS_COMMON_NUM_TX_ANTENNAS, MmwDemo_DataPathObj_t::timingInfo, and MmwDemo_timingInfo::transmitOutputCycles.
Referenced by MmwDemo_initTask().
void MmwDemo_EDMA_CQTransferCompletionCallbackFxn (uintptr_t arg, uint8_t transferCompletionCode)
Description
EDMA transfer completion callback for CQ transfers
Parameters
[in] arg Transfer completion callback argument
[in] transferCompletionCode Transfer completion code
Return values
None
Definition at line 920 of file main.c.
References MmwDemo_dataPathCQ_t::anaMonCfg, MmwDemo_DataPathObj_t::datapathCQ, MMW_EDMA_RXSAT_TRANSFER_COMPLETION, MmwDemo_debugAssert, MmwDemo_dataPathCQ_t::rxSatData, MmwDemo_dataPathCQ_t::rxSatEdmaCnt, MmwDemo_dataPathCQ_t::rxSatMonCfg, MmwDemo_dataPathCQ_t::sigImgBandEdmaCnt, MmwDemo_dataPathCQ_t::sigImgData, and MmwDemo_dataPathCQ_t::sigImgMonCfg.
Referenced by MmwDemo_dataPathConfigCQEdma().
int32_t MmwDemo_eventCallbackFxn (uint16_t msgId, uint16_t sbId, uint16_t sbLen, uint8_t * payload)
Description
Registered event function to mmwave which is invoked when an event from the BSS is received.
Parameters
[in] msgId Message Identifier
[in] sbId Subblock identifier
[in] sbLen Length of the subblock
[in] payload Pointer to the payload buffer
Return values
Always return 0
Definition at line 1881 of file main.c.
References MmwDemo_Stats_t::calibrationReports, CLI_write(), MmwDemo_Stats_t::failedTimingReports, MmwDemo_Stats_t::frameTriggerReady, MmwDemo_debugAssert, MmwDemo_notifyBssSensorStop(), MmwDemo_Stats_t::sensorStopped, and MmwDemo_MCB_t::stats.
Referenced by MmwDemo_initTask().
static void MmwDemo_frameStartIntHandler (uintptr_t arg) static
Description
Frame start interrupt handler
Return values
Not Applicable.
Definition at line 2165 of file main.c.
References MmwDemo_MCB_t::dataPathObj, MmwDemo_DataPathObj_t::frameStart_semHandle, MmwDemo_DataPathObj_t::frameStartIntCounter, MmwDemo_timingInfo::interFrameProcessingEndMargin, MmwDemo_timingInfo::interFrameProcessingEndTime, MmwDemo_DataPathObj_t::interFrameProcToken, MmwDemo_debugAssert, and MmwDemo_DataPathObj_t::timingInfo.
Referenced by MmwDemo_initTask().
void MmwDemo_getAngleBinsAtPeak (uint32_t numObj, MmwDemo_detectedObj * objOut, uint16_t * pAngleBins)
void MmwDemo_initTask (UArg arg0, UArg arg1)
Description
System Initialization Task which initializes the various components in the system.
Return values
Not Applicable.
Definition at line 2194 of file main.c.
References MmwDemo_MCB_t::cfg, MmwDemo_MCB_t::commandUartHandle, MmwDemo_MCB_t::ctrlHandle, MmwDemo_MCB_t::dataPathObj, MmwDemo_DataPathObj_t::frameStart_semHandle, MmwDemo_MCB_t::loggingUartHandle, MmwDemo_CLIInit(), MmwDemo_dataPathInit(), MmwDemo_dataPathOpen(), MmwDemo_dataPathTask(), MmwDemo_debugAssert, MmwDemo_eventCallbackFxn(), MmwDemo_frameStartIntHandler(), MmwDemo_LVDSStreamInit(), MmwDemo_mmWaveCtrlTask(), MmwDemo_sensorMgmtInit(), SOC_XWR14XX_DSS_FRAME_START_IRQ, and MmwDemo_MCB_t::socHandle.
Referenced by main().
void MmwDemo_measurementResultOutput (MmwDemo_DataPathObj * obj)
Definition at line 1404 of file main.c.
References CLI_write(), MmwDemo_DataPathObj_t::cliCommonCfg, SYS_COMMON_NUM_RX_CHANNEL, and SYS_COMMON_NUM_TX_ANTENNAS.
Referenced by MmwDemo_dataPathTask().
void MmwDemo_mmWaveCtrlTask (UArg arg0, UArg arg1)
Description
The task is used to provide an execution context for the mmWave control task
Return values
Not Applicable.
Definition at line 1848 of file main.c.
References MmwDemo_MCB_t::ctrlHandle, and MmwDemo_debugAssert.
Referenced by MmwDemo_initTask().
bool MmwDemo_parseProfileAndChirpConfig (MmwDemo_DataPathObj * dataPathObj)
Description
parses Profile, Chirp and Frame config and extracts parameters needed for processing chain configuration
Definition at line 1171 of file main.c.
References MmwDemo_MCB_t::cfg, MmwDemo_DataPathObj_t::cliCommonCfg, MmwDemo_DataPathObj_t::compRxChanCfg, DATA_PATH_WITH_ADCBUF, MmwDemo_DataPathObj_t::dataPathMode, MmwDemo_DataPathObj_t::frameStartIntCounter, cmplx16ImRe_t_::imag, MmwDemo_DataPathObj_t::interFrameProcToken, log2Approx(), MMW_NUM_ANGLE_BINS, MMW_NUM_RANGE_BINS_PER_TRANSFER, MmwDemo_debugAssert, MmwDemo_pow2roundup(), MMWDEMO_SPEED_OF_LIGHT_IN_METERS_PER_SEC, MmwDemo_DataPathObj_t::numAdcSamples, MmwDemo_DataPathObj_t::numAngleBins, MmwDemo_DataPathObj_t::numChirpsPerFrame, MmwDemo_DataPathObj_t::numDopplerBins, MmwDemo_DataPathObj_t::numRangeBins, MmwDemo_DataPathObj_t::numRangeBinsPerTransfer, MmwDemo_DataPathObj_t::numRxAntennas, MmwDemo_DataPathObj_t::numTxAntennas, MmwDemo_DataPathObj_t::numVirtualAntAzim, MmwDemo_DataPathObj_t::numVirtualAntElev, MmwDemo_DataPathObj_t::numVirtualAntennas, MmwDemo_DataPathObj_t::rangeResolution, cmplx16ImRe_t_::real, SYS_COMMON_NUM_RX_CHANNEL, SYS_COMMON_NUM_TX_ANTENNAS, MmwDemo_DataPathObj_t::validProfileIdx, and MmwDemo_DataPathObj_t::xyzOutputQFormat.
Referenced by MmwDemo_dataPathConfig().
void MmwDemo_sleep (void)
Description
Function to sleep the R4F using WFI (Wait For Interrupt) instruction. When R4F has no work left to do, the BIOS will be in Idle thread and will call this function. The R4F will wake-up on any interrupt (e.g chirp interrupt).
Return values
Not Applicable.
Definition at line 2383 of file main.c.
void MmwDemo_transferLVDSUserData (MmwDemo_DataPathObj * dataPathObj)
Description
Transmit user data over LVDS interface.
Parameters
[in] dataPathObj Pointer to datapath object
Definition at line 1971 of file main.c.
References MmwDemo_LVDSUserDataHeader::detObjNum, MmwDemo_LVDSUserDataHeader::frameNum, MmwDemo_DataPathObj_t::frameStartIntCounter, MmwDemo_MCB_t::lvdsStream, MmwDemo_debugAssert, MmwDemo_LVDSStreamDeleteSwSession(), MmwDemo_LVDSStreamSwConfig(), MmwDemo_DataPathObj_t::numObjOut, MmwDemo_LVDSUserDataHeader::reserved, MmwDemo_LVDSStream_MCB::swSessionHandle, and MmwDemo_LVDSStream_MCB::userDataHeader.
Referenced by MmwDemo_dataPathTask().
void MmwDemo_transmitProcessedOutput (UART_Handle uartHandle, MmwDemo_DataPathObj * obj)
Transmits detection data over UART.
The following data is transmitted:
Header (size = 32bytes), including "Magic word", (size = 8 bytes) and icluding the number of TLV items TLV Items:
If detectedObjects flag is set, pbjOut structure containing range, Doppler, and X,Y,Z location for detected objects, size = sizeof(objOut_t) * number of detected objects
If logMagRange flag is set, rangeProfile, size = number of range bins * sizeof(uint16_t)
If noiseProfile flag is set, noiseProfile, size = number of range bins * sizeof(uint16_t)
If rangeAzimuthHeatMap flag is set, the zero Doppler column of the range cubed matrix, size = number of Rx Azimuth virtual antennas * number of chirps per frame * sizeof(uint32_t)
If rangeDopplerHeatMap flag is set, the log magnitude range-Doppler matrix, size = number of range bins * number of Doppler bins * sizeof(uint16_t)
If statsInfo flag is set, the stats information
Parameters
[in] uartHandle UART driver handle
[in] obj Pointer data path object MmwDemo_DataPathObj
Definition at line 1442 of file main.c.
References MmwDemo_output_message_stats_t::activeFrameCPULoad, MmwDemo_timingInfo::activeFrameCPULoad, MmwDemo_DataPathObj_t::azimuthStaticHeatMap, MmwDemo_MCB_t::cliCfg, MmwDemo_output_message_header_t::frameNumber, MmwDemo_DataPathObj_t::frameStartIntCounter, MmwDemo_output_message_stats_t::interChirpProcessingMargin, MmwDemo_output_message_stats_t::interFrameCPULoad, MmwDemo_timingInfo::interFrameCPULoad, MmwDemo_timingInfo::interFrameProcCycles, MmwDemo_timingInfo::interFrameProcessingEndMargin, MmwDemo_output_message_stats_t::interFrameProcessingMargin, MmwDemo_output_message_stats_t::interFrameProcessingTime, MmwDemo_output_message_tl_t::length, MmwDemo_output_message_header_t::magicWord, MMWDEMO_OUTPUT_MSG_AZIMUT_STATIC_HEAT_MAP, MMWDEMO_OUTPUT_MSG_DETECTED_POINTS, MMWDEMO_OUTPUT_MSG_MAX, MMWDEMO_OUTPUT_MSG_NOISE_PROFILE, MMWDEMO_OUTPUT_MSG_RANGE_DOPPLER_HEAT_MAP, MMWDEMO_OUTPUT_MSG_RANGE_PROFILE, MMWDEMO_OUTPUT_MSG_SEGMENT_LEN, MMWDEMO_OUTPUT_MSG_STATS, MmwDemo_output_message_header_t::numDetectedObj, MmwDemo_output_message_dataObjDescr_t::numDetetedObj, MmwDemo_DataPathObj_t::numDopplerBins, MmwDemo_DataPathObj_t::numObjOut, MmwDemo_DataPathObj_t::numRangeBins, MmwDemo_output_message_header_t::numTLVs, MmwDemo_DataPathObj_t::numVirtualAntAzim, MmwDemo_DataPathObj_t::objOut, MmwDemo_output_message_header_t::platform, R4F_CLOCK_MHZ, MmwDemo_DataPathObj_t::rangeDopplerLogMagMatrix, MmwDemo_output_message_header_t::timeCpuCycles, MmwDemo_DataPathObj_t::timingInfo, MmwDemo_output_message_header_t::totalPacketLen, MmwDemo_timingInfo::transmitOutputCycles, MmwDemo_output_message_stats_t::transmitOutputTime, MmwDemo_output_message_tl_t::type, MmwDemo_output_message_header_t::version, MmwDemo_DataPathObj_t::xyzOutputQFormat, and MmwDemo_output_message_dataObjDescr_t::xyzQFormat.
Referenced by MmwDemo_dataPathTask().
Variable Documentation
rlRfRxSaturationCqData_t gCQRxSatMonMemory
Definition at line 713 of file main.c.
Referenced by MmwDemo_dataPathConfigCQ().
rlRfSigImgPowerCqData_t gCQRxSigImgMemory
Definition at line 716 of file main.c.
Referenced by MmwDemo_dataPathConfigCQ().
mmwHwaBuf_t gMmwHwaMemBuf[MMW_HWA_NUM_MEM_BUFS]
HWA memory buffer to produce the M0,M1,M2,M3 partition addresses and link to the HWA section in the linker command file.
Definition at line 105 of file data_path.c.
uint8_t gMmwL3[SOC_XWR14XX_MSS_L3RAM_SIZE]
L3 RAM buffer
Definition at line 709 of file main.c.
MmwDemoMemPool_t gMmwL3heap
Initial value:
=
{
    &gMmwL3[0],
    SOC_XWR14XX_MSS_L3RAM_SIZE,
    0
}
L3 heap for convenience of partitioning L3 RAM
Definition at line 719 of file main.c.
MmwDemo_MCB gMmwMCB
Global Variable for tracking information required by the mmw Demo.
Definition at line 734 of file main.c.
Referenced by MmwDemo_doSensorOpen(), MmwDemo_doSensorStart(), and MmwDemo_doSensorStop().
Copyright 2018, Texas Instruments Incorporated