xwr14xx/mmw/post_processing.h File Reference
post_processing.h File Reference
Routines for post processing (detection/angle estimation) of data output by the Hardware Accelerator.
#include "config_hwa_util.h"
#include "data_path.h"
#include <ti/demo/io_interface/mmw_config.h>
Functions
uint32_t postDetectionProcessing (uint32_t numDetectedObjects, uint16_t *detBuffptr, cfarDetOutput_t *cfarObjptr, uint32_t *fftBuffptr, MmwDemo_detectedObj *objOut, uint32_t *dstPtrAzim, uint32_t *dstPtrElev, uint32_t numTxAnt, uint32_t numRxAnt, uint32_t numVirtualAntAzim, uint32_t numVirtualAntElev, uint32_t numDopplerBins, uint32_t numRangeBins, uint32_t minRangeIdx, uint32_t maxRangeIdx, uint32_t groupInDopplerDirection, uint32_t groupInRangeDirection)
Function is executed after the HWA CFAR algorithm. It reduces the number of detected objects performed by CFAR algorithm. It selects only those objects with peaks greater than its neighbors.
void MmwDemo_dopplerCompensation (uint32_t numDetectedObjects, uint32_t *srcPtrAzim, uint32_t *srcPtrElev, MmwDemo_detectedObj *objOut, uint32_t *dstPtrAzim, uint32_t *dstPtrElev, uint32_t numTxAnt, uint32_t numRxAnt, uint32_t numVirtualAntAzim, uint32_t numVirtualAntElev, uint32_t numDopplerBins)
Function is executed after the HWA CFAR algorithm or Peak grouping if enabled. It compensates the Siganl on Azimuth and Elevation attennas due to signal transmit time shift from different TX antennas.
void MmwDemo_azimHeapMapDopplerCompensation (cmplx16ImRe_t *azimuthHeapMap, uint16_t dopplerIdx, uint32_t numTxAnt, uint32_t numRxAnt, uint32_t numVirtualAntAzim, uint32_t numVirtualAntElev, uint32_t numDopplerBins, uint32_t numRangeBins)
Function is executed after the HWA CFAR algorithm or Peak grouping if enabled. It compensates the Siganl on Azimuth and Elevation attennas due to signal transmit time shift from different TX antennas.
uint32_t MmwDemo_peakGrouping (uint32_t numDetectedObjects, uint16_t *detBuffptr, cfarDetOutput_t *cfarObjptr, uint32_t *fftBuffptr, MmwDemo_detectedObj *objOut, uint32_t *peakGrpAzimOut, uint32_t *peakGrpElevOut, uint32_t numVirtualAntAzim, uint32_t numVirtualAntElev, uint32_t numDopplerBins, uint32_t minRangeIdx, uint32_t maxRangeIdx, uint32_t groupInDopplerDirection, uint32_t groupInRangeDirection)
Function is executed after the HWA CFAR algorithm. It reduces the number of detected objects performed by CFAR algorithm. It selects only those objects with peaks greater than its neighbors.
void angleEstimationAzimElev (uint16_t *azimFFTAbsPtr, uint16_t *azimFFTPtr, uint16_t *elevFFTPtr, MmwDemo_DataPathObj *obj)
Function finds for each detected object the peak in the azimut FFT and the based on complex values of azimuth and elevation FFT corresponding to peak position, calculates the x,y,z coordinates of the object.
uint32_t calcNoiseFloor (uint32_t *radarCubedMemPtr, uint32_t numDopplerBins, uint32_t numRangeBins, uint32_t numVirtualAnt)
Calculate noise energy (diagnostic only) This routine calculates the noise energy Assumes a predominantly static scene- and averages the values in the high velocity bins to estimate noise energy.
Detailed Description
Routines for post processing (detection/angle estimation) of data output by the Hardware Accelerator.
NOTE: (C) Copyright 2016 Texas Instruments, Inc.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Texas Instruments Incorporated nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file post_processing.h.
Function Documentation
void angleEstimationAzimElev (uint16_t * azimFFTAbsPtr, uint16_t * azimFFTPtr, uint16_t * elevFFTPtr, MmwDemo_DataPathObj * obj)
Function finds for each detected object the peak in the azimut FFT and the based on complex values of azimuth and elevation FFT corresponding to peak position, calculates the x,y,z coordinates of the object.
Parameters
[in] azimFFTAbsPtr Pointer to array with magnitude values of azimuth FFTs of detected objects. The length of each FFT is numAngleBins. The size of input array is numAngleBins * numObjOut
[in] azimFFTPtr Pointer to array with complex values of azimuth FFTs of detected objects. The length of each FFT is numAngleBins. The size of input array is numAngleBins * numObjOut
[in] elevFFTPtr Pointer to array with complex values of elevation FFTs of detected objects. The length of each FFT is numAngleBins. The size of input array is numAngleBins * numObjOut
[in] obj Pointer to Data path object.
Definition at line 543 of file post_processing.c.
References MmwDemo_DataPathObj_t::cliCfg, MmwDemo_DataPathObj_t::detObj2dAzimIdx, MMW_MAX_OBJ_ELEVATION, MMW_MAX_OBJ_OUT, MmwDemo_XYZestimation(), MmwDemo_DataPathObj_t::numAngleBins, MmwDemo_DataPathObj_t::numObjOut, MmwDemo_DataPathObj_t::numVirtualAntElev, and MmwDemo_DataPathObj_t::objOut.
Referenced by MmwDemo_processAngle().
uint32_t calcNoiseFloor (uint32_t * radarCubedMemPtr, uint32_t numDopplerBins, uint32_t numRangeBins, uint32_t numVirtualAnt)
Calculate noise energy (diagnostic only) This routine calculates the noise energy Assumes a predominantly static scene- and averages the values in the high velocity bins to estimate noise energy.
Parameters
[in] radarCubedMemPtr Pointer to 2nd D FFT buffer with complex symbols. The size of buffer is numRangeBins * numDopplerBins * (numVirtualAntAzim + numVirtualAntElev)
[in] numDopplerBins Number of Doppler bins
[in] numRangeBins Number of range bins
[in] numVirtualAnt Number of virtual antennas
Definition at line 670 of file post_processing.c.
Referenced by MmwDemo_dataPathTask().
void MmwDemo_azimHeapMapDopplerCompensation (cmplx16ImRe_t * azimuthHeapMap, uint16_t dopplerIdx, uint32_t numTxAnt, uint32_t numRxAnt, uint32_t numVirtualAntAzim, uint32_t numVirtualAntElev, uint32_t numDopplerBins, uint32_t numRangeBins)
Function is executed after the HWA CFAR algorithm or Peak grouping if enabled. It compensates the Siganl on Azimuth and Elevation attennas due to signal transmit time shift from different TX antennas.
Parameters
[in] azimuthHeapMap Pointer to Azimuth Heap map that filled with antenna symbols. The compensation will be applied in place.
[in] dopplerIdx Doppler Index used for doppler compensation
[in] numTxAnt Number of Tx antennas
[in] numRxAnt Number of Rx antennas
[in] numVirtualAntAzim Number of virtual Rx antennas
[in] numVirtualAntElev Number of virtual Rx antennas
[in] numDopplerBins Number of Doppler bins
[in] numRangeBins Number of Range bins
Returns
None
Definition at line 369 of file post_processing.c.
References MmwDemo_calcCompIdx(), MmwDemo_dopplerComp(), and PI_.
Referenced by MmwDemo_dopplerCompensation(), and MmwDemo_processAngle().
void MmwDemo_dopplerCompensation (uint32_t numDetectedObjects, uint32_t * srcPtrAzim, uint32_t * srcPtrElev, MmwDemo_detectedObj * objOut, uint32_t * dstPtrAzim, uint32_t * dstPtrElev, uint32_t numTxAnt, uint32_t numRxAnt, uint32_t numVirtualAntAzim, uint32_t numVirtualAntElev, uint32_t numDopplerBins)
Function is executed after the HWA CFAR algorithm or Peak grouping if enabled. It compensates the Siganl on Azimuth and Elevation attennas due to signal transmit time shift from different TX antennas.
Parameters
[in] numDetectedObjects Number of detected objects by HWA CFAR algorithm
[in] srcPtrAzim Input pointer (local memory of HWA) filled with antenna symbols of selected objects for azimuth calculation.
[in] srcPtrElev Input pointer (local memory of HWA) filled with antenna symbols of selected objects for elevation calculation.
[in] objOut Output pointer to the structure with with selected objects. The function fills range and doppler index of the object.
[out] dstPtrAzim Output pointer (local memory of HWA) filled with antenna symbols of selected objects for azimuth calculation.
[out] dstPtrElev Output pointer (local memory of HWA) filled with antenna symbols of selected objects for elevation calculation.
[in] numTxAnt Number of Tx antennas
[in] numRxAnt Number of Rx antennas
[in] numVirtualAntAzim Number of virtual Rx antennas
[in] numVirtualAntElev Number of virtual Rx antennas
[in] numDopplerBins Number of Doppler bins
Returns
None
Definition at line 307 of file post_processing.c.
References MmwDemo_azimHeapMapDopplerCompensation(), MmwDemo_calcCompIdx(), MmwDemo_dopplerComp(), and PI_.
Referenced by MmwDemo_calcCompIdx(), and MmwDemo_processAngle().
uint32_t MmwDemo_peakGrouping (uint32_t numDetectedObjects, uint16_t * detBuffptr, cfarDetOutput_t * cfarObjptr, uint32_t * fftBuffptr, MmwDemo_detectedObj * objOut, uint32_t * peakGrpAzimOut, uint32_t * peakGrpElevOut, uint32_t numVirtualAntAzim, uint32_t numVirtualAntElev, uint32_t numDopplerBins, uint32_t minRangeIdx, uint32_t maxRangeIdx, uint32_t groupInDopplerDirection, uint32_t groupInRangeDirection)
Function is executed after the HWA CFAR algorithm. It reduces the number of detected objects performed by CFAR algorithm. It selects only those objects with peaks greater than its neighbors.
Parameters
[in] numDetectedObjects Number of detected objects by HWA CFAR algorithm
[in] detBuffptr Pointer to range-doppler matrix which was used by CFAR alogorithm to generate detected objects, size number of range bins times number of doppler bins.
[in] cfarObjptr Pointer to the output structure generated by CFAR algorithm, contains list of detected objects.
[in] fftBuffptr Pointer to 2nd D FFT buffer with complex symbols. The size of buffer is numRangeBins * numDopplerBins * (numVirtualAntAzim + numVirtualAntElev).
[out] objOut Output pointer to the structure with with selected objects. The function fills range and doppler index of the object.
[out] peakGrpAzimOut Output pointer (local memory of HWA) filled with antenna symbols of selected objects for azimuth calculation.
[out] peakGrpElevOut Output pointer (local memory of HWA) filled with antenna symbols of selected objects for elevation calculation.
[in] numVirtualAntAzim Number of virtual Rx antennas
[in] numVirtualAntElev Number of virtual Rx antennas
[in] numDopplerBins Number of Doppler bins
[in] minRangeIdx Minimum range index to be exported
[in] maxRangeIdx Maximum range index to be exported
[in] groupInDopplerDirection peak grouping in Doppler direction 0-disabled, 1-enabled
[in] groupInRangeDirection peak grouping in Range direction 0-disabled, 1-enabled
Returns
numObjOut Number of selected objects
Function is executed after the HWA CFAR algorithm. It reduces the number of detected objects performed by CFAR algorithm. It selects only those objects with peaks greater than its neighbors.
Definition at line 66 of file post_processing.c.
References MMW_MAX_OBJ_ELEVATION, MMW_MAX_OBJ_OUT, and MmwDemo_dopplerComp().
Referenced by MmwDemo_processAngle().
uint32_t postDetectionProcessing (uint32_t numDetectedObjects, uint16_t * detBuffptr, cfarDetOutput_t * cfarObjptr, uint32_t * fftBuffptr, MmwDemo_detectedObj * objOut, uint32_t * dstPtrAzim, uint32_t * dstPtrElev, uint32_t numTxAnt, uint32_t numRxAnt, uint32_t numVirtualAntAzim, uint32_t numVirtualAntElev, uint32_t numDopplerBins, uint32_t numRangeBins, uint32_t minRangeIdx, uint32_t maxRangeIdx, uint32_t groupInDopplerDirection, uint32_t groupInRangeDirection)
Function is executed after the HWA CFAR algorithm. It reduces the number of detected objects performed by CFAR algorithm. It selects only those objects with peaks greater than its neighbors.
Parameters
[in] numDetectedObjects Number of detected objects by HWA CFAR algorithm
[in] detBuffptr Pointer to range-doppler matrix which was used by CFAR alogorithm to generate detected objects, size number of range bins times number of doppler bins.
[in] cfarObjptr Pointer to the output structure generated by CFAR algorithm, contains list of detected objects.
[in] fftBuffptr Pointer to 2nd D FFT buffer with complex symbols. The size of buffer is numRangeBins * numDopplerBins * (numVirtualAntAzim + numVirtualAntElev).
[out] objOut Output pointer to the structure with with selected objects. The function fills range and doppler index of the object.
[out] dstPtrAzim Output pointer (local memory of HWA) filled with antenna symbols of selected objects for azimuth calculation.
[out] dstPtrElev Output pointer (local memory of HWA) filled with antenna symbols of selected objects for elevation calculation.
[in] numTxAnt Number of Tx antennas
[in] numRxAnt Number of Rx antennas
[in] numVirtualAntAzim Number of virtual azimuth Rx antennas
[in] numVirtualAntElev Number of virtual elevation Rx antennas
[in] numDopplerBins Number of Doppler bins
[in] numRangeBins NUmber of Range bins
[in] minRangeIdx minimum range index to be exported
[in] maxRangeIdx maximum range index to be exported
[in] groupInDopplerDirection peak grouping in Doppler direction 0-disabled, 1-enabled
[in] groupInRangeDirection peak grouping in Range direction 0-disabled, 1-enabled
Returns
numObjOut Number of selected objects
Copyright 2018, Texas Instruments Incorporated