xwr14xx/mmw/sensor_mgmt.c File Reference
sensor_mgmt.c File Reference
The file implements the sensor management. Sensors can be started or stopped by either the GPIO Switch or through the CLI.
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <xdc/std.h>
#include <xdc/cfg/global.h>
#include <xdc/runtime/IHeap.h>
#include <xdc/runtime/System.h>
#include <xdc/runtime/Error.h>
#include <xdc/runtime/Memory.h>
#include <ti/sysbios/BIOS.h>
#include <ti/sysbios/knl/Task.h>
#include <ti/sysbios/knl/Event.h>
#include <ti/sysbios/knl/Semaphore.h>
#include <ti/sysbios/knl/Clock.h>
#include <ti/sysbios/heaps/HeapBuf.h>
#include <ti/sysbios/heaps/HeapMem.h>
#include <ti/sysbios/family/arm/v7a/Pmu.h>
#include <ti/sysbios/family/arm/v7r/vim/Hwi.h>
#include <ti/common/sys_common.h>
#include <ti/drivers/soc/soc.h>
#include <ti/drivers/esm/esm.h>
#include <ti/drivers/gpio/gpio.h>
#include <ti/drivers/crc/crc.h>
#include <ti/drivers/uart/UART.h>
#include <ti/drivers/mailbox/mailbox.h>
#include <ti/control/mmwave/mmwave.h>
#include <ti/drivers/osal/DebugP.h>
#include <ti/utils/cli/cli.h>
#include "mmw.h"
#include "data_path.h"
Data Structures
struct MmwDemo_SensorMgmtMCB_t
Millimeter Wave Demo Session Management MCB.
Macros
#define MMWDEMO_CLI_SENSORSTART_EVT Event_Id_00
Sensor Start Event.
#define MMWDEMO_CLI_SENSORSTOP_EVT Event_Id_01
Sensor Stop Event.
#define MMWDEMO_CLI_FRAMESTART_EVT Event_Id_02
Sensor Start Event without reconfig.
#define MMWDEMO_START_COMPLETED_EVT Event_Id_03
Sensor start completed event.
#define MMWDEMO_STOP_COMPLETED_EVT Event_Id_04
Sensor stop completed event.
#define MMWDEMO_START_FAILED_EVT Event_Id_05
Sensor start failed event.
#define MMWDEMO_KEY_PRESS_EVT Event_Id_06
Sensor start key event.
#define MMWDEMO_BSS_STOP_EVT Event_Id_07
Sensor BSS stop event.
#define MMWDEMO_DATAPATH_STOP_EVT Event_Id_08
Sensor Datapath stop event.
#define MMWDEMO_DATAPATH_STOP_STATUS 1U
Sensor Stop status bit for Data path - Bit 0.
#define MMWDEMO_BSS_STOP_STATUS 2U
Sensor Stop status bit for BSS - Bit 1.
#define MMWDEMO_CTRLPATH_STOP_STATUS 4U
Sensor Stop status bit for Data path - Bit 2.
#define MMWDEMO_ALLCOMP_STOP_STATUS
Sensor Stop status bits for all components.
Typedefs
typedef enum MmwDemo_SensorState_e MmwDemo_SensorState
Millimeter Wave Demo Sensor State.
typedef enum MmwDemo_SensorEvent_e MmwDemo_SensorEvent
Millimeter Wave Demo Sensor Event.
typedef void(* MmwDemo_sensorSMFunc) (MmwDemo_SensorEvent event)
typedef struct MmwDemo_SensorMgmtMCB_t MmwDemo_SensorMgmtMCB
Millimeter Wave Demo Session Management MCB.
Enumerations
enum MmwDemo_SensorState_e {
MmwDemo_SensorState_INIT = 0, MmwDemo_SensorState_START, MmwDemo_SensorState_STOP_PENDING, MmwDemo_SensorState_STOP,
MmwDemo_SensorState_MAX
}
Millimeter Wave Demo Sensor State.
enum MmwDemo_SensorEvent_e {
MmwDemo_SensorEvent_START = 0, MmwDemo_SensorEvent_STOP, MmwDemo_SensorEvent_FRAME_START, MmwDemo_SensorEvent_KEY_PRESS,
MmwDemo_SensorEvent_BSS_STOP, MmwDemo_SensorEvent_DATAPATH_STOP, MmwDemo_SensorEvent_MAX
}
Millimeter Wave Demo Sensor Event.
Functions
int32_t MmwDemo_setHsiClk (void)
static bool MmwDemo_doSensorOpen (void)
static bool MmwDemo_doSensorStart (void)
static bool MmwDemo_doSensorFrameStart (void)
static bool MmwDemo_doSensorStop (void)
static void MmwDemo_finishSensorStop (void)
void MmwDemo_sensorStateInit (MmwDemo_SensorEvent event)
void MmwDemo_sensorStateStart (MmwDemo_SensorEvent event)
void MmwDemo_sensorStateStopPending (MmwDemo_SensorEvent event)
void MmwDemo_sensorStateStop (MmwDemo_SensorEvent event)
static void MmwDemo_switchPressFxn (unsigned int index)
static void MmwDemo_sensorMgmtTask (UArg arg0, UArg arg1)
void MmwDemo_notifySensorStart (bool doReconfig)
void MmwDemo_notifySensorStop (void)
int32_t MmwDemo_waitSensorStartComplete (void)
void MmwDemo_waitSensorStopComplete (void)
void MmwDemo_notifyBssSensorStop (void)
void MmwDemo_notifyDathPathStop (void)
int32_t MmwDemo_sensorMgmtInit (void)
int32_t MmwDemo_sensorMgmtDeinit (void)
Variables
MmwDemo_SensorMgmtMCB gMmwSessionMgmtMCB
Global variable which is used to keep relevant information used by the Session Management module.
MmwDemo_sensorSMFunc MmwDemo_sensorStateMachine [MmwDemo_SensorState_MAX]
Sensor Management state machine.
Detailed Description
The file implements the sensor management. Sensors can be started or stopped by either the GPIO Switch or through the CLI.
NOTE: (C) Copyright 2016 Texas Instruments, Inc.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Texas Instruments Incorporated nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file sensor_mgmt.c.
Macro Definition Documentation
#define MMWDEMO_ALLCOMP_STOP_STATUS
Value:
(MMWDEMO_DATAPATH_STOP_STATUS |    \
                                                MMWDEMO_BSS_STOP_STATUS         |  \
                                                MMWDEMO_CTRLPATH_STOP_STATUS)
Sensor Stop status bits for all components.
Definition at line 161 of file sensor_mgmt.c.
Referenced by MmwDemo_sensorStateStart(), and MmwDemo_sensorStateStopPending().
#define MMWDEMO_BSS_STOP_EVT Event_Id_07
Sensor BSS stop event.
Definition at line 133 of file sensor_mgmt.c.
Referenced by MmwDemo_notifyBssSensorStop(), and MmwDemo_sensorMgmtTask().
#define MMWDEMO_BSS_STOP_STATUS 2U
Sensor Stop status bit for BSS - Bit 1.
Definition at line 151 of file sensor_mgmt.c.
Referenced by MmwDemo_sensorStateStart(), and MmwDemo_sensorStateStopPending().
#define MMWDEMO_CLI_FRAMESTART_EVT Event_Id_02
Sensor Start Event without reconfig.
Definition at line 108 of file sensor_mgmt.c.
Referenced by MmwDemo_notifySensorStart(), and MmwDemo_sensorMgmtTask().
#define MMWDEMO_CLI_SENSORSTART_EVT Event_Id_00
Sensor Start Event.
Definition at line 98 of file sensor_mgmt.c.
Referenced by MmwDemo_notifySensorStart(), and MmwDemo_sensorMgmtTask().
#define MMWDEMO_CLI_SENSORSTOP_EVT Event_Id_01
Sensor Stop Event.
Definition at line 103 of file sensor_mgmt.c.
Referenced by MmwDemo_notifySensorStop(), and MmwDemo_sensorMgmtTask().
#define MMWDEMO_CTRLPATH_STOP_STATUS 4U
Sensor Stop status bit for Data path - Bit 2.
Definition at line 156 of file sensor_mgmt.c.
Referenced by MmwDemo_doSensorStop(), and MmwDemo_sensorStateStopPending().
#define MMWDEMO_DATAPATH_STOP_EVT Event_Id_08
Sensor Datapath stop event.
Definition at line 138 of file sensor_mgmt.c.
Referenced by MmwDemo_notifyDathPathStop(), and MmwDemo_sensorMgmtTask().
#define MMWDEMO_DATAPATH_STOP_STATUS 1U
Sensor Stop status bit for Data path - Bit 0.
Definition at line 146 of file sensor_mgmt.c.
Referenced by MmwDemo_sensorStateStopPending().
#define MMWDEMO_KEY_PRESS_EVT Event_Id_06
Sensor start key event.
Definition at line 128 of file sensor_mgmt.c.
Referenced by MmwDemo_sensorMgmtTask(), and MmwDemo_switchPressFxn().
#define MMWDEMO_START_COMPLETED_EVT Event_Id_03
Sensor start completed event.
Definition at line 113 of file sensor_mgmt.c.
Referenced by MmwDemo_sensorStateInit(), MmwDemo_sensorStateStart(), MmwDemo_sensorStateStop(), MmwDemo_sensorStateStopPending(), and MmwDemo_waitSensorStartComplete().
#define MMWDEMO_START_FAILED_EVT Event_Id_05
Sensor start failed event.
Definition at line 123 of file sensor_mgmt.c.
Referenced by MmwDemo_doSensorOpen(), MmwDemo_sensorStateInit(), MmwDemo_sensorStateStop(), and MmwDemo_waitSensorStartComplete().
#define MMWDEMO_STOP_COMPLETED_EVT Event_Id_04
Sensor stop completed event.
Definition at line 118 of file sensor_mgmt.c.
Referenced by MmwDemo_sensorStateInit(), MmwDemo_sensorStateStop(), MmwDemo_sensorStateStopPending(), and MmwDemo_waitSensorStopComplete().
Typedef Documentation
typedef enum MmwDemo_SensorEvent_e MmwDemo_SensorEvent
Millimeter Wave Demo Sensor Event.
The enumeration is used to define the sensor events used in mmwDemo
typedef struct MmwDemo_SensorMgmtMCB_t MmwDemo_SensorMgmtMCB
Millimeter Wave Demo Session Management MCB.
The structure is used to hold all the relevant information for the Millimeter Wave demo session management module
typedef void(* MmwDemo_sensorSMFunc) (MmwDemo_SensorEvent event)
Definition at line 257 of file sensor_mgmt.c.
typedef enum MmwDemo_SensorState_e MmwDemo_SensorState
Millimeter Wave Demo Sensor State.
The enumeration is used to define the sensor states used in mmwDemo
Enumeration Type Documentation
enum MmwDemo_SensorEvent_e
Millimeter Wave Demo Sensor Event.
The enumeration is used to define the sensor events used in mmwDemo
Enumerator
MmwDemo_SensorEvent_START
mmwDemo Sensor start event
MmwDemo_SensorEvent_STOP
mmwDemo Sensor stop event
MmwDemo_SensorEvent_FRAME_START
mmwDemo Sensor frame start event
MmwDemo_SensorEvent_KEY_PRESS
mmwDemo key press event
MmwDemo_SensorEvent_BSS_STOP
mmwDemo BSS stop event
MmwDemo_SensorEvent_DATAPATH_STOP
mmwDemo data path stop event
MmwDemo_SensorEvent_MAX
mmwDemo maximum event
Definition at line 218 of file sensor_mgmt.c.
enum MmwDemo_SensorState_e
Millimeter Wave Demo Sensor State.
The enumeration is used to define the sensor states used in mmwDemo
Enumerator
MmwDemo_SensorState_INIT
mmwDemo Sensor INIT state. This is the inital state after sensor is initialized.
MmwDemo_SensorState_START
mmwDemo Sensor START state. This is the state after sensor is started through mmwave_start()
MmwDemo_SensorState_STOP_PENDING
mmwDemo Sensor STOP PEDNING state. This is the state after sensor is stopped through mmwave_stop(), and waiting for all modules(such as datapath, Bss etc) to reach full stop state.
MmwDemo_SensorState_STOP
mmwDemo Sensor STOP state. This is the state that radar sensor including all its componets reach stop state.
MmwDemo_SensorState_MAX
mmwDemo Sensor maximum supported state.
Definition at line 176 of file sensor_mgmt.c.
Function Documentation
static bool MmwDemo_doSensorFrameStart (void) static
Description
mmw demo helper Function to do sensor frame Start
Return values
start Status: true - start successfully false - start failed
Definition at line 554 of file sensor_mgmt.c.
References MmwDemo_SensorMgmtMCB_t::isSensorStarted, MmwDemo_dataPathStart(), MmwDemo_debugAssert, MmwDemo_SensorMgmtMCB_t::sensorStartCount, MmwDemo_SensorMgmtMCB_t::sensorStopStatus, and SOC_XWR14XX_GPIO_2.
Referenced by MmwDemo_sensorStateStop().
static bool MmwDemo_doSensorOpen (void) static
Description
Return values
open Status: true - open successfully false - open failed
Definition at line 385 of file sensor_mgmt.c.
References MmwDemo_MCB_t::cfg, CLI_getMMWaveExtensionOpenConfig(), MmwDemo_MCB_t::ctrlHandle, MmwDemo_SensorMgmtMCB_t::eventHandleNotify, gMmwMCB, MmwDemo_SensorMgmtMCB_t::isSensorOpened, MmwDemo_debugAssert, MmwDemo_setHsiClk(), and MMWDEMO_START_FAILED_EVT.
Referenced by MmwDemo_sensorStateInit(), and MmwDemo_sensorStateStop().
static bool MmwDemo_doSensorStart (void) static
Description
mmw demo helper Function to do sensor Start
Return values
start Status: true - start successfully false - start failed
Definition at line 484 of file sensor_mgmt.c.
References MmwDemo_MCB_t::cfg, CLI_getMMWaveExtensionConfig(), MmwDemo_MCB_t::ctrlHandle, gMmwMCB, MmwDemo_SensorMgmtMCB_t::isSensorStarted, MmwDemo_dataPathConfig(), MmwDemo_dataPathStart(), MmwDemo_debugAssert, MmwDemo_SensorMgmtMCB_t::sensorStartCount, MmwDemo_SensorMgmtMCB_t::sensorStopStatus, and SOC_XWR14XX_GPIO_2.
Referenced by MmwDemo_sensorStateInit(), and MmwDemo_sensorStateStop().
static bool MmwDemo_doSensorStop (void) static
Description
mmw demo helper Function to trigger sensor Stop
Return values
start Status: true - start successfully false - start failed
Definition at line 597 of file sensor_mgmt.c.
References MmwDemo_MCB_t::ctrlHandle, MmwDemo_MCB_t::dataPathObj, gMmwMCB, MmwDemo_SensorMgmtMCB_t::isSensorStarted, MMWDEMO_CTRLPATH_STOP_STATUS, MmwDemo_dataPathStop(), MmwDemo_debugAssert, and MmwDemo_SensorMgmtMCB_t::sensorStopStatus.
Referenced by MmwDemo_sensorStateStart(), and MmwDemo_sensorStateStopPending().
static void MmwDemo_finishSensorStop (void) static
Description
mmw demo helper Function to finish sensor Stop when stop is done successfully
Return values
start Status: true - start successfully false - start failed
Definition at line 664 of file sensor_mgmt.c.
References MmwDemo_SensorMgmtMCB_t::isSensorStarted, MmwDemo_SensorMgmtMCB_t::sensorStartCount, MmwDemo_SensorMgmtMCB_t::sensorStopCount, and SOC_XWR14XX_GPIO_2.
Referenced by MmwDemo_sensorStateStopPending().
void MmwDemo_notifyBssSensorStop (void)
Description
This is a utility function which can be invoked from the data path to notify that actual BSS sensor stop completed.
Return values
Not applicable
Definition at line 1260 of file sensor_mgmt.c.
References MMWDEMO_BSS_STOP_EVT, and MmwDemo_SensorMgmtMCB_t::sensorMgmtEventHandle.
Referenced by MmwDemo_eventCallbackFxn().
void MmwDemo_notifyDathPathStop (void)
Description
This is a utility function which can be invoked from the data path to notify that data path stop completed.
Return values
Not applicable
Definition at line 1274 of file sensor_mgmt.c.
References MMWDEMO_DATAPATH_STOP_EVT, and MmwDemo_SensorMgmtMCB_t::sensorMgmtEventHandle.
Referenced by MmwDemo_dataPathStop(), and MmwDemo_dataPathTask().
void MmwDemo_notifySensorStart (bool doReconfig)
Description
This is a utility function which can be invoked from the CLI or the Switch press to start the sensor. This sends an event to the sensor management task where the actual start procedure is implemented.
Return values
Not applicable
Definition at line 1150 of file sensor_mgmt.c.
References MMWDEMO_CLI_FRAMESTART_EVT, MMWDEMO_CLI_SENSORSTART_EVT, and MmwDemo_SensorMgmtMCB_t::sensorMgmtEventHandle.
Referenced by MmwDemo_CLISensorStart().
void MmwDemo_notifySensorStop (void)
Description
This is a utility function which can be invoked from the CLI or the Switch press to start the sensor. This sends an event to the sensor management task where the actual start procedure is implemented.
Return values
Not applicable
Definition at line 1171 of file sensor_mgmt.c.
References MMWDEMO_CLI_SENSORSTOP_EVT, and MmwDemo_SensorMgmtMCB_t::sensorMgmtEventHandle.
Referenced by MmwDemo_CLISensorStop().
int32_t MmwDemo_sensorMgmtDeinit (void)
Description
This is the function which is used to deinitialize and shutdown the sensor management module
Return values
Success - 0
Error - <0
Definition at line 1344 of file sensor_mgmt.c.
References MmwDemo_SensorMgmtMCB_t::eventHandleNotify, MmwDemo_SensorMgmtMCB_t::sensorMgmtEventHandle, and MmwDemo_SensorMgmtMCB_t::sensorMgmtTaskHandle.
int32_t MmwDemo_sensorMgmtInit (void)
Description
This is the function which is used to initialize and setup the sensor management module.
Return values
Success - 0
Error - <0
Definition at line 1290 of file sensor_mgmt.c.
References MmwDemo_SensorMgmtMCB_t::eventHandleNotify, MmwDemo_SensorMgmtMCB_t::isSensorStarted, MmwDemo_debugAssert, MmwDemo_sensorMgmtTask(), MmwDemo_SensorState_INIT, MmwDemo_SensorMgmtMCB_t::sensorMgmtEventHandle, MmwDemo_SensorMgmtMCB_t::sensorMgmtTaskHandle, and MmwDemo_SensorMgmtMCB_t::state.
Referenced by MmwDemo_initTask().
static void MmwDemo_sensorMgmtTask (UArg arg0, UArg arg1) static
Description
This is the sensor management task which is used to start & stop the sensor. Sensors can be controlled via the CLI or the switch
Return values
Not Applicable.
Definition at line 1043 of file sensor_mgmt.c.
References MmwDemo_SensorMgmtMCB_t::keyPressEvent, MMWDEMO_BSS_STOP_EVT, MMWDEMO_CLI_FRAMESTART_EVT, MMWDEMO_CLI_SENSORSTART_EVT, MMWDEMO_CLI_SENSORSTOP_EVT, MMWDEMO_DATAPATH_STOP_EVT, MmwDemo_debugAssert, MMWDEMO_KEY_PRESS_EVT, MmwDemo_SensorEvent_BSS_STOP, MmwDemo_SensorEvent_DATAPATH_STOP, MmwDemo_SensorEvent_FRAME_START, MmwDemo_SensorEvent_KEY_PRESS, MmwDemo_SensorEvent_START, MmwDemo_SensorEvent_STOP, MmwDemo_SensorState_MAX, MmwDemo_sensorStateMachine, MmwDemo_switchPressFxn(), MmwDemo_SensorMgmtMCB_t::sensorMgmtEventHandle, SOC_XWR14XX_GPIO_1, SOC_XWR14XX_GPIO_2, and MmwDemo_SensorMgmtMCB_t::state.
Referenced by MmwDemo_sensorMgmtInit().
void MmwDemo_sensorStateInit (MmwDemo_SensorEvent event)
Description
This function implements the sensor state machine in INIT state
Parameters
[in] event mmwDemo event sent to sensor state machine
Return values
Not applicable
Definition at line 688 of file sensor_mgmt.c.
References MmwDemo_SensorMgmtMCB_t::eventHandleNotify, MmwDemo_debugAssert, MmwDemo_doSensorOpen(), MmwDemo_doSensorStart(), MmwDemo_SensorEvent_BSS_STOP, MmwDemo_SensorEvent_DATAPATH_STOP, MmwDemo_SensorEvent_FRAME_START, MmwDemo_SensorEvent_KEY_PRESS, MmwDemo_SensorEvent_START, MmwDemo_SensorEvent_STOP, MmwDemo_SensorState_START, MMWDEMO_START_COMPLETED_EVT, MMWDEMO_START_FAILED_EVT, MMWDEMO_STOP_COMPLETED_EVT, and MmwDemo_SensorMgmtMCB_t::state.
void MmwDemo_sensorStateStart (MmwDemo_SensorEvent event)
Description
This function implements the sensor state machine in START state
Parameters
[in] event mmwDemo event sent to sensor state machine
Return values
Not applicable
Definition at line 749 of file sensor_mgmt.c.
References MmwDemo_SensorMgmtMCB_t::eventHandleNotify, MMWDEMO_ALLCOMP_STOP_STATUS, MMWDEMO_BSS_STOP_STATUS, MmwDemo_debugAssert, MmwDemo_doSensorStop(), MmwDemo_SensorEvent_BSS_STOP, MmwDemo_SensorEvent_DATAPATH_STOP, MmwDemo_SensorEvent_FRAME_START, MmwDemo_SensorEvent_KEY_PRESS, MmwDemo_SensorEvent_START, MmwDemo_SensorEvent_STOP, MmwDemo_SensorState_STOP_PENDING, MMWDEMO_START_COMPLETED_EVT, MmwDemo_SensorMgmtMCB_t::sensorStopStatus, and MmwDemo_SensorMgmtMCB_t::state.
void MmwDemo_sensorStateStop (MmwDemo_SensorEvent event)
Description
This function implements the sensor state machine in STOP state
Parameters
[in] event mmwDemo event sent to sensor state machine
Return values
Not applicable
Definition at line 916 of file sensor_mgmt.c.
References MmwDemo_SensorMgmtMCB_t::eventHandleNotify, MmwDemo_SensorMgmtMCB_t::keyPressEvent, MmwDemo_debugAssert, MmwDemo_doSensorFrameStart(), MmwDemo_doSensorOpen(), MmwDemo_doSensorStart(), MmwDemo_SensorEvent_BSS_STOP, MmwDemo_SensorEvent_DATAPATH_STOP, MmwDemo_SensorEvent_FRAME_START, MmwDemo_SensorEvent_KEY_PRESS, MmwDemo_SensorEvent_START, MmwDemo_SensorEvent_STOP, MmwDemo_SensorState_START, MMWDEMO_START_COMPLETED_EVT, MMWDEMO_START_FAILED_EVT, MMWDEMO_STOP_COMPLETED_EVT, and MmwDemo_SensorMgmtMCB_t::state.
void MmwDemo_sensorStateStopPending (MmwDemo_SensorEvent event)
Description
This function implements the sensor state machine in STOP Pending state
Parameters
[in] event mmwDemo event sent to sensor state machine
Return values
Not applicable
Definition at line 815 of file sensor_mgmt.c.
References MmwDemo_SensorMgmtMCB_t::eventHandleNotify, MmwDemo_SensorMgmtMCB_t::keyPressEvent, MMWDEMO_ALLCOMP_STOP_STATUS, MMWDEMO_BSS_STOP_STATUS, MMWDEMO_CTRLPATH_STOP_STATUS, MMWDEMO_DATAPATH_STOP_STATUS, MmwDemo_debugAssert, MmwDemo_doSensorStop(), MmwDemo_finishSensorStop(), MmwDemo_SensorEvent_BSS_STOP, MmwDemo_SensorEvent_DATAPATH_STOP, MmwDemo_SensorEvent_FRAME_START, MmwDemo_SensorEvent_KEY_PRESS, MmwDemo_SensorEvent_START, MmwDemo_SensorEvent_STOP, MmwDemo_SensorState_STOP, MMWDEMO_START_COMPLETED_EVT, MMWDEMO_STOP_COMPLETED_EVT, MmwDemo_SensorMgmtMCB_t::sensorStopStatus, and MmwDemo_SensorMgmtMCB_t::state.
int32_t MmwDemo_setHsiClk (void)
Description
mmw demo helper Function to do sensor Open Function to Setup the HSI Clock. Required for LVDS streaming.
Return values
0 - Success. <0 - Failed with errors
Definition at line 346 of file sensor_mgmt.c.
Referenced by MmwDemo_doSensorOpen().
static void MmwDemo_switchPressFxn (unsigned int index) static
Description
Callback function invoked when the GPIO switch is pressed. This is invoked from interrupt context.
Parameters
[in] index GPIO index configured as input
Return values
Not applicable
Definition at line 1029 of file sensor_mgmt.c.
References MMWDEMO_KEY_PRESS_EVT, and MmwDemo_SensorMgmtMCB_t::sensorMgmtEventHandle.
Referenced by MmwDemo_sensorMgmtTask().
int32_t MmwDemo_waitSensorStartComplete (void)
Description
This is a utility function which can be used by the CLI to pend for start complete (after MmwDemo_notifySensorStart is called)
Return values
Not applicable
Definition at line 1186 of file sensor_mgmt.c.
References MmwDemo_SensorMgmtMCB_t::eventHandleNotify, MmwDemo_debugAssert, MMWDEMO_START_COMPLETED_EVT, and MMWDEMO_START_FAILED_EVT.
Referenced by MmwDemo_CLISensorStart().
void MmwDemo_waitSensorStopComplete (void)
Description
This is a utility function which can be used by the CLI to pend for stop complete (after MmwDemo_notifySensorStart is called)
Return values
Not applicable
Definition at line 1228 of file sensor_mgmt.c.
References MmwDemo_SensorMgmtMCB_t::eventHandleNotify, MmwDemo_debugAssert, and MMWDEMO_STOP_COMPLETED_EVT.
Referenced by MmwDemo_CLISensorStop().
Variable Documentation
MmwDemo_SensorMgmtMCB gMmwSessionMgmtMCB
Global variable which is used to keep relevant information used by the Session Management module.
Definition at line 329 of file sensor_mgmt.c.
MmwDemo_sensorSMFunc MmwDemo_sensorStateMachine[MmwDemo_SensorState_MAX]
Initial value:
=
{
    MmwDemo_sensorStateInit,
    MmwDemo_sensorStateStart,
    MmwDemo_sensorStateStopPending,
    MmwDemo_sensorStateStop
}
Sensor Management state machine.
Definition at line 1009 of file sensor_mgmt.c.
Referenced by MmwDemo_sensorMgmtTask().
Copyright 2018, Texas Instruments Incorporated