xwr16xx/mmw/mss/cli.c File Reference
cli.c File Reference
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <xdc/std.h>
#include <xdc/cfg/global.h>
#include <xdc/runtime/IHeap.h>
#include <xdc/runtime/System.h>
#include <xdc/runtime/Error.h>
#include <xdc/runtime/Memory.h>
#include <ti/sysbios/BIOS.h>
#include <ti/sysbios/knl/Task.h>
#include <ti/sysbios/knl/Event.h>
#include <ti/sysbios/knl/Semaphore.h>
#include <ti/sysbios/knl/Clock.h>
#include <ti/sysbios/heaps/HeapBuf.h>
#include <ti/sysbios/heaps/HeapMem.h>
#include <ti/common/sys_common.h>
#include <ti/common/mmwave_sdk_version.h>
#include <ti/drivers/uart/UART.h>
#include <ti/control/mmwavelink/mmwavelink.h>
#include <ti/utils/cli/cli.h>
#include "ti/demo/xwr16xx/mmw/mss/mss_mmw.h"
#include "ti/demo/xwr16xx/mmw/common/mmw_messages.h"
Functions
static int32_t MmwDemo_CLICfarCfg (int32_t argc, char *argv[])
static int32_t MmwDemo_CLIPeakGroupingCfg (int32_t argc, char *argv[])
static int32_t MmwDemo_CLIMultiObjBeamForming (int32_t argc, char *argv[])
static int32_t MmwDemo_CLICalibDcRangeSig (int32_t argc, char *argv[])
static int32_t MmwDemo_CLIExtendedMaxVelocity (int32_t argc, char *argv[])
static int32_t MmwDemo_CLIClutterRemoval (int32_t argc, char *argv[])
static int32_t MmwDemo_CLISensorStart (int32_t argc, char *argv[])
static int32_t MmwDemo_CLISensorStop (int32_t argc, char *argv[])
static int32_t MmwDemo_CLIGuiMonSel (int32_t argc, char *argv[])
static int32_t MmwDemo_CLISetDataLogger (int32_t argc, char *argv[])
static int32_t MmwDemo_CLIADCBufCfg (int32_t argc, char *argv[])
static int32_t MmwDemo_CLICompRangeBiasAndRxChanPhaseCfg (int32_t argc, char *argv[])
static int32_t MmwDemo_CLIMeasureRangeBiasAndRxChanPhaseCfg (int32_t argc, char *argv[])
static int32_t MmwDemo_CLINearFieldCorrection (int32_t argc, char *argv[])
static int32_t MmwDemo_CLIChirpQualityRxSatMonCfg (int32_t argc, char *argv[])
static int32_t MmwDemo_CLIChirpQualitySigImgMonCfg (int32_t argc, char *argv[])
static int32_t MmwDemo_CLIAnalogMonitorCfg (int32_t argc, char *argv[])
static int32_t MmwDemo_CLILvdsStreamCfg (int32_t argc, char *argv[])
int32_t MmwDemo_mboxWrite (MmwDemo_message *message)
static int32_t MmwDemo_CLIGetSubframe (int32_t argc, char *argv[], int32_t expectedArgc, int8_t *subFrameNum)
static void MmwDemo_mssCfgUpdate (void *srcPtr, uint32_t offset, uint32_t size, int8_t subFrameNum)
uint32_t log2Approx (uint32_t x)
static int32_t MmwDemo_CLIBpmCfg (int32_t argc, char *argv[])
void MmwDemo_CLIInit (void)
Variables
MmwDemo_MCB gMmwMssMCB
Global Variable for tracking information required by the mmw Demo.
Function Documentation
uint32_t log2Approx (uint32_t x)
Definition at line 450 of file cli.c.
Referenced by MmwDemo_CLICalibDcRangeSig().
static int32_t MmwDemo_CLIADCBufCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for data logger set command
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 765 of file cli.c.
References MmwDemo_message_body_u::adcBufCfg, MmwDemo_ADCBufCfg_t::adcFmt, MmwDemo_message_t::body, MmwDemo_ADCBufCfg_t::chInterleave, MmwDemo_ADCBufCfg_t::chirpThreshold, MmwDemo_ADCBufCfg_t::iqSwapSel, MmwDemo_CLIGetSubframe(), MmwDemo_mboxWrite(), MMWDEMO_MSS2DSS_ADCBUFCFG, MmwDemo_mssCfgUpdate(), MmwDemo_message_t::subFrameNum, and MmwDemo_message_t::type.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLIAnalogMonitorCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for enabling analog monitors
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 1113 of file cli.c.
References MmwDemo_message_body_u::anaMonCfg, MmwDemo_CliCommonCfg_t_::anaMonCfg, MmwDemo_message_t::body, CLI_write(), MmwDemo_MCB_t::cliCommonCfg, MmwDemo_mboxWrite(), MMWDEMO_MSS2DSS_ANALOG_MONITOR, MmwDemo_AnaMonitorCfg_t::rxSatMonEn, MmwDemo_AnaMonitorCfg_t::sigImgMonEn, and MmwDemo_message_t::type.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLIBpmCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for BPM configuration supported by the mmw Demo Note that there is a generic BPM configuration command supported by utils/cli and mmwave. The generic BPM command is not supported by the demo as the mmw demo assumes a specific BPM pattern for the TX antennas.
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 934 of file cli.c.
References MmwDemo_message_t::body, MmwDemo_message_body_u::bpmCfg, MmwDemo_BpmCfg_t::chirp0Idx, MmwDemo_BpmCfg_t::chirp1Idx, CLI_write(), MmwDemo_BpmCfg_t::isEnabled, MmwDemo_CLIGetSubframe(), MmwDemo_mboxWrite(), MMWDEMO_MSS2DSS_BPM_CFG, MmwDemo_mssCfgUpdate(), MmwDemo_message_t::subFrameNum, and MmwDemo_message_t::type.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLICalibDcRangeSig (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for DC range calibration
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 493 of file cli.c.
References MmwDemo_message_t::body, MmwDemo_message_body_u::calibDcRangeSigCfg, CLI_write(), DC_RANGE_SIGNATURE_COMP_MAX_BIN_SIZE, MmwDemo_CalibDcRangeSigCfg_t::enabled, log2Approx(), MmwDemo_CLIGetSubframe(), MmwDemo_mboxWrite(), MMWDEMO_MSS2DSS_CALIB_DC_RANGE_SIG, MmwDemo_mssCfgUpdate(), MmwDemo_CalibDcRangeSigCfg_t::negativeBinIdx, MmwDemo_CalibDcRangeSigCfg_t::numAvgChirps, MmwDemo_CalibDcRangeSigCfg_t::positiveBinIdx, MmwDemo_message_t::subFrameNum, and MmwDemo_message_t::type.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLICfarCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for CFAR configuration
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 279 of file cli.c.
References MmwDemo_CfarCfg_t::averageMode, MmwDemo_message_t::body, MmwDemo_message_body_u::cfarCfg, MmwDemo_CfarCfg_t::cyclicMode, MmwDemo_CfarCfg_t::guardLen, MmwDemo_CLIGetSubframe(), MmwDemo_mboxWrite(), MMWDEMO_MSS2DSS_CFAR_DOPPLER_CFG, MMWDEMO_MSS2DSS_CFAR_RANGE_CFG, MmwDemo_mssCfgUpdate(), MmwDemo_CfarCfg_t::noiseDivShift, MmwDemo_message_t::subFrameNum, MmwDemo_CfarCfg_t::thresholdScale, MmwDemo_message_t::type, and MmwDemo_CfarCfg_t::winLen.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLIChirpQualityRxSatMonCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for configuring CQ RX Saturation monitor
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 991 of file cli.c.
References MmwDemo_message_t::body, CLI_write(), MmwDemo_MCB_t::cliCommonCfg, MmwDemo_message_body_u::cqSatMonCfg, MmwDemo_CliCommonCfg_t_::cqSatMonCfg, MmwDemo_mboxWrite(), MMWDEMO_MSS2DSS_CQ_SATURATION_MONITOR, and MmwDemo_message_t::type.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLIChirpQualitySigImgMonCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for configuring CQ Singal & Image band monitor
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 1053 of file cli.c.
References MmwDemo_message_t::body, CLI_write(), MmwDemo_MCB_t::cliCommonCfg, MmwDemo_message_body_u::cqSigImgMonCfg, MmwDemo_CliCommonCfg_t_::cqSigImgMonCfg, MmwDemo_mboxWrite(), MMWDEMO_MSS2DSS_CQ_SIGIMG_MONITOR, and MmwDemo_message_t::type.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLIClutterRemoval (int32_t argc, char * argv[]) static
Description
Clutter removal Configuration
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 665 of file cli.c.
References MmwDemo_message_t::body, MmwDemo_message_body_u::clutterRemovalCfg, MmwDemo_ClutterRemovalCfg_t::enabled, MmwDemo_CLIGetSubframe(), MmwDemo_mboxWrite(), MMWDEMO_MSS2DSS_CLUTTER_REMOVAL, MmwDemo_mssCfgUpdate(), MmwDemo_message_t::subFrameNum, and MmwDemo_message_t::type.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLICompRangeBiasAndRxChanPhaseCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for compensation of range bias and channel phase offsets
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 817 of file cli.c.
References MmwDemo_message_t::body, CLI_write(), MmwDemo_MCB_t::cliCommonCfg, MmwDemo_message_body_u::compRxChanCfg, MmwDemo_CliCommonCfg_t_::compRxChanCfg, cmplx16ImRe_t_::imag, MmwDemo_mboxWrite(), MMWDEMO_MSS2DSS_COMP_RANGE_BIAS_AND_RX_CHAN_PHASE, MMWDEMO_SATURATE_HIGH, MMWDEMO_SATURATE_LOW, MmwDemo_compRxChannelBiasCfg_t_::rangeBias, cmplx16ImRe_t_::real, MmwDemo_compRxChannelBiasCfg_t_::rxChPhaseComp, SYS_COMMON_NUM_RX_CHANNEL, SYS_COMMON_NUM_TX_ANTENNAS, and MmwDemo_message_t::type.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLIExtendedMaxVelocity (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for Velocity Disambiguation Configuration
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 563 of file cli.c.
References MmwDemo_message_t::body, MmwDemo_ExtendedMaxVelocityCfg_t::enabled, MmwDemo_message_body_u::extendedMaxVelocityCfg, MmwDemo_CLIGetSubframe(), MmwDemo_mboxWrite(), MMWDEMO_MSS2DSS_EXTENDED_MAX_VELOCITY, MmwDemo_mssCfgUpdate(), MmwDemo_message_t::subFrameNum, and MmwDemo_message_t::type.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLIGetSubframe (int32_t argc, char * argv[], int32_t expectedArgc, int8_t * subFrameNum) static
Definition at line 166 of file cli.c.
References CLI_write().
Referenced by MmwDemo_CLIADCBufCfg(), MmwDemo_CLIBpmCfg(), MmwDemo_CLICalibDcRangeSig(), MmwDemo_CLICfarCfg(), MmwDemo_CLIClutterRemoval(), MmwDemo_CLIExtendedMaxVelocity(), MmwDemo_CLIGuiMonSel(), MmwDemo_CLILvdsStreamCfg(), MmwDemo_CLIMultiObjBeamForming(), MmwDemo_CLINearFieldCorrection(), and MmwDemo_CLIPeakGroupingCfg().
static int32_t MmwDemo_CLIGuiMonSel (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for gui monitoring configuration
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 226 of file cli.c.
References MmwDemo_message_t::body, MmwDemo_GuiMonSel_t::detectedObjects, MmwDemo_message_body_u::guiMonSel, MmwDemo_GuiMonSel_t::logMagRange, MmwDemo_CLIGetSubframe(), MmwDemo_mboxWrite(), MMWDEMO_MSS2DSS_GUIMON_CFG, MmwDemo_mssCfgUpdate(), MmwDemo_GuiMonSel_t::noiseProfile, MmwDemo_GuiMonSel_t::rangeAzimuthHeatMap, MmwDemo_GuiMonSel_t::rangeDopplerHeatMap, MmwDemo_GuiMonSel_t::statsInfo, MmwDemo_message_t::subFrameNum, and MmwDemo_message_t::type.
Referenced by MmwDemo_CLIInit().
void MmwDemo_CLIInit (void)
Description
This is the CLI Execution Task
Return values
Not Applicable.
Definition at line 1206 of file cli.c.
References CLI_open(), MmwDemo_MCB_t::commandUartHandle, MmwDemo_MCB_t::ctrlHandle, MmwDemo_CLIADCBufCfg(), MmwDemo_CLIAnalogMonitorCfg(), MmwDemo_CLIBpmCfg(), MmwDemo_CLICalibDcRangeSig(), MmwDemo_CLICfarCfg(), MmwDemo_CLIChirpQualityRxSatMonCfg(), MmwDemo_CLIChirpQualitySigImgMonCfg(), MmwDemo_CLIClutterRemoval(), MmwDemo_CLICompRangeBiasAndRxChanPhaseCfg(), MmwDemo_CLIExtendedMaxVelocity(), MmwDemo_CLIGuiMonSel(), MmwDemo_CLILvdsStreamCfg(), MmwDemo_CLIMeasureRangeBiasAndRxChanPhaseCfg(), MmwDemo_CLIMultiObjBeamForming(), MmwDemo_CLINearFieldCorrection(), MmwDemo_CLIPeakGroupingCfg(), MmwDemo_CLISensorStart(), MmwDemo_CLISensorStop(), and MmwDemo_CLISetDataLogger().
Referenced by MmwDemo_mssInitTask().
static int32_t MmwDemo_CLILvdsStreamCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for the High Speed Interface
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 1157 of file cli.c.
References MmwDemo_message_t::body, CLI_write(), MmwDemo_LvdsStreamCfg_t::dataFmt, MmwDemo_LvdsStreamCfg_t::isHeaderEnabled, MmwDemo_LvdsStreamCfg_t::isSwEnabled, MmwDemo_message_body_u::lvdsStreamCfg, MmwDemo_CLIGetSubframe(), MmwDemo_mboxWrite(), MMWDEMO_MSS2DSS_LVDSSTREAM_CFG, MmwDemo_mssCfgUpdate(), MmwDemo_message_t::subFrameNum, and MmwDemo_message_t::type.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLIMeasureRangeBiasAndRxChanPhaseCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for measurement configuration of range bias and channel phase offsets
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 882 of file cli.c.
References MmwDemo_message_t::body, CLI_write(), MmwDemo_MCB_t::cliCommonCfg, MmwDemo_measureRxChannelBiasCfg_t_::enabled, MmwDemo_message_body_u::measureRxChanCfg, MmwDemo_CliCommonCfg_t_::measureRxChanCfg, MmwDemo_mboxWrite(), MMWDEMO_MSS2DSS_MEASURE_RANGE_BIAS_AND_RX_CHAN_PHASE, MmwDemo_measureRxChannelBiasCfg_t_::searchWinSize, MmwDemo_measureRxChannelBiasCfg_t_::targetDistance, and MmwDemo_message_t::type.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLIMultiObjBeamForming (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for multi object beam forming configuration
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 415 of file cli.c.
References MmwDemo_message_t::body, MmwDemo_MultiObjBeamFormingCfg_t::enabled, MmwDemo_CLIGetSubframe(), MmwDemo_mboxWrite(), MMWDEMO_MSS2DSS_MULTI_OBJ_BEAM_FORM, MmwDemo_mssCfgUpdate(), MmwDemo_message_body_u::multiObjBeamFormingCfg, MmwDemo_MultiObjBeamFormingCfg_t::multiPeakThrsScal, MmwDemo_message_t::subFrameNum, and MmwDemo_message_t::type.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLINearFieldCorrection (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for Near field correction Configuration
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 613 of file cli.c.
References MmwDemo_message_t::body, MmwDemo_NearFieldCorrectionCfg_t::enabled, MmwDemo_NearFieldCorrectionCfg_t::endRangeIdx, MmwDemo_CLIGetSubframe(), MmwDemo_mboxWrite(), MMWDEMO_MSS2DSS_NEAR_FIELD_CFG, MmwDemo_mssCfgUpdate(), MmwDemo_message_body_u::nearFieldCorrectionCfg, MmwDemo_NearFieldCorrectionCfg_t::startRangeIdx, MmwDemo_message_t::subFrameNum, and MmwDemo_message_t::type.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLIPeakGroupingCfg (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for Peak grouping configuration
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 355 of file cli.c.
References MmwDemo_message_t::body, CLI_write(), MmwDemo_PeakGroupingCfg_t::inDopplerDirectionEn, MmwDemo_PeakGroupingCfg_t::inRangeDirectionEn, MmwDemo_PeakGroupingCfg_t::maxRangeIndex, MmwDemo_PeakGroupingCfg_t::minRangeIndex, MmwDemo_CLIGetSubframe(), MmwDemo_mboxWrite(), MMWDEMO_MSS2DSS_PEAK_GROUPING_CFG, MmwDemo_mssCfgUpdate(), MmwDemo_message_body_u::peakGroupingCfg, MmwDemo_PeakGroupingCfg_t::scheme, MmwDemo_message_t::subFrameNum, and MmwDemo_message_t::type.
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLISensorStart (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for the sensor start command
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 128 of file cli.c.
References MmwDemo_notifySensorStart(), and MmwDemo_waitSensorStartComplete().
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLISensorStop (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for the sensor stop command
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 157 of file cli.c.
References MmwDemo_notifySensorStop(), and MmwDemo_waitSensorStopComplete().
Referenced by MmwDemo_CLIInit().
static int32_t MmwDemo_CLISetDataLogger (int32_t argc, char * argv[]) static
Description
This is the CLI Handler for data logger set command
Parameters
[in] argc Number of arguments
[in] argv Arguments
Return values
Success - 0
Error - <0
Definition at line 715 of file cli.c.
References MmwDemo_message_t::body, MmwDemo_MCB_t::cfg, CLI_write(), MmwDemo_message_body_u::dataLogger, MmwDemo_Cfg_t::dataLogger, MmwDemo_mboxWrite(), MMWDEMO_MSS2DSS_SET_DATALOGGER, and MmwDemo_message_t::type.
Referenced by MmwDemo_CLIInit().
int32_t MmwDemo_mboxWrite (MmwDemo_message * message)
Description
Function to send a message to peer through Mailbox virtural channel
Parameters
[in] message Pointer to the MMW demo message.
Return values
Success - 0 Fail < -1
Definition at line 1308 of file mss_main.c.
References MmwDemo_MCB_t::peerMailbox.
Referenced by MmwDemo_CLIADCBufCfg(), MmwDemo_CLIAnalogMonitorCfg(), MmwDemo_CLIBpmCfg(), MmwDemo_CLICalibDcRangeSig(), MmwDemo_CLICfarCfg(), MmwDemo_CLIChirpQualityRxSatMonCfg(), MmwDemo_CLIChirpQualitySigImgMonCfg(), MmwDemo_CLIClutterRemoval(), MmwDemo_CLICompRangeBiasAndRxChanPhaseCfg(), MmwDemo_CLIExtendedMaxVelocity(), MmwDemo_CLIGuiMonSel(), MmwDemo_CLILvdsStreamCfg(), MmwDemo_CLIMeasureRangeBiasAndRxChanPhaseCfg(), MmwDemo_CLIMultiObjBeamForming(), MmwDemo_CLINearFieldCorrection(), MmwDemo_CLIPeakGroupingCfg(), MmwDemo_CLISetDataLogger(), and MmwDemo_mboxReadTask().
static void MmwDemo_mssCfgUpdate (void * srcPtr, uint32_t offset, uint32_t size, int8_t subFrameNum) static
Definition at line 191 of file cli.c.
References MmwDemo_MCB_t::cliCfg, and MMWDEMO_SUBFRAME_NUM_FRAME_LEVEL_CONFIG.
Referenced by MmwDemo_CLIADCBufCfg(), MmwDemo_CLIBpmCfg(), MmwDemo_CLICalibDcRangeSig(), MmwDemo_CLICfarCfg(), MmwDemo_CLIClutterRemoval(), MmwDemo_CLIExtendedMaxVelocity(), MmwDemo_CLIGuiMonSel(), MmwDemo_CLILvdsStreamCfg(), MmwDemo_CLIMultiObjBeamForming(), MmwDemo_CLINearFieldCorrection(), and MmwDemo_CLIPeakGroupingCfg().
Variable Documentation
MmwDemo_MCB gMmwMssMCB
Global Variable for tracking information required by the mmw Demo.
Definition at line 1034 of file mss_main.c.
Copyright 2018, Texas Instruments Incorporated