xwr16xx/mmw/dss/dss_data_path.c File Reference
dss_data_path.c File Reference
Implements Data path processing functionality.
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <xdc/std.h>
#include <xdc/cfg/global.h>
#include <xdc/runtime/IHeap.h>
#include <xdc/runtime/System.h>
#include <xdc/runtime/Error.h>
#include <xdc/runtime/Memory.h>
#include <ti/sysbios/BIOS.h>
#include <ti/sysbios/knl/Task.h>
#include <ti/sysbios/knl/Event.h>
#include <ti/sysbios/knl/Semaphore.h>
#include <ti/sysbios/knl/Clock.h>
#include <ti/sysbios/heaps/HeapBuf.h>
#include <ti/sysbios/heaps/HeapMem.h>
#include <ti/sysbios/family/c64p/Hwi.h>
#include <ti/sysbios/family/c64p/EventCombiner.h>
#include <ti/drivers/osal/DebugP.h>
#include <assert.h>
#include <ti/common/sys_common.h>
#include <ti/drivers/osal/SemaphoreP.h>
#include <ti/drivers/edma/edma.h>
#include <ti/drivers/esm/esm.h>
#include <ti/drivers/soc/soc.h>
#include <ti/utils/cycleprofiler/cycle_profiler.h>
#include <ti/alg/mmwavelib/mmwavelib.h>
#include "DSP_fft32x32.h"
#include "DSP_fft16x16.h"
#include <ti/mathlib/mathlib.h>
#include "dss_mmw.h"
#include "dss_data_path.h"
#include "dss_config_edma_util.h"
#include "dss_resources.h"
#include <ti/demo/utils/rx_ch_bias_measure.h>
Macros
#define DebugP_ASSERT_ENABLED 1
#define MMW_ADCBUF_SIZE 0x4000U
#define MMW_L2_HEAP_SIZE 0xC000U
L2 heap used for allocating buffers in L2 SRAM, mostly scratch buffers.
#define MMW_L1_HEAP_SIZE 0x4000U
L1 heap used for allocating buffers in L1D SRAM, mostly scratch buffers.
#define FFT_WINDOW_INT16 0
#define FFT_WINDOW_INT32 1
#define MMW_WIN_HANNING 0
#define MMW_WIN_BLACKMAN 1
#define MMW_WIN_RECT 2
#define MMW_USE_SINGLE_POINT_DFT
#define MMW_EDMA_TRIGGER_ENABLE 1
#define MMW_EDMA_TRIGGER_DISABLE 0
#define ONE_QFORMAT (1 << xyzOutputQFormat)
#define ONE_QFORMAT (1 << xyzOutputQFormat)
#define WRAP_DOPPLER_IDX(_x) ((_x) & (numDopplerBins-1))
#define WRAP_DWN_LIST_IDX(_x) ((_x) >= numDetectedObjects ? ((_x) - numDetectedObjects) : (_x))
#define WRAP_UP_LIST_IDX(_x) ((_x) < 0 ? ((_x) + numDetectedObjects) : (_x))
#define pingPongId(x) ((x) & 0x1U)
#define isPong(x) (pingPongId(x))
#define MMWDEMO_XWR16XX_EVM_77GHZ_LAMBDA (3.8961)
#define MMWDEMO_NEAR_FIELD_A (0)
#define MMWDEMO_NEAR_FIELD_B (MMWDEMO_XWR16XX_EVM_77GHZ_LAMBDA)
#define MMWDEMO_NEAR_FIELD_C (2 * MMWDEMO_XWR16XX_EVM_77GHZ_LAMBDA)
#define MMWDEMO_NEAR_FIELD_D (MMWDEMO_NEAR_FIELD_C + 8.7)
#define MMWDEMO_NEAR_FIELD_E (MMWDEMO_NEAR_FIELD_D + 1.5 * MMWDEMO_XWR16XX_EVM_77GHZ_LAMBDA)
#define MMWDEMO_NEAR_FIELD_AB2 (2.0 * (MMWDEMO_NEAR_FIELD_A - MMWDEMO_NEAR_FIELD_B))
#define MMWDEMO_NEAR_FIELD_CB2 (2.0 * (MMWDEMO_NEAR_FIELD_C - MMWDEMO_NEAR_FIELD_B))
#define MMWDEMO_NEAR_FIELD_DB2 (2.0 * (MMWDEMO_NEAR_FIELD_D - MMWDEMO_NEAR_FIELD_B))
#define MMWDEMO_NEAR_FIELD_EB2 (2.0 * (MMWDEMO_NEAR_FIELD_E - MMWDEMO_NEAR_FIELD_B))
#define MMWDEMO_NEAR_FIELD_AB_SQ ((MMWDEMO_NEAR_FIELD_A - MMWDEMO_NEAR_FIELD_B) * (MMWDEMO_NEAR_FIELD_A - MMWDEMO_NEAR_FIELD_B))
#define MMWDEMO_NEAR_FIELD_CB_SQ ((MMWDEMO_NEAR_FIELD_C - MMWDEMO_NEAR_FIELD_B) * (MMWDEMO_NEAR_FIELD_C - MMWDEMO_NEAR_FIELD_B))
#define MMWDEMO_NEAR_FIELD_DB_SQ ((MMWDEMO_NEAR_FIELD_D - MMWDEMO_NEAR_FIELD_B) * (MMWDEMO_NEAR_FIELD_D - MMWDEMO_NEAR_FIELD_B))
#define MMWDEMO_NEAR_FIELD_EB_SQ ((MMWDEMO_NEAR_FIELD_E - MMWDEMO_NEAR_FIELD_B) * (MMWDEMO_NEAR_FIELD_E - MMWDEMO_NEAR_FIELD_B))
#define MMWDEMO_TWO_PI_OVER_LAMBDA (2. * PI_ / MMWDEMO_XWR16XX_EVM_77GHZ_LAMBDA)
#define SOC_MAX_NUM_RX_ANTENNAS SYS_COMMON_NUM_RX_CHANNEL
#define SOC_MAX_NUM_TX_ANTENNAS SYS_COMMON_NUM_TX_ANTENNAS
#define ALIGN(x, a) (((x)+((a)-1))&~((a)-1))
#define MMW_ALLOC_BUF(name, nameType, startAddr, alignment, size)
Functions
int32_t MmwDemo_gen_twiddle_fft32x32_fast (int32_t *w, int32_t n, double scale)
int32_t MmwDemo_gen_twiddle_fft16x16_fast (short *w, int32_t n)
void MmwDemo_genWindow (void *win, uint32_t windowDatumType, uint32_t winLen, uint32_t winGenLen, int32_t oneQformat, uint32_t winType)
void MmwDemo_resetDopplerLines (MmwDemo_1D_DopplerLines_t *ths)
void MmwDemo_setDopplerLine (MmwDemo_1D_DopplerLines_t *ths, uint16_t dopplerIndex)
uint32_t MmwDemo_isSetDopplerLine (MmwDemo_1D_DopplerLines_t *ths, uint16_t index)
int32_t MmwDemo_getDopplerLine (MmwDemo_1D_DopplerLines_t *ths)
uint32_t MmwDemo_pow2roundup (uint32_t x)
void MmwDemo_XYcalc (MmwDemo_DSS_DataPathObj *obj, uint32_t objIndex, uint16_t azimIdx, float maxVal)
void MmwDemo_XYestimation (MmwDemo_DSS_DataPathObj *obj, uint32_t objIndex)
void MmwDemo_Yestimation (MmwDemo_DSS_DataPathObj *obj, uint32_t objIndex)
void MmwDemo_dataPathWait1DInputData (MmwDemo_DSS_DataPathObj *obj, uint32_t pingPongId)
void MmwDemo_dataPathWait1DOutputData (MmwDemo_DSS_DataPathObj *obj, uint32_t pingPongId)
void MmwDemo_dataPathWait2DInputData (MmwDemo_DSS_DataPathObj *obj, uint32_t pingPongId)
void MmwDemo_dataPathWait3DInputData (MmwDemo_DSS_DataPathObj *obj, uint32_t pingPongId)
void MmwDemo_dataPathWaitTransDetMatrix (MmwDemo_DSS_DataPathObj *obj)
void MmwDemo_dataPathWaitTransDetMatrix2 (MmwDemo_DSS_DataPathObj *obj)
void MmwDemo_EDMA_CQTransferCompletionCallbackFxn (uintptr_t arg, uint8_t transferCompletionCode)
int32_t MmwDemo_dataPathConfigCQEdma (MmwDemo_DSS_DataPathObj *obj)
void MmwDemo_dssDataPathStartCQEdma (MmwDemo_DSS_DataPathObj *ptrDataPathObj)
int32_t MmwDemo_dataPathConfigEdma (MmwDemo_DSS_DataPathObj *obj)
uint32_t MmwDemo_cfarPeakGrouping (MmwDemo_detectedObj *objOut, MmwDemo_objRaw_t *objRaw, uint32_t numDetectedObjects, uint16_t *detMatrix, uint32_t numDopplerBins, uint32_t maxRangeIdx, uint32_t minRangeIdx, uint32_t groupInDopplerDirection, uint32_t groupInRangeDirection)
uint32_t MmwDemo_cfarPeakGroupingCfarQualified (MmwDemo_detectedObj *objOut, MmwDemo_objRaw_t *objRaw, uint32_t numDetectedObjects, uint32_t numDopplerBins, uint32_t maxRangeIdx, uint32_t minRangeIdx, uint32_t groupInDopplerDirection, uint32_t groupInRangeDirection)
void MmwDemo_magnitudeSquared (cmplx32ReIm_t *restrict inpBuff, float *restrict magSqrdBuff, uint32_t numSamples)
void MmwDemo_dcRangeSignatureCompensation (MmwDemo_DSS_DataPathObj *obj, uint8_t chirpPingPongId)
void MmwDemo_interChirpProcessing (MmwDemo_DSS_DataPathObj *obj, uint8_t chirpPingPongId)
void MmwDemo_addDopplerCompensation (int32_t dopplerIdx, int32_t numDopplerBins, uint32_t *azimuthModCoefs, uint32_t *azimuthModCoefsHalfBin, int64_t *azimuthIn, uint32_t numAnt)
Function Name : MmwDemo_DopplerCompensation.
static void MmwDemo_rxChanPhaseBiasCompensation (uint32_t *rxChComp, int64_t *input, uint32_t numAnt)
Function Name : MmwDemo_rxChanPhaseBiasCompensation.
void MmwDemo_decodeBPM (cmplx32ReIm_t *azimuthIn, uint32_t numRxAnt)
void MmwDemo_log2AbsAccum (MmwDemo_DSS_DataPathObj *obj, int32_t rxAntIdx, uint32_t rangeIdx, uint32_t *waitingTime, uint32_t fftOutIndx)
void MmwDemo_nearFieldCorrection (MmwDemo_DSS_DataPathObj *obj, uint32_t detIdx2)
void MmwDemo_interFrameProcessing (MmwDemo_DSS_DataPathObj *obj)
void MmwDemo_processChirp (MmwDemo_DSS_DataPathObj *obj, uint16_t chirpIndxInMultiChirp)
void MmwDemo_waitEndOfChirps (MmwDemo_DSS_DataPathObj *obj)
void MmwDemo_genDftSinCosTable (cmplx16ImRe_t *dftSinCosTable, cmplx16ImRe_t *dftHalfBinVal, uint32_t dftLen)
void MmwDemo_edmaErrorCallbackFxn (EDMA_Handle handle, EDMA_errorInfo_t *errorInfo)
void MmwDemo_edmaTransferControllerErrorCallbackFxn (EDMA_Handle handle, EDMA_transferControllerErrorInfo_t *errorInfo)
void MmwDemo_dataPathObjInit (MmwDemo_DSS_DataPathObj *obj, MmwDemo_DSS_dataPathContext_t *context, MmwDemo_CliCfg_t *cliCfg, MmwDemo_CliCommonCfg_t *cliCommonCfg, MmwDemo_Cfg *cfg)
void MmwDemo_dataPathInit1Dstate (MmwDemo_DSS_DataPathObj *obj)
void MmwDemo_dataPathDeleteSemaphore (MmwDemo_DSS_dataPathContext_t *context)
int32_t MmwDemo_dataPathInitEdma (MmwDemo_DSS_dataPathContext_t *context)
void MmwDemo_printHeapStats (char *name, uint32_t heapUsed, uint32_t heapSize)
void MmwDemo_dataPathComputeDerivedConfig (MmwDemo_DSS_DataPathObj *obj)
void MmwDemo_dataPathConfigBuffers (MmwDemo_DSS_DataPathObj *obj, uint32_t adcBufAddress)
void MmwDemo_dataPathConfigFFTs (MmwDemo_DSS_DataPathObj *obj)
void MmwDemo_checkDynamicConfigErrors (MmwDemo_DSS_DataPathObj *obj)
Variables
const int32_t twiddleTableCommon [2 *256]
Lookup table for Twiddle table generation and DFT single bin DFT calculation. It contains 256 complex exponentials e(k) = cos(2*pi*k/1024)+j*sin(2*pi*k/1024), k=0,...,255, Imaginary values are in even, and real values are in odd locations. Values are in Q31 format, saturated to +/- 2147483647.
uint8_t gMmwL3 [SOC_XWR16XX_DSS_L3RAM_SIZE]
uint8_t gMmwL2 [MMW_L2_HEAP_SIZE]
uint8_t gMmwL1 [MMW_L1_HEAP_SIZE]
volatile cycleLog_t gCycleLog
Detailed Description
Implements Data path processing functionality.
NOTE: (C) Copyright 2016 Texas Instruments, Inc.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Texas Instruments Incorporated nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file dss_data_path.c.
Macro Definition Documentation
#define ALIGN (x, a) (((x)+((a)-1))&~((a)-1))
Referenced by MmwDemo_dataPathConfigBuffers().
#define DebugP_ASSERT_ENABLED 1
Definition at line 71 of file dss_data_path.c.
#define FFT_WINDOW_INT16 0
Types of FFT window
FFT window 16 - samples format is int16_t
Definition at line 448 of file dss_data_path.c.
Referenced by MmwDemo_dataPathConfigFFTs(), and MmwDemo_genWindow().
#define FFT_WINDOW_INT32 1
FFT window 32 - samples format is int32_t
Definition at line 450 of file dss_data_path.c.
Referenced by MmwDemo_dataPathConfigFFTs(), and MmwDemo_genWindow().
#define isPong (x) (pingPongId(x))
Definition at line 2056 of file dss_data_path.c.
Referenced by MmwDemo_interChirpProcessing(), MmwDemo_interFrameProcessing(), and MmwDemo_processChirp().
#define MMW_ADCBUF_SIZE 0x4000U
Definition at line 421 of file dss_data_path.c.
#define MMW_ALLOC_BUF (name, nameType, startAddr, alignment, size)
Value:
obj->name = (nameType *) ALIGN(startAddr, alignment); \
        uint32_t name##_end = (uint32_t)obj->name + (size) * sizeof(nameType);
Referenced by MmwDemo_dataPathConfigBuffers().
#define MMW_EDMA_TRIGGER_DISABLE 0
Definition at line 474 of file dss_data_path.c.
Referenced by MmwDemo_interFrameProcessing().
#define MMW_EDMA_TRIGGER_ENABLE 1
Definition at line 473 of file dss_data_path.c.
Referenced by MmwDemo_interFrameProcessing().
#define MMW_L1_HEAP_SIZE 0x4000U
L1 heap used for allocating buffers in L1D SRAM, mostly scratch buffers.
Definition at line 429 of file dss_data_path.c.
Referenced by MmwDemo_dataPathConfigBuffers().
#define MMW_L2_HEAP_SIZE 0xC000U
L2 heap used for allocating buffers in L2 SRAM, mostly scratch buffers.
Definition at line 425 of file dss_data_path.c.
Referenced by MmwDemo_dataPathConfigBuffers().
#define MMW_USE_SINGLE_POINT_DFT
If MMW_USE_SINGLE_POINT_DFT is defined azimuth calculation uses single point DFT, otherwise FFT function from DSP lib
Definition at line 462 of file dss_data_path.c.
#define MMW_WIN_BLACKMAN 1
Blackman window
Definition at line 456 of file dss_data_path.c.
Referenced by MmwDemo_dataPathConfigFFTs(), and MmwDemo_genWindow().
#define MMW_WIN_HANNING 0
Hanning window
Definition at line 454 of file dss_data_path.c.
Referenced by MmwDemo_dataPathConfigFFTs(), and MmwDemo_genWindow().
#define MMW_WIN_RECT 2
Rectangular window
Definition at line 458 of file dss_data_path.c.
Referenced by MmwDemo_genWindow().
#define MMWDEMO_NEAR_FIELD_A (0)
#define MMWDEMO_NEAR_FIELD_AB2 (2.0 * (MMWDEMO_NEAR_FIELD_A - MMWDEMO_NEAR_FIELD_B))
Referenced by MmwDemo_nearFieldCorrection().
#define MMWDEMO_NEAR_FIELD_AB_SQ ((MMWDEMO_NEAR_FIELD_A - MMWDEMO_NEAR_FIELD_B) * (MMWDEMO_NEAR_FIELD_A - MMWDEMO_NEAR_FIELD_B))
Referenced by MmwDemo_nearFieldCorrection().
#define MMWDEMO_NEAR_FIELD_B (MMWDEMO_XWR16XX_EVM_77GHZ_LAMBDA)
#define MMWDEMO_NEAR_FIELD_C (2 * MMWDEMO_XWR16XX_EVM_77GHZ_LAMBDA)
#define MMWDEMO_NEAR_FIELD_CB2 (2.0 * (MMWDEMO_NEAR_FIELD_C - MMWDEMO_NEAR_FIELD_B))
Referenced by MmwDemo_nearFieldCorrection().
#define MMWDEMO_NEAR_FIELD_CB_SQ ((MMWDEMO_NEAR_FIELD_C - MMWDEMO_NEAR_FIELD_B) * (MMWDEMO_NEAR_FIELD_C - MMWDEMO_NEAR_FIELD_B))
Referenced by MmwDemo_nearFieldCorrection().
#define MMWDEMO_NEAR_FIELD_D (MMWDEMO_NEAR_FIELD_C + 8.7)
#define MMWDEMO_NEAR_FIELD_DB2 (2.0 * (MMWDEMO_NEAR_FIELD_D - MMWDEMO_NEAR_FIELD_B))
Referenced by MmwDemo_nearFieldCorrection().
#define MMWDEMO_NEAR_FIELD_DB_SQ ((MMWDEMO_NEAR_FIELD_D - MMWDEMO_NEAR_FIELD_B) * (MMWDEMO_NEAR_FIELD_D - MMWDEMO_NEAR_FIELD_B))
Referenced by MmwDemo_nearFieldCorrection().
#define MMWDEMO_NEAR_FIELD_E (MMWDEMO_NEAR_FIELD_D + 1.5 * MMWDEMO_XWR16XX_EVM_77GHZ_LAMBDA)
#define MMWDEMO_NEAR_FIELD_EB2 (2.0 * (MMWDEMO_NEAR_FIELD_E - MMWDEMO_NEAR_FIELD_B))
Referenced by MmwDemo_nearFieldCorrection().
#define MMWDEMO_NEAR_FIELD_EB_SQ ((MMWDEMO_NEAR_FIELD_E - MMWDEMO_NEAR_FIELD_B) * (MMWDEMO_NEAR_FIELD_E - MMWDEMO_NEAR_FIELD_B))
Referenced by MmwDemo_nearFieldCorrection().
#define MMWDEMO_TWO_PI_OVER_LAMBDA (2. * PI_ / MMWDEMO_XWR16XX_EVM_77GHZ_LAMBDA)
Referenced by MmwDemo_nearFieldCorrection().
#define MMWDEMO_XWR16XX_EVM_77GHZ_LAMBDA (3.8961)
#define ONE_QFORMAT (1 << xyzOutputQFormat)
Referenced by MmwDemo_XYcalc(), and MmwDemo_Yestimation().
#define ONE_QFORMAT (1 << xyzOutputQFormat)
#define pingPongId (x) ((x) & 0x1U)
Definition at line 2055 of file dss_data_path.c.
Referenced by MmwDemo_interChirpProcessing(), MmwDemo_interFrameProcessing(), and MmwDemo_processChirp().
#define SOC_MAX_NUM_RX_ANTENNAS SYS_COMMON_NUM_RX_CHANNEL
Definition at line 3481 of file dss_data_path.c.
Referenced by MmwDemo_dataPathConfigBuffers().
#define SOC_MAX_NUM_TX_ANTENNAS SYS_COMMON_NUM_TX_ANTENNAS
Definition at line 3482 of file dss_data_path.c.
Referenced by MmwDemo_dataPathConfigBuffers().
#define WRAP_DOPPLER_IDX (_x) ((_x) & (numDopplerBins-1))
Referenced by MmwDemo_cfarPeakGroupingCfarQualified().
#define WRAP_DWN_LIST_IDX (_x) ((_x) >= numDetectedObjects ? ((_x) - numDetectedObjects) : (_x))
Referenced by MmwDemo_cfarPeakGroupingCfarQualified().
#define WRAP_UP_LIST_IDX (_x) ((_x) < 0 ? ((_x) + numDetectedObjects) : (_x))
Referenced by MmwDemo_cfarPeakGroupingCfarQualified().
Function Documentation
void MmwDemo_addDopplerCompensation (int32_t dopplerIdx, int32_t numDopplerBins, uint32_t * azimuthModCoefs, uint32_t * azimuthModCoefsHalfBin, int64_t * azimuthIn, uint32_t numAnt)
Function Name : MmwDemo_DopplerCompensation.
Description : Compensation of Doppler phase shift in the virtual antennas, (corresponding to second Tx antenna chirps). Symbols corresponding to virtual antennas, are rotated by half of the Doppler phase shift measured by Doppler FFT. The phase shift read from the table using half of the object Doppler index value. If the Doppler index is odd, an extra half of the bin phase shift is added.
Parameters
[in] dopplerIdx : Doppler index of the object
[in] numDopplerBins : Number of Doppler bins
[in] azimuthModCoefs Table with cos/sin values SIN in even position, COS in odd position exp(1j*2*pi*k/N) for k=0,...,N-1 where N is number of Doppler bins.
[out] azimuthModCoefsHalfBin : exp(1j*2*pi* 0.5 /N)
[in,out] azimuthIn :Pointer to antenna symbols to be Doppler compensated
[in] numAnt : Number of antenna symbols to be Doppler compensated
Returns
void
Definition at line 2279 of file dss_data_path.c.
Referenced by MmwDemo_interFrameProcessing().
uint32_t MmwDemo_cfarPeakGrouping (MmwDemo_detectedObj * objOut, MmwDemo_objRaw_t * objRaw, uint32_t numDetectedObjects, uint16_t * detMatrix, uint32_t numDopplerBins, uint32_t maxRangeIdx, uint32_t minRangeIdx, uint32_t groupInDopplerDirection, uint32_t groupInRangeDirection)
Description
The function groups neighboring peaks into one. The grouping is done according to two input flags: groupInDopplerDirection and groupInDopplerDirection. For each detected peak the function checks if the peak is greater than its neighbors. If this is true, the peak is copied to the output list of detected objects. The neighboring peaks that are used for checking are taken from the detection matrix and copied into 3x3 kernel regardless of whether they are CFAR detected or not. Note: Function always reads 9 samples per detected object from L3 memory into local array tempBuff, but it only needs to read according to input flags. For example if only the groupInDopplerDirection flag is set, it only needs to read middle row of the kernel, i.e. 3 samples per target from detection matrix.
Parameters
[out] objOut Output array of detected objects after peak grouping
[in] objRaw Array of detected objects after CFAR detection
[in] numDetectedObjects Number of detected objects by CFAR
[in] detMatrix Detection Range/Doppler matrix
[in] numDopplerBins Number of Doppler bins
[in] maxRangeIdx Maximum range limit
[in] minRangeIdx Minimum range limit
[in] groupInDopplerDirection Flag enables grouping in Doppler directiuon
[in] groupInRangeDirection Flag enables grouping in Range directiuon
Return values
Number of detected objects after grouping
Definition at line 1710 of file dss_data_path.c.
References DOPPLER_IDX_TO_SIGNED, MmwDemo_objRaw::dopplerIdx, MIN, MMW_MAX_OBJ_OUT, MmwDemo_objRaw::peakVal, and MmwDemo_objRaw::rangeIdx.
Referenced by MmwDemo_interFrameProcessing().
uint32_t MmwDemo_cfarPeakGroupingCfarQualified (MmwDemo_detectedObj * objOut, MmwDemo_objRaw_t * objRaw, uint32_t numDetectedObjects, uint32_t numDopplerBins, uint32_t maxRangeIdx, uint32_t minRangeIdx, uint32_t groupInDopplerDirection, uint32_t groupInRangeDirection)
Description
The function groups neighboring peaks into one. The grouping is done according to two input flags: groupInDopplerDirection and groupInDopplerDirection. For each detected peak the function checks if the peak is greater than its neighbors. If this is true, the peak is copied to the output list of detected objects. The neighboring peaks that are used for checking are taken from the list of CFAR detected objects, (not from the detection matrix), and copied into 3x3 kernel that has been initialized to zero for each peak under test. If the neighboring cell has not been detected by CFAR, its peak value is not copied into the kernel. Note: Function always search for 8 peaks in the list, but it only needs to search according to input flags.
Parameters
[out] objOut Output array of detected objects after peak grouping
[in] objRaw Array of detected objects after CFAR detection
[in] numDetectedObjects Number of detected objects by CFAR
[in] numDopplerBins Number of Doppler bins
[in] maxRangeIdx Maximum range limit
[in] minRangeIdx Minimum range limit
[in] groupInDopplerDirection Flag enables grouping in Doppler directiuon
[in] groupInRangeDirection Flag enables grouping in Range directiuon
Return values
Number of detected objects after grouping
Definition at line 1865 of file dss_data_path.c.
References DOPPLER_IDX_TO_SIGNED, MmwDemo_objRaw::dopplerIdx, MIN, MMW_MAX_OBJ_OUT, MmwDemo_objRaw::peakVal, MmwDemo_objRaw::rangeIdx, WRAP_DOPPLER_IDX, WRAP_DWN_LIST_IDX, and WRAP_UP_LIST_IDX.
Referenced by MmwDemo_interFrameProcessing().
void MmwDemo_checkDynamicConfigErrors (MmwDemo_DSS_DataPathObj * obj)
Description
Perform error checking for configurations that can change dynamically after start sensor has been issued e.g multi object, peakGrouping etc Ideally these checks should be done when the configuration commands are issued but this blows up code size because for each command there needs to be checking with current state related to other commands. So doing it in run-time (real-time) is cheaper with some expenditure of cycles to do the checks. If there is error exception message will be generated.
Return values
None
Definition at line 3947 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::cliCfg, MmwDemo_MultiObjBeamFormingCfg_t::enabled, MmwDemo_ExtendedMaxVelocityCfg_t::enabled, MmwDemo_NearFieldCorrectionCfg_t::enabled, MmwDemo_CliCfg_t_::extendedMaxVelocityCfg, MmwDemo_dssAssert, MmwDemo_CliCfg_t_::multiObjBeamFormingCfg, MmwDemo_CliCfg_t_::nearFieldCorrectionCfg, and MmwDemo_DSS_DataPathObj_t::numTxAntennas.
Referenced by MmwDemo_mboxReadTask().
void MmwDemo_dataPathComputeDerivedConfig (MmwDemo_DSS_DataPathObj * obj)
Description
Configures azimuth heat map related processing.
Return values
Not Applicable.
Definition at line 3484 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::log2NumDopplerBins, MmwDemo_dssAssert, MmwDemo_floorLog2(), and MmwDemo_DSS_DataPathObj_t::numDopplerBins.
Referenced by MmwDemo_dssDataPathConfig().
void MmwDemo_dataPathConfigBuffers (MmwDemo_DSS_DataPathObj * obj, uint32_t adcBufAddress)
Description
Creates heap in L2 and L3 and allocates data path buffers, The heap is destroyed at the end of the function.
Return values
Not Applicable.
Definition at line 3496 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::ADCdataBuf, MmwDemo_DSS_DataPathObj_t::adcDataIn, ALIGN, MmwDemo_CliCfg_t_::bpmCfg, MmwDemo_DSS_DataPathObj_t::cliCfg, DC_RANGE_SIGNATURE_COMP_MAX_BIN_SIZE, MmwDemo_DSS_DataPathObj_t::detDopplerLines, MmwDemo_1D_DopplerLines::dopplerLineMask, MmwDemo_1D_DopplerLines::dopplerLineMaskLen, gMmwL1, gMmwL2, gMmwL3, MmwDemo_BpmCfg_t::isEnabled, MAX, MAX_DET_OBJECTS_RAW, MMW_ALLOC_BUF, MMW_L1_HEAP_SIZE, MMW_L2_HEAP_SIZE, MMW_MAX_OBJ_OUT, MmwDemo_dssAssert, MMWDEMO_MEMORY_ALLOC_DOUBLE_WORD_ALIGN, MMWDEMO_MEMORY_ALLOC_MAX_STRUCT_ALIGN, MmwDemo_printHeapStats(), MmwDemo_DSS_DataPathObj_t::numAdcSamples, MmwDemo_DSS_DataPathObj_t::numAngleBins, MmwDemo_DSS_DataPathObj_t::numDopplerBins, MmwDemo_DSS_DataPathObj_t::numRangeBins, MmwDemo_DSS_DataPathObj_t::numRxAntennas, MmwDemo_DSS_DataPathObj_t::numTxAntennas, MmwDemo_DSS_DataPathObj_t::numVirtualAntAzim, SOC_MAX_NUM_RX_ANTENNAS, SOC_MAX_NUM_TX_ANTENNAS, and SOC_XWR16XX_DSS_L3RAM_SIZE.
Referenced by MmwDemo_dssDataPathConfig().
int32_t MmwDemo_dataPathConfigCQEdma (MmwDemo_DSS_DataPathObj * obj)
Description
Configures all EDMA channels and param sets used in data path processing
Parameters
[in] obj Pointer to data path object
Return values
-1 if error, 0 for no error
Definition at line 1262 of file dss_data_path.c.
References MmwDemo_DSS_DataPathCQConfig_t::anaMonCfg, MmwDemo_DSS_DataPathObj_t::context, MmwDemo_DSS_DataPathObj_t::datapathCQ, MmwDemo_DSS_dataPathContext_t_::edmaHandle, EDMAutil_configType1(), MMW_DATA_PATH_EDMA_INSTANCE, MMW_EDMA_CH_RX_SATURATION_MON, MMW_EDMA_CH_SIGIMG_MON, MmwDemo_EDMA_CQTransferCompletionCallbackFxn(), MmwDemo_DSS_DataPathCQConfig_t::rxSatData, MmwDemo_AnaMonitorCfg_t::rxSatMonEn, MmwDemo_DSS_DataPathCQConfig_t::satMonAddr, MmwDemo_DSS_DataPathCQConfig_t::satMonTotalSize, MmwDemo_DSS_DataPathCQConfig_t::sigImgData, MmwDemo_DSS_DataPathCQConfig_t::sigImgMonAddr, MmwDemo_AnaMonitorCfg_t::sigImgMonEn, and MmwDemo_DSS_DataPathCQConfig_t::sigImgMonTotalSize.
Referenced by MmwDemo_dataPathConfigEdma().
int32_t MmwDemo_dataPathConfigEdma (MmwDemo_DSS_DataPathObj * obj)
Description
Configures all EDMA channels and param sets used in data path processing
Parameters
[in] obj Pointer to data path object
Return values
-1 if error, 0 for no error
Definition at line 1355 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::ADCdataBuf, MmwDemo_DSS_DataPathObj_t::adcDataIn, BYTES_PER_SAMP_1D, BYTES_PER_SAMP_DET, MmwDemo_DSS_DataPathObj_t::context, MmwDemo_DSS_dataPathContext_t_::edmaHandle, EDMAutil_configType1(), EDMAutil_configType2b(), EDMAutil_configType3(), MAX, MMW_DATA_PATH_EDMA_INSTANCE, MMW_EDMA_CH_1D_IN_PING, MMW_EDMA_CH_1D_IN_PING_SHADOW, MMW_EDMA_CH_1D_IN_PONG, MMW_EDMA_CH_1D_IN_PONG_SHADOW, MMW_EDMA_CH_1D_OUT_PING, MMW_EDMA_CH_1D_OUT_PING_SHADOW, MMW_EDMA_CH_1D_OUT_PONG, MMW_EDMA_CH_1D_OUT_PONG_SHADOW, MMW_EDMA_CH_2D_IN_PING, MMW_EDMA_CH_2D_IN_PING_SHADOW, MMW_EDMA_CH_2D_IN_PONG, MMW_EDMA_CH_2D_IN_PONG_SHADOW, MMW_EDMA_CH_3D_IN_PING, MMW_EDMA_CH_3D_IN_PING_SHADOW, MMW_EDMA_CH_3D_IN_PONG, MMW_EDMA_CH_3D_IN_PONG_SHADOW, MMW_EDMA_CH_DET_MATRIX, MMW_EDMA_CH_DET_MATRIX2, MMW_EDMA_CH_DET_MATRIX2_SHADOW, MMW_EDMA_CH_DET_MATRIX_SHADOW, MmwDemo_dataPathConfigCQEdma(), MmwDemo_DSS_DataPathObj_t::numAdcSamples, MmwDemo_DSS_DataPathObj_t::numChirpsPerChirpEvent, MmwDemo_DSS_DataPathObj_t::numRxAntennas, MmwDemo_AnaMonitorCfg_t::rxSatMonEn, and MmwDemo_AnaMonitorCfg_t::sigImgMonEn.
Referenced by MmwDemo_dssDataPathReconfig().
void MmwDemo_dataPathConfigFFTs (MmwDemo_DSS_DataPathObj * obj)
Description
Configures FFTs (twiddle tables etc) involved in 1D, 2D and Azimuth processing.
Return values
Not Applicable.
Definition at line 3796 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::azimuthModCoefs, MmwDemo_DSS_DataPathObj_t::azimuthModCoefsHalfBin, MmwDemo_DSS_DataPathObj_t::azimuthTwiddle32x32, FFT_WINDOW_INT16, FFT_WINDOW_INT32, MMW_WIN_BLACKMAN, MMW_WIN_HANNING, MmwDemo_gen_twiddle_fft16x16_fast(), MmwDemo_gen_twiddle_fft32x32_fast(), MmwDemo_genDftSinCosTable(), MmwDemo_genWindow(), MmwDemo_DSS_DataPathObj_t::numAdcSamples, MmwDemo_DSS_DataPathObj_t::numAngleBins, MmwDemo_DSS_DataPathObj_t::numDopplerBins, MmwDemo_DSS_DataPathObj_t::numRangeBins, ONE_Q15, ONE_Q19, MmwDemo_DSS_DataPathObj_t::twiddle16x16_1D, MmwDemo_DSS_DataPathObj_t::twiddle32x32_2D, MmwDemo_DSS_DataPathObj_t::window1D, and MmwDemo_DSS_DataPathObj_t::window2D.
Referenced by MmwDemo_dssDataPathReconfig().
void MmwDemo_dataPathDeleteSemaphore (MmwDemo_DSS_dataPathContext_t * context)
Description
Delete Semaphores which are created in MmwDemo_dataPathInitEdma().
Return values
Not Applicable.
Definition at line 3383 of file dss_data_path.c.
void MmwDemo_dataPathInit1Dstate (MmwDemo_DSS_DataPathObj * obj)
Description
Initializes data path state variables for 1D processing.
Return values
Not Applicable.
Definition at line 3373 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::chirpCount, MmwDemo_DSS_DataPathObj_t::dopplerBinCount, and MmwDemo_DSS_DataPathObj_t::txAntennaCount.
Referenced by MmwDemo_dssDataPathInit().
int32_t MmwDemo_dataPathInitEdma (MmwDemo_DSS_dataPathContext_t * context)
Description
Initializes EDMA driver.
Return values
Not Applicable.
Definition at line 3409 of file dss_data_path.c.
References MmwDemo_DSS_dataPathContext_t_::edmaHandle, MmwDemo_edmaErrorCallbackFxn(), and MmwDemo_edmaTransferControllerErrorCallbackFxn().
Referenced by MmwDemo_dssDataPathInit().
void MmwDemo_dataPathObjInit (MmwDemo_DSS_DataPathObj * obj, MmwDemo_DSS_dataPathContext_t * context, MmwDemo_CliCfg_t * cliCfg, MmwDemo_CliCommonCfg_t * cliCommonCfg, MmwDemo_Cfg * cfg)
Description
Initializes data path object with supplied context and cli Config. The context and cli config point to permanent storage outside of data path object that data path object can refer to anytime during the lifetime of data path object. Data path default values that are not required to come through CLI commands are set in this function.
Return values
Not Applicable.
Definition at line 3360 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::cfg, MmwDemo_DSS_DataPathObj_t::cliCfg, MmwDemo_DSS_DataPathObj_t::cliCommonCfg, and MmwDemo_DSS_DataPathObj_t::context.
Referenced by MmwDemo_dssDataPathInit().
void MmwDemo_dataPathWait1DInputData (MmwDemo_DSS_DataPathObj * obj, uint32_t pingPongId)
Description
Waits for 1D FFT data to be transferrd to input buffer. This is a blocking function.
Parameters
[in] obj Pointer to data path object
[in] pingPongId ping-pong id (ping is 0 and pong is 1)
Return values
NONE
Definition at line 875 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::context, MmwDemo_DSS_dataPathContext_t_::edmaHandle, MMW_DATA_PATH_EDMA_INSTANCE, MMW_EDMA_CH_1D_IN_PING, MMW_EDMA_CH_1D_IN_PONG, and MmwDemo_dssAssert.
Referenced by MmwDemo_interChirpProcessing().
void MmwDemo_dataPathWait1DOutputData (MmwDemo_DSS_DataPathObj * obj, uint32_t pingPongId)
Description
Waits for 1D FFT data to be transferred to output buffer. This is a blocking function.
Parameters
[in] obj Pointer to data path object
[in] pingPongId ping-pong id (ping is 0 and pong is 1)
Return values
NONE
Definition at line 922 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::context, MmwDemo_DSS_dataPathContext_t_::edmaHandle, MMW_DATA_PATH_EDMA_INSTANCE, MMW_EDMA_CH_1D_OUT_PING, MMW_EDMA_CH_1D_OUT_PONG, and MmwDemo_dssAssert.
Referenced by MmwDemo_processChirp(), and MmwDemo_waitEndOfChirps().
void MmwDemo_dataPathWait2DInputData (MmwDemo_DSS_DataPathObj * obj, uint32_t pingPongId)
Description
Waits for 1D FFT data to be transferred to input buffer for 2D-FFT caclulation. This is a blocking function.
Parameters
[in] obj Pointer to data path object
[in] pingPongId ping-pong id (ping is 0 and pong is 1)
Return values
NONE
Definition at line 968 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::context, MmwDemo_DSS_dataPathContext_t_::edmaHandle, MMW_DATA_PATH_EDMA_INSTANCE, MMW_EDMA_CH_2D_IN_PING, MMW_EDMA_CH_2D_IN_PONG, and MmwDemo_dssAssert.
Referenced by MmwDemo_interFrameProcessing().
void MmwDemo_dataPathWait3DInputData (MmwDemo_DSS_DataPathObj * obj, uint32_t pingPongId)
Description
Waits for 1D FFT data to be transferred to input buffer for 3D-FFT calculation. This is a blocking function.
Parameters
[in] obj Pointer to data path object
[in] pingPongId ping-pong id (ping is 0 and pong is 1)
Return values
NONE
Definition at line 1014 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::context, MmwDemo_DSS_dataPathContext_t_::edmaHandle, MMW_DATA_PATH_EDMA_INSTANCE, MMW_EDMA_CH_3D_IN_PING, MMW_EDMA_CH_3D_IN_PONG, and MmwDemo_dssAssert.
Referenced by MmwDemo_interFrameProcessing().
void MmwDemo_dataPathWaitTransDetMatrix (MmwDemo_DSS_DataPathObj * obj)
Description
Waits for 2D FFT calculated data to be transferred out from L2 memory to detection matrix located in L3 memory. This is a blocking function.
Parameters
[in] obj Pointer to data path object
Return values
NONE
Definition at line 1061 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::context, MmwDemo_DSS_dataPathContext_t_::edmaHandle, MMW_DATA_PATH_EDMA_INSTANCE, MMW_EDMA_CH_DET_MATRIX, and MmwDemo_dssAssert.
Referenced by MmwDemo_interFrameProcessing(), and MmwDemo_log2AbsAccum().
void MmwDemo_dataPathWaitTransDetMatrix2 (MmwDemo_DSS_DataPathObj * obj)
Description
Waits for 2D FFT data to be transferred from detection matrix in L3 memory to L2 memory for CFAR detection in range direction. This is a blocking function.
Parameters
[in] obj Pointer to data path object
Return values
NONE
Definition at line 1098 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::context, MmwDemo_DSS_dataPathContext_t_::edmaHandle, MMW_DATA_PATH_EDMA_INSTANCE, MMW_EDMA_CH_1D_IN_PING, MMW_EDMA_CH_1D_IN_PONG, MMW_EDMA_CH_1D_OUT_PING, MMW_EDMA_CH_1D_OUT_PONG, MMW_EDMA_CH_2D_IN_PING, MMW_EDMA_CH_2D_IN_PONG, MMW_EDMA_CH_3D_IN_PING, MMW_EDMA_CH_3D_IN_PONG, MMW_EDMA_CH_DET_MATRIX, MMW_EDMA_CH_DET_MATRIX2, and MmwDemo_dssAssert.
Referenced by MmwDemo_interFrameProcessing().
void MmwDemo_dcRangeSignatureCompensation (MmwDemo_DSS_DataPathObj * obj, uint8_t chirpPingPongId)
Description
Compensation of DC range antenna signature
Return values
Not Applicable.
Definition at line 2067 of file dss_data_path.c.
References MmwDemo_CliCfg_t_::calibDcRangeSigCfg, MmwDemo_DSS_DataPathObj_t::cliCfg, MmwDemo_DSS_DataPathObj_t::dcRangeSigCalibCntr, MmwDemo_DSS_DataPathObj_t::dcRangeSigMean, MmwDemo_DSS_DataPathObj_t::fftOut1D, MmwDemo_DSS_DataPathObj_t::log2NumAvgChirps, MmwDemo_CalibDcRangeSigCfg_t::negativeBinIdx, MmwDemo_CalibDcRangeSigCfg_t::numAvgChirps, MmwDemo_DSS_DataPathObj_t::numRangeBins, MmwDemo_DSS_DataPathObj_t::numRxAntennas, MmwDemo_DSS_DataPathObj_t::numTxAntennas, and MmwDemo_CalibDcRangeSigCfg_t::positiveBinIdx.
Referenced by MmwDemo_interChirpProcessing().
void MmwDemo_decodeBPM (cmplx32ReIm_t * azimuthIn, uint32_t numRxAnt)
Description
Decodes the BPM antenna data.
Parameters
[in] azimuthIn : Pointer to antenna symbols
[in] numRxAnt : Number of RX antennas
Return values
Not Applicable.
Definition at line 2381 of file dss_data_path.c.
References cmplx32ReIm_t_::imag, and cmplx32ReIm_t_::real.
Referenced by MmwDemo_interFrameProcessing().
void MmwDemo_dssDataPathStartCQEdma (MmwDemo_DSS_DataPathObj * ptrDataPathObj)
Description
Function to configure CQ.
Parameters
[in] ptrDataPathObj Pointer to data path object.
Return values
0 if no error, else error (there will be system prints for these).
Definition at line 1326 of file dss_data_path.c.
References MmwDemo_DSS_DataPathCQConfig_t::anaMonCfg, MmwDemo_DSS_DataPathObj_t::context, MmwDemo_DSS_DataPathObj_t::datapathCQ, MmwDemo_DSS_dataPathContext_t_::edmaHandle, MMW_DATA_PATH_EDMA_INSTANCE, MMW_EDMA_CH_RX_SATURATION_MON, MMW_EDMA_CH_SIGIMG_MON, MmwDemo_AnaMonitorCfg_t::rxSatMonEn, and MmwDemo_AnaMonitorCfg_t::sigImgMonEn.
Referenced by MmwDemo_dssDataPathProcessEvents().
void MmwDemo_EDMA_CQTransferCompletionCallbackFxn (uintptr_t arg, uint8_t transferCompletionCode)
Description
EDMA transfer completion call back function as per EDMA API. Depending on the programmed transfer completion codes, posts the corresponding done/completion semaphore. Per current design, a single semaphore could have been used as the 1D, 2D and CFAR stages are sequential, this code gives some flexibility if some design change in future.
Definition at line 1204 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::datapathCQ, MMW_EDMA_CH_RX_SATURATION_MON, MMW_EDMA_CH_SIGIMG_MON, MmwDemo_dssAssert, MmwDemo_DSS_DataPathObj_t::numChirpsPerChirpEvent, MmwDemo_DSS_DataPathCQConfig_t::rxSatData, MmwDemo_DSS_DataPathCQConfig_t::rxSatEdmaCnt, MmwDemo_DSS_DataPathCQConfig_t::rxSatErrCnt, MmwDemo_DSS_DataPathCQConfig_t::rxSatMonCfg, MmwDemo_DSS_DataPathCQConfig_t::satMonDataSizePerChirp, MmwDemo_DSS_DataPathCQConfig_t::sigImgData, MmwDemo_DSS_DataPathCQConfig_t::sigImgEdmaCnt, MmwDemo_DSS_DataPathCQConfig_t::sigImgErrCnt, MmwDemo_DSS_DataPathCQConfig_t::sigImgMonCfg, and MmwDemo_DSS_DataPathCQConfig_t::sigImgMonDataSizePerChirp.
Referenced by MmwDemo_dataPathConfigCQEdma().
void MmwDemo_edmaErrorCallbackFxn (EDMA_Handle handle, EDMA_errorInfo_t * errorInfo)
Definition at line 3349 of file dss_data_path.c.
References MmwDemo_dssAssert.
Referenced by MmwDemo_dataPathInitEdma().
void MmwDemo_edmaTransferControllerErrorCallbackFxn (EDMA_Handle handle, EDMA_transferControllerErrorInfo_t * errorInfo)
Definition at line 3354 of file dss_data_path.c.
References MmwDemo_dssAssert.
Referenced by MmwDemo_dataPathInitEdma().
int32_t MmwDemo_gen_twiddle_fft16x16_fast (short * w, int32_t n)
Description
Following function is equivalent of the dsplib's gen_twiddle_fft16x16() function optimized for speed to allow quick reconfiguration when switching sub-frames in advanced frame mode. The alternative is to store tables for each sub-frame which is very high in memory consumption. The maximum error with respect to the dsplib function is in the LSB (+/- 1).
Definition at line 290 of file dss_data_path.c.
References twiddleTableCommon.
Referenced by MmwDemo_dataPathConfigFFTs().
int32_t MmwDemo_gen_twiddle_fft32x32_fast (int32_t * w, int32_t n, double scale)
Description
Following function is equivalent of the dsplib's gen_twiddle_fft32x32() function optimized for speed to allow quick reconfiguration when switching sub-frames in advanced frame mode. The alternative is to store tables for each sub-frame which is very high in memory consumption. The maximum error with respect to the dsplib function is in the LSB (+/- 1).
Definition at line 205 of file dss_data_path.c.
References twiddleTableCommon.
Referenced by MmwDemo_dataPathConfigFFTs().
void MmwDemo_genDftSinCosTable (cmplx16ImRe_t * dftSinCosTable, cmplx16ImRe_t * dftHalfBinVal, uint32_t dftLen)
Description
Generate SIN/COS table in Q15 (SIN to even int16 location, COS to odd int16 location. Also generates Sine/Cosine at half the bin value The table is generated using a lookup table twiddleTableCommon
Parameters
[out] dftSinCosTable Array with generated Sin Cos table
[out] dftHalfBinVal Sin/Cos value at half the bin
[in] dftLen Length of the DFT
Return values
Not Applicable.
Definition at line 3288 of file dss_data_path.c.
References cmplx16ImRe_t_::imag, ONE_Q15, PI_, cmplx16ImRe_t_::real, ROUND, and twiddleTableCommon.
Referenced by MmwDemo_dataPathConfigFFTs().
void MmwDemo_genWindow (void * win, uint32_t windowDatumType, uint32_t winLen, uint32_t winGenLen, int32_t oneQformat, uint32_t winType)
Description
Function generates a single FFT window samples. It calls single precision sine and cosine functions from mathlib library for the first sample only, and then recursively generates cosine values for other samples.
Parameters
[out] win Pointer to calculated window samples.
[in] windowDatumType Window samples data format. For windowDatumType = FFT_WINDOW_INT16, the samples format is int16_t. For windowDatumType = FFT_WINDOW_INT32, the samples format is int32_t.
[in] winLen Nominal window length
[in] winGenLen Number of generated samples
[in] oneQformat Q format of samples, oneQformat is the value of one in the desired format.
[in] winType Type of window, one of MMW_WIN_BLACKMAN, MMW_WIN_HANNING, or MMW_WIN_RECT.
Return values
none.
Definition at line 3847 of file dss_data_path.c.
References FFT_WINDOW_INT16, FFT_WINDOW_INT32, MMW_WIN_BLACKMAN, MMW_WIN_HANNING, MMW_WIN_RECT, and PI_.
Referenced by MmwDemo_dataPathConfigFFTs().
int32_t MmwDemo_getDopplerLine (MmwDemo_1D_DopplerLines_t * ths)
Description
Gets the Doppler index from the Doppler line bit mask, starting from the smallest active Doppler lin (bin). Subsequent calls return the next active Doppler line.
See also
MmwDemo_resetDopplerLines
Definition at line 545 of file dss_data_path.c.
References MmwDemo_1D_DopplerLines::currentIndex, MmwDemo_1D_DopplerLines::dopplerLineMask, MmwDemo_1D_DopplerLines::dopplerLineMaskLen, and MmwDemo_dssAssert.
Referenced by MmwDemo_interFrameProcessing().
void MmwDemo_interChirpProcessing (MmwDemo_DSS_DataPathObj * obj, uint8_t chirpPingPongId)
Description
Interchirp processing. It is executed per chirp event, after ADC buffer is filled with chirp samples.
Return values
Not Applicable.
Definition at line 2188 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::adcDataIn, MmwDemo_CliCfg_t_::calibDcRangeSigCfg, MmwDemo_DSS_DataPathObj_t::cliCfg, MmwDemo_DSS_DataPathObj_t::context, MmwDemo_DSS_dataPathContext_t_::edmaHandle, MmwDemo_CalibDcRangeSigCfg_t::enabled, MmwDemo_DSS_DataPathObj_t::fftOut1D, cycleLog_t_::interChirpProcessingTime, cycleLog_t_::interChirpWaitTime, isPong, MMW_DATA_PATH_EDMA_INSTANCE, MMW_EDMA_CH_1D_IN_PING, MMW_EDMA_CH_1D_IN_PONG, MmwDemo_dataPathWait1DInputData(), MmwDemo_dcRangeSignatureCompensation(), MmwDemo_DSS_DataPathObj_t::numAdcSamples, MmwDemo_DSS_DataPathObj_t::numRangeBins, MmwDemo_DSS_DataPathObj_t::numRxAntennas, pingPongId, MmwDemo_DSS_DataPathObj_t::twiddle16x16_1D, and MmwDemo_DSS_DataPathObj_t::window1D.
Referenced by MmwDemo_processChirp().
void MmwDemo_interFrameProcessing (MmwDemo_DSS_DataPathObj * obj)
Description
Interframe processing. It is called from MmwDemo_dssDataPathProcessEvents after all chirps of the frame have been received and 1D FFT processing on them has been completed.
Return values
Not Applicable.
Definition at line 2550 of file dss_data_path.c.
References MmwDemo_CfarCfg_t::averageMode, MmwDemo_DSS_DataPathObj_t::azimuthIn, MmwDemo_DSS_DataPathObj_t::azimuthMagSqr, MmwDemo_DSS_DataPathObj_t::azimuthModCoefs, MmwDemo_DSS_DataPathObj_t::azimuthModCoefsHalfBin, MmwDemo_DSS_DataPathObj_t::azimuthOut, MmwDemo_DSS_DataPathObj_t::azimuthStaticHeatMap, MmwDemo_DSS_DataPathObj_t::azimuthTwiddle32x32, MmwDemo_CliCfg_t_::bpmCfg, MmwDemo_CliCfg_t_::cfarCfgDoppler, MmwDemo_CliCfg_t_::cfarCfgRange, MmwDemo_DSS_DataPathObj_t::cfarDetObjIndexBuf, MmwDemo_DSS_DataPathObj_t::cliCfg, MmwDemo_DSS_DataPathObj_t::cliCommonCfg, MmwDemo_CliCfg_t_::clutterRemovalCfg, MmwDemo_CliCommonCfg_t_::compRxChanCfg, MmwDemo_DSS_DataPathObj_t::compRxChanCfg, MmwDemo_DSS_DataPathObj_t::context, MmwDemo_DSS_DataPathObj_t::detDopplerLines, MmwDemo_DSS_DataPathObj_t::detMatrix, MmwDemo_DSS_DataPathObj_t::detObj2D, MmwDemo_DSS_DataPathObj_t::detObj2DRaw, DOPPLER_IDX_TO_UNSIGNED, MmwDemo_objRaw::dopplerIdx, MmwDemo_DSS_DataPathObj_t::dstPingPong, MmwDemo_DSS_dataPathContext_t_::edmaHandle, EDMAutil_triggerType3(), MmwDemo_ExtendedMaxVelocityCfg_t::enabled, MmwDemo_NearFieldCorrectionCfg_t::enabled, MmwDemo_ClutterRemovalCfg_t::enabled, MmwDemo_measureRxChannelBiasCfg_t_::enabled, MmwDemo_NearFieldCorrectionCfg_t::endRangeIdx, MmwDemo_CliCfg_t_::extendedMaxVelocityCfg, MmwDemo_DSS_DataPathObj_t::fftOut2D, MmwDemo_CfarCfg_t::guardLen, cmplx16ReIm_t_::imag, cmplx16ImRe_t_::imag, cmplx32ReIm_t_::imag, MmwDemo_PeakGroupingCfg_t::inDopplerDirectionEn, MmwDemo_PeakGroupingCfg_t::inRangeDirectionEn, cycleLog_t_::interFrameProcessingTime, cycleLog_t_::interFrameWaitTime, MmwDemo_BpmCfg_t::isEnabled, isPong, MmwDemo_DSS_DataPathObj_t::log2NumDopplerBins, MAX_DET_OBJECTS_RAW, MmwDemo_PeakGroupingCfg_t::maxRangeIndex, MmwDemo_CliCommonCfg_t_::measureRxChanCfg, MmwDemo_PeakGroupingCfg_t::minRangeIndex, MMW_DATA_PATH_EDMA_INSTANCE, MMW_EDMA_CH_2D_IN_PING, MMW_EDMA_CH_2D_IN_PONG, MMW_EDMA_CH_3D_IN_PING, MMW_EDMA_CH_3D_IN_PONG, MMW_EDMA_CH_DET_MATRIX, MMW_EDMA_CH_DET_MATRIX2, MMW_EDMA_TRIGGER_DISABLE, MMW_EDMA_TRIGGER_ENABLE, MMW_PEAK_GROUPING_CFAR_PEAK_BASED, MMW_PEAK_GROUPING_DET_MATRIX_BASED, MmwDemo_addDopplerCompensation(), MmwDemo_cfarPeakGrouping(), MmwDemo_cfarPeakGroupingCfarQualified(), MmwDemo_dataPathWait2DInputData(), MmwDemo_dataPathWait3DInputData(), MmwDemo_dataPathWaitTransDetMatrix(), MmwDemo_dataPathWaitTransDetMatrix2(), MmwDemo_decodeBPM(), MmwDemo_dssAssert, MmwDemo_getDopplerLine(), MmwDemo_isSetDopplerLine(), MmwDemo_log2AbsAccum(), MmwDemo_magnitudeSquared(), MmwDemo_nearFieldCorrection(), MmwDemo_rangeBiasRxChPhaseMeasure(), MmwDemo_resetDopplerLines(), MmwDemo_rxChanPhaseBiasCompensation(), MmwDemo_setDopplerLine(), MmwDemo_XYestimation(), MmwDemo_Yestimation(), MmwDemo_CliCfg_t_::nearFieldCorrectionCfg, MmwDemo_CfarCfg_t::noiseDivShift, MmwDemo_DSS_DataPathObj_t::numAngleBins, MmwDemo_DSS_DataPathObj_t::numDetObj, MmwDemo_DSS_DataPathObj_t::numDetObjRaw, MmwDemo_DSS_DataPathObj_t::numDopplerBins, MmwDemo_DSS_DataPathObj_t::numRangeBins, MmwDemo_DSS_DataPathObj_t::numRxAntennas, MmwDemo_DSS_DataPathObj_t::numTxAntennas, MmwDemo_DSS_DataPathObj_t::numVirtualAntAzim, MmwDemo_DSS_DataPathObj_t::numVirtualAntennas, MmwDemo_CliCfg_t_::peakGroupingCfg, MmwDemo_objRaw::peakVal, pingPongId, MmwDemo_DSS_DataPathObj_t::radarCube, MmwDemo_objRaw::rangeIdx, MmwDemo_DSS_DataPathObj_t::rangeResolution, cmplx16ReIm_t_::real, cmplx16ImRe_t_::real, cmplx32ReIm_t_::real, MmwDemo_compRxChannelBiasCfg_t_::rxChPhaseComp, MmwDemo_PeakGroupingCfg_t::scheme, MmwDemo_measureRxChannelBiasCfg_t_::searchWinSize, MmwDemo_NearFieldCorrectionCfg_t::startRangeIdx, MmwDemo_DSS_DataPathObj_t::sumAbs, MmwDemo_DSS_DataPathObj_t::sumAbsRange, SYS_COMMON_NUM_TX_ANTENNAS, MmwDemo_measureRxChannelBiasCfg_t_::targetDistance, MmwDemo_CfarCfg_t::thresholdScale, MmwDemo_DSS_DataPathObj_t::twiddle32x32_2D, MmwDemo_DSS_DataPathObj_t::window2D, MmwDemo_DSS_DataPathObj_t::windowingBuf2D, and MmwDemo_CfarCfg_t::winLen.
Referenced by MmwDemo_dssDataPathProcessEvents().
uint32_t MmwDemo_isSetDopplerLine (MmwDemo_1D_DopplerLines_t * ths, uint16_t index)
Description
Checks whetehr Doppler line is active in the observed frame. It checks whether the bit is set in the Doppler line bit mask corresponding to Doppler line on which CFAR in Doppler direction detected object.
See also
MmwDemo_resetDopplerLines
Definition at line 520 of file dss_data_path.c.
References MmwDemo_1D_DopplerLines::dopplerLineMask.
Referenced by MmwDemo_interFrameProcessing().
void MmwDemo_log2AbsAccum (MmwDemo_DSS_DataPathObj * obj, int32_t rxAntIdx, uint32_t rangeIdx, uint32_t * waitingTime, uint32_t fftOutIndx)
Description
Computes log2Abs and accumulates for each dopple bin.
Return values
Not Applicable.
Definition at line 2414 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::fftOut2D, MmwDemo_DSS_DataPathObj_t::log2Abs, MmwDemo_dataPathWaitTransDetMatrix(), MmwDemo_DSS_DataPathObj_t::numDopplerBins, and MmwDemo_DSS_DataPathObj_t::sumAbs.
Referenced by MmwDemo_interFrameProcessing().
void MmwDemo_magnitudeSquared (cmplx32ReIm_t *restrict inpBuff, float *restrict magSqrdBuff, uint32_t numSamples)
Description
Outputs magnitude squared float array of input complex32 array
Return values
Not Applicable.
Definition at line 2044 of file dss_data_path.c.
Referenced by MmwDemo_interFrameProcessing().
void MmwDemo_nearFieldCorrection (MmwDemo_DSS_DataPathObj * obj, uint32_t detIdx2)
Description
Calculates near field correction for input detected index (corresponding to a range position). Referring to top level doxygen Implementation Details, this function performs the Set 1 rotation with the correction and adds to Set 0 in place to produce result in Set 0 of the azimuthOut.
Return values
Not Applicable.
Definition at line 2456 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::azimuthOut, MmwDemo_DSS_DataPathObj_t::cliCommonCfg, MmwDemo_CliCommonCfg_t_::compRxChanCfg, MmwDemo_DSS_DataPathObj_t::detObj2D, cmplx32ReIm_t_::imag, MMWDEMO_NEAR_FIELD_AB2, MMWDEMO_NEAR_FIELD_AB_SQ, MMWDEMO_NEAR_FIELD_CB2, MMWDEMO_NEAR_FIELD_CB_SQ, MMWDEMO_NEAR_FIELD_DB2, MMWDEMO_NEAR_FIELD_DB_SQ, MMWDEMO_NEAR_FIELD_EB2, MMWDEMO_NEAR_FIELD_EB_SQ, MMWDEMO_TWO_PI_OVER_LAMBDA, MmwDemo_DSS_DataPathObj_t::numAngleBins, PI_, MmwDemo_compRxChannelBiasCfg_t_::rangeBias, MmwDemo_DSS_DataPathObj_t::rangeResolution, and cmplx32ReIm_t_::real.
Referenced by MmwDemo_interFrameProcessing().
uint32_t MmwDemo_pow2roundup (uint32_t x)
Description
Power of 2 round up function.
Definition at line 575 of file dss_data_path.c.
Referenced by MmwDemo_parseProfileAndChirpConfig().
void MmwDemo_printHeapStats (char * name, uint32_t heapUsed, uint32_t heapSize)
Definition at line 3474 of file dss_data_path.c.
Referenced by MmwDemo_dataPathConfigBuffers().
void MmwDemo_processChirp (MmwDemo_DSS_DataPathObj * obj, uint16_t chirpIndxInMultiChirp)
Description
Chirp processing. It is called from MmwDemo_dssDataPathProcessEvents. It is executed per chirp
Return values
Not Applicable.
Definition at line 3195 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::ADCdataBuf, MmwDemo_DSS_DataPathObj_t::chirpCount, MmwDemo_DSS_DataPathObj_t::context, MmwDemo_DSS_DataPathObj_t::dopplerBinCount, MmwDemo_DSS_dataPathContext_t_::edmaHandle, cycleLog_t_::interChirpWaitTime, isPong, MMW_DATA_PATH_EDMA_INSTANCE, MMW_EDMA_CH_1D_IN_PING, MMW_EDMA_CH_1D_IN_PONG, MMW_EDMA_CH_1D_OUT_PING, MMW_EDMA_CH_1D_OUT_PONG, MmwDemo_dataPathWait1DOutputData(), MmwDemo_interChirpProcessing(), MmwDemo_DSS_DataPathObj_t::numAdcSamples, MmwDemo_DSS_DataPathObj_t::numChirpsPerChirpEvent, MmwDemo_DSS_DataPathObj_t::numDopplerBins, MmwDemo_DSS_DataPathObj_t::numRangeBins, MmwDemo_DSS_DataPathObj_t::numRxAntennas, MmwDemo_DSS_DataPathObj_t::numTxAntennas, pingPongId, MmwDemo_DSS_DataPathObj_t::radarCube, and MmwDemo_DSS_DataPathObj_t::txAntennaCount.
Referenced by MmwDemo_dssDataPathProcessEvents().
void MmwDemo_resetDopplerLines (MmwDemo_1D_DopplerLines_t * ths)
Description
Resets the Doppler line bit mask. Doppler line bit mask indicates Doppler lines (bins) on wich the CFAR in Doppler direction detected objects. After the CFAR in Doppler direction is completed for all range bins, the CFAR in range direction is performed on indicated Doppler lines. The array dopplerLineMask is uint32_t array. The LSB bit of the first word corresponds to Doppler line (bin) zero.
Definition at line 491 of file dss_data_path.c.
References MmwDemo_1D_DopplerLines::currentIndex, MmwDemo_1D_DopplerLines::dopplerLineMask, and MmwDemo_1D_DopplerLines::dopplerLineMaskLen.
Referenced by MmwDemo_interFrameProcessing().
static void MmwDemo_rxChanPhaseBiasCompensation (uint32_t * rxChComp, int64_t * input, uint32_t numAnt) inline static
Function Name : MmwDemo_rxChanPhaseBiasCompensation.
Description : Compensation of rx channel phase bias
Parameters
[in] rxChComp : rx channel compensation coefficient
[in] input : 32-bit complex input symbols must be 64 bit aligned
[in] numAnt : number of symbols
Returns
void
Definition at line 2344 of file dss_data_path.c.
Referenced by MmwDemo_interFrameProcessing().
void MmwDemo_setDopplerLine (MmwDemo_1D_DopplerLines_t * ths, uint16_t dopplerIndex)
Description
Sets the bit in the Doppler line bit mask dopplerLineMask corresponding to Doppler line on which CFAR in Doppler direction detected object. Indicating the Doppler line being active in observed frame.
See also
MmwDemo_resetDopplerLines
Definition at line 504 of file dss_data_path.c.
References MmwDemo_1D_DopplerLines::dopplerLineMask.
Referenced by MmwDemo_interFrameProcessing().
void MmwDemo_waitEndOfChirps (MmwDemo_DSS_DataPathObj * obj)
Description
Wait for transfer of data corresponding to the last 2 chirps (ping/pong) to the radarCube matrix before starting interframe processing.
Return values
Not Applicable.
Definition at line 3262 of file dss_data_path.c.
References cycleLog_t_::interChirpWaitTime, and MmwDemo_dataPathWait1DOutputData().
Referenced by MmwDemo_dssDataPathProcessEvents().
void MmwDemo_XYcalc (MmwDemo_DSS_DataPathObj * obj, uint32_t objIndex, uint16_t azimIdx, float maxVal)
Description
Calculates X/Y coordinates in meters based on the maximum position in the magnitude square of the azimuth FFT output. The function is called per detected object. The detected object structure already has populated range and Doppler indices. It calculates X and Y and coordinates and stores them into object fields along with the peak height. Also it populates the azimuth index in azimuthMagSqr array.
Parameters
[in] obj Pointer to data path object
[in] objIndex Detected object index
[in] azimIdx Index of the peak position in Azimuth FFT output
[in] maxVal Peak value
Return values
NONE
Definition at line 606 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::cliCommonCfg, MmwDemo_CliCommonCfg_t_::compRxChanCfg, MmwDemo_DSS_DataPathObj_t::detObj2D, MmwDemo_DSS_DataPathObj_t::detObj2dAzimIdx, MmwDemo_DSS_DataPathObj_t::numAngleBins, MmwDemo_DSS_DataPathObj_t::numDopplerBins, MmwDemo_DSS_DataPathObj_t::numRangeBins, ONE_QFORMAT, MmwDemo_compRxChannelBiasCfg_t_::rangeBias, MmwDemo_DSS_DataPathObj_t::rangeResolution, ROUND, and MmwDemo_DSS_DataPathObj_t::xyzOutputQFormat.
Referenced by MmwDemo_XYestimation().
void MmwDemo_XYestimation (MmwDemo_DSS_DataPathObj * obj, uint32_t objIndex)
Calculates X/Y coordinates in meters based on the maximum position in the magnitude square of the azimuth FFT output. The function is called per detected object. The detected object structure already has populated range and Doppler indices. This function finds maximum index in the azimuth FFT, calculates X and Y and coordinates and stores them into object fields along with the peak height. Also it populates the azimuth index in azimuthMagSqr array.
Parameters
[in] obj Pointer to data path object
[in] objIndex Detected object index
Return values
NONE
Definition at line 700 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::azimuthMagSqr, MmwDemo_DSS_DataPathObj_t::cliCfg, MmwDemo_DSS_DataPathObj_t::detObj2D, MmwDemo_MultiObjBeamFormingCfg_t::enabled, MmwDemo_ExtendedMaxVelocityCfg_t::enabled, MmwDemo_CliCfg_t_::extendedMaxVelocityCfg, MMW_MAX_OBJ_OUT, MmwDemo_XYcalc(), MmwDemo_CliCfg_t_::multiObjBeamFormingCfg, MmwDemo_MultiObjBeamFormingCfg_t::multiPeakThrsScal, MmwDemo_DSS_DataPathObj_t::numAngleBins, MmwDemo_DSS_DataPathObj_t::numDetObj, MmwDemo_DSS_DataPathObj_t::numDopplerBins, MmwDemo_DSS_DataPathObj_t::numRxAntennas, and MmwDemo_DSS_DataPathObj_t::numVirtualAntAzim.
Referenced by MmwDemo_interFrameProcessing().
void MmwDemo_Yestimation (MmwDemo_DSS_DataPathObj * obj, uint32_t objIndex)
Description
Calculates Y coordinates in meters based on the maximum position in the magnitude square of the azimuth FFT output. This is called when the number of rx antennas is 1.
Parameters
[in] obj Pointer to data path object
[in] objIndex Detected object index
Definition at line 827 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::cliCommonCfg, MmwDemo_CliCommonCfg_t_::compRxChanCfg, MmwDemo_DSS_DataPathObj_t::detObj2D, MmwDemo_DSS_DataPathObj_t::numRangeBins, ONE_QFORMAT, MmwDemo_compRxChannelBiasCfg_t_::rangeBias, MmwDemo_DSS_DataPathObj_t::rangeResolution, ROUND, and MmwDemo_DSS_DataPathObj_t::xyzOutputQFormat.
Referenced by MmwDemo_interFrameProcessing().
Variable Documentation
volatile cycleLog_t gCycleLog
Definition at line 175 of file dss_main.c.
uint8_t gMmwL1[MMW_L1_HEAP_SIZE]
L1 Heap
Definition at line 444 of file dss_data_path.c.
Referenced by MmwDemo_dataPathConfigBuffers().
uint8_t gMmwL2[MMW_L2_HEAP_SIZE]
L2 Heap
Definition at line 439 of file dss_data_path.c.
Referenced by MmwDemo_dataPathConfigBuffers().
uint8_t gMmwL3[SOC_XWR16XX_DSS_L3RAM_SIZE]
L3 RAM buffer
Definition at line 434 of file dss_data_path.c.
Referenced by MmwDemo_dataPathConfigBuffers().
const int32_t twiddleTableCommon[2 *256]
Lookup table for Twiddle table generation and DFT single bin DFT calculation. It contains 256 complex exponentials e(k) = cos(2*pi*k/1024)+j*sin(2*pi*k/1024), k=0,...,255, Imaginary values are in even, and real values are in odd locations. Values are in Q31 format, saturated to +/- 2147483647.
Following Matlab code was used to generate this table:
Generates lookup table for fast twiddle table generation for DSP lib FFT functions 16x16 and 32x32 for FFT sizes up to 1024. It saturates the amplitude to +/- 2147483647. The values are saved to file as imaginary %(sine) to even, and real (cosine) to odd index positions. M = 2147483647.5; nMax = 1024; table=round(M*exp(1j*2*pi/1024*[0:1*nMax/4-1]')); table=max(min(real(table),2147483647),-2147483647) + 1j* max(min(imag(table),2147483647),-2147483647); fid = fopen('twiddle_table_all.dat','w');
tableRI = [imag(table) real(table)]'; tableRI = tableRI(:); tableRI(tableRI<0) = tableRI(tableRI<0) + 4294967296;
fprintf(fid, [repmat(' 0x%08x,', 1, 8) '
'], tableRI); fclose(fid);
Definition at line 129 of file dss_data_path.c.
Referenced by MmwDemo_gen_twiddle_fft16x16_fast(), MmwDemo_gen_twiddle_fft32x32_fast(), and MmwDemo_genDftSinCosTable().
Copyright 2018, Texas Instruments Incorporated