xwr16xx/mmw/dss/dss_main.c File Reference
dss_main.c File Reference
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <xdc/std.h>
#include <xdc/cfg/global.h>
#include <xdc/runtime/IHeap.h>
#include <xdc/runtime/System.h>
#include <xdc/runtime/Error.h>
#include <xdc/runtime/Memory.h>
#include <ti/sysbios/BIOS.h>
#include <ti/sysbios/knl/Task.h>
#include <ti/sysbios/knl/Event.h>
#include <ti/sysbios/knl/Semaphore.h>
#include <ti/sysbios/knl/Clock.h>
#include <ti/sysbios/heaps/HeapBuf.h>
#include <ti/sysbios/heaps/HeapMem.h>
#include <ti/sysbios/family/c64p/Cache.h>
#include <ti/sysbios/family/c64p/Hwi.h>
#include <ti/sysbios/family/c64p/EventCombiner.h>
#include <ti/sysbios/utils/Load.h>
#include <ti/drivers/soc/soc.h>
#include <ti/common/sys_common.h>
#include <ti/common/mmwave_sdk_version.h>
#include <ti/utils/cycleprofiler/cycle_profiler.h>
#include <ti/demo/xwr16xx/mmw/dss/dss_mmw.h>
#include <ti/demo/xwr16xx/mmw/dss/dss_data_path.h>
#include <ti/demo/xwr16xx/mmw/common/mmw_messages.h>
#include <ti/demo/xwr16xx/mmw/dss/dss_lvds_stream.h>
#include <ti/mathlib/mathlib.h>
#include <cpy_tbl.h>
Data Structures
struct MmwDemo_HSRAM_t_
DSS stores demo output and DSS to MSS ISR information (for fast exception signalling) in HSRAM.
Macros
#define MMW_DEMO_CQ_SIGIMG_ADDR_OFFSET 0U
#define MMW_DEMO_CQ_RXSAT_ADDR_OFFSET 0x1000U
#define MMW_DEMO_CQ_DATA_ALIGNMENT 16U
#define MMW_DATAPATH_DET_PAYLOAD_SIZE (SOC_XWR16XX_DSS_HSRAM_SIZE - sizeof(uint8_t))
#define MMW_NUM_ANGLE_BINS 64
Azimuth FFT size.
#define MMWDEMO_AZIMUTH_TWO_PEAK_DETECTION_ENABLE 1
Flag to enable/disable two peak detection in azimuth for same range and velocity.
#define MMWDEMO_AZIMUTH_TWO_PEAK_THRESHOLD_SCALE (0.5)
Threshold for two peak detection in azimuth for same range and velocity, if 2nd peak heigth > first peak height * this scale then declare 2nd peak as detected. The peaks are in MmwDemo_DSS_DataPathObj::azimuthMagSqr.
#define MMWDEMO_SPEED_OF_LIGHT_IN_METERS_PER_SEC (3.0e8)
Typedefs
typedef struct MmwDemo_HSRAM_t_ MmwDemo_HSRAM_t
DSS stores demo output and DSS to MSS ISR information (for fast exception signalling) in HSRAM.
Functions
static void MmwDemo_edmaBlockCopy (EDMA_Handle handle, uint32_t loadAddr, uint32_t runAddr, uint16_t size)
static void MmwDemo_copyTable (EDMA_Handle handle, COPY_TABLE *tp)
int32_t MmwDemo_dssDataPathInit (void)
static int32_t MmwDemo_dssDataPathConfig (void)
static int32_t MmwDemo_dssDataPathStart (bool doRFStart)
static int32_t MmwDemo_dssDataPathStop (void)
static int32_t MmwDemo_dssDataPathProcessEvents (UInt event)
static int32_t MmwDemo_dssDataPathReconfig (MmwDemo_DSS_DataPathObj *obj)
static void MmwDemo_measurementResultOutput (MmwDemo_DSS_DataPathObj *obj)
static int32_t MmwDemo_dssMmwaveEventCallbackFxn (uint16_t msgId, uint16_t sbId, uint16_t sbLen, uint8_t *payload)
static void MmwDemo_dssMmwaveConfigCallbackFxn (MMWave_CtrlCfg *ptrCtrlCfg)
static void MmwDemo_dssMmwaveStartCallbackFxn (MMWave_CalibrationCfg *ptrCalibrationCfg)
static void MmwDemo_dssMmwaveStopCallbackFxn (void)
static void MmwDemo_dssMmwaveOpenCallbackFxn (MMWave_OpenCfg *ptrOpenCfg)
static void MmwDemo_dssMmwaveCloseCallbackFxn (void)
static void MmwDemo_dssChirpIntHandler (uintptr_t arg)
static void MmwDemo_dssFrameStartIntHandler (uintptr_t arg)
static void MmwDemo_dssInitTask (UArg arg0, UArg arg1)
static void MmwDemo_dssDataPathTask (UArg arg0, UArg arg1)
static void MmwDemo_dssMMWaveCtrlTask (UArg arg0, UArg arg1)
static void MmwDemo_triggerDss2MssISR (uint8_t dss2MssIsrInfo)
void MmwDemo_sleep (void)
static int32_t MmwDemo_dssSendProcessOutputToMSS (uint8_t *ptrHsmBuffer, uint32_t outputBufSize, MmwDemo_DSS_DataPathObj *obj)
void MmwDemo_dssDataPathOutputLogging (MmwDemo_DSS_DataPathObj *dataPathObj)
static int32_t MmwDemo_mboxWrite (MmwDemo_message *message)
static void MmwDemo_cfgUpdate (void *srcPtr, uint32_t offset, uint32_t size, int8_t subFrameNum)
static void MmwDemo_bssStopDone (void)
static void MmwDemo_mboxReadTask (UArg arg0, UArg arg1)
void MmwDemo_mboxCallback (Mbox_Handle handle, Mailbox_Type peer)
static int32_t MmwDemo_dataPathAdcBufInit (MmwDemo_DSS_dataPathContext_t *context)
static int32_t MmwDemo_dssDataPathConfigCQ (MmwDemo_DSS_DataPathObj *ptrDataPathObj)
static int32_t MmwDemo_dssDataPathConfigAdcBuf (MmwDemo_DSS_DataPathObj *ptrDataPathObj)
static uint16_t MmwDemo_getChirpStartIdx (MMWave_CtrlCfg *cfg, uint8_t subFrameIndx)
static uint16_t MmwDemo_getChirpEndIdx (MMWave_CtrlCfg *cfg, uint8_t subFrameIndx)
static uint16_t MmwDemo_getNumLoops (MMWave_CtrlCfg *cfg, uint8_t subFrameIndx)
static MMWave_ProfileHandle MmwDemo_getProfileHandle (MMWave_CtrlCfg *cfg, uint32_t profileLoopIdx)
bool MmwDemo_parseProfileAndChirpConfig (MmwDemo_DSS_DataPathObj *dataPathObj, MMWave_CtrlCfg *ptrCtrlCfg, uint8_t subFrameIndx)
void MmwDemo_parseAdcBufCfg (MmwDemo_DSS_DataPathObj *dataPathObj)
void _MmwDemo_dssAssert (int32_t expression, const char *file, int32_t line)
int main (void)
Variables
MmwDemo_HSRAM_t gHSRAM
uint8_t gCQRxSatMonMemory [SYS_COMMON_CQ_MAX_CHIRP_THRESHOLD *(RL_NUM_MON_SLICES_MAX+1)]
uint16_t gCQRxSigImgMemory [SYS_COMMON_CQ_MAX_CHIRP_THRESHOLD *(RL_NUM_MON_SLICES_MAX+1)]
MmwDemo_DSS_MCB gMmwDssMCB
Global Variable for tracking information required by the mmw Demo.
volatile cycleLog_t gCycleLog
far COPY_TABLE _MmwDemo_fastCode_L1PSRAM_copy_table
Macro Definition Documentation
#define MMW_DATAPATH_DET_PAYLOAD_SIZE (SOC_XWR16XX_DSS_HSRAM_SIZE - sizeof(uint8_t))
Definition at line 121 of file dss_main.c.
Referenced by MmwDemo_dssDataPathOutputLogging().
#define MMW_DEMO_CQ_DATA_ALIGNMENT 16U
Definition at line 104 of file dss_main.c.
Referenced by MmwDemo_dssDataPathConfigCQ().
#define MMW_DEMO_CQ_RXSAT_ADDR_OFFSET 0x1000U
Definition at line 101 of file dss_main.c.
Referenced by MmwDemo_dssDataPathConfigCQ().
#define MMW_DEMO_CQ_SIGIMG_ADDR_OFFSET 0U
Definition at line 100 of file dss_main.c.
Referenced by MmwDemo_dssDataPathConfigCQ().
#define MMW_NUM_ANGLE_BINS 64
Azimuth FFT size.
Definition at line 154 of file dss_main.c.
Referenced by MmwDemo_parseProfileAndChirpConfig().
#define MMWDEMO_AZIMUTH_TWO_PEAK_DETECTION_ENABLE 1
Flag to enable/disable two peak detection in azimuth for same range and velocity.
Definition at line 157 of file dss_main.c.
#define MMWDEMO_AZIMUTH_TWO_PEAK_THRESHOLD_SCALE (0.5)
Threshold for two peak detection in azimuth for same range and velocity, if 2nd peak heigth > first peak height * this scale then declare 2nd peak as detected. The peaks are in MmwDemo_DSS_DataPathObj::azimuthMagSqr.
Definition at line 162 of file dss_main.c.
#define MMWDEMO_SPEED_OF_LIGHT_IN_METERS_PER_SEC (3.0e8)
Definition at line 165 of file dss_main.c.
Referenced by MmwDemo_parseProfileAndChirpConfig().
Typedef Documentation
typedef struct MmwDemo_HSRAM_t_ MmwDemo_HSRAM_t
DSS stores demo output and DSS to MSS ISR information (for fast exception signalling) in HSRAM.
Function Documentation
void _MmwDemo_dssAssert (int32_t expression, const char * file, int32_t line)
Description
Sends DSS assert information to MSS
Return values
Not Applicable.
Definition at line 2854 of file dss_main.c.
References MmwDemo_message_body_u::assertInfo, MmwDemo_message_t::body, MmwDemo_dssAssertInfoMsg_t::file, MmwDemo_dssAssertInfoMsg_t::line, MMWDEMO_DSS2MSS_ASSERT_INFO, MMWDEMO_MAX_FILE_NAME_SIZE, MmwDemo_mboxWrite(), and MmwDemo_message_t::type.
int main (void)
Description
Entry point into the test code.
Return values
Not Applicable.
Definition at line 2905 of file dss_main.c.
References MmwDemo_DSS_MCB_t::cfg, DSS_SYS_VCLK, MmwDemo_Cfg_t::loggingBaudRate, MmwDemo_dssInitTask(), MmwDemo_DSS_MCB_t::socHandle, and MmwDemo_Cfg_t::sysClockFrequency.
static void MmwDemo_bssStopDone (void) static
Description
Function that acts upon receiving message that BSS has stopped successfully.
Return values
Not applicable
Definition at line 609 of file dss_main.c.
References MmwDemo_DSS_MCB_t::dataPathContext, MmwDemo_DSS_MCB_t::eventHandle, MmwDemo_DSS_dataPathContext_t_::interFrameProcToken, MmwDemo_DSS_STATE_STOP_PENDING, MMWDEMO_STOP_COMPLETE_EVT, and MmwDemo_DSS_MCB_t::state.
Referenced by MmwDemo_dssDataPathTask().
static void MmwDemo_cfgUpdate (void * srcPtr, uint32_t offset, uint32_t size, int8_t subFrameNum) static
Definition at line 580 of file dss_main.c.
References MmwDemo_DSS_MCB_t::cliCfg, and MMWDEMO_SUBFRAME_NUM_FRAME_LEVEL_CONFIG.
Referenced by MmwDemo_mboxReadTask().
static void MmwDemo_copyTable (EDMA_Handle handle, COPY_TABLE * tp) static
Description
Performs linker generated copy table copy using EDMA. Currently this is used to page in fast code from L3 to L1PSRAM.
Parameters
[in] handle EDMA handle
[in] tp Pointer to copy table
Return values
Not Applicable.
Definition at line 1289 of file dss_main.c.
References MmwDemo_dssAssert, and MmwDemo_edmaBlockCopy().
Referenced by MmwDemo_dssDataPathInit().
static int32_t MmwDemo_dataPathAdcBufInit (MmwDemo_DSS_dataPathContext_t * context) static
Description
Function to do Data Path Initialization on DSS.
Return values
Not Applicable.
Definition at line 1250 of file dss_main.c.
References MmwDemo_DSS_dataPathContext_t_::adcbufHandle.
Referenced by MmwDemo_dssDataPathInit().
static void MmwDemo_dssChirpIntHandler (uintptr_t arg) static
Description
Interrupt handler callback for chirp available. It runs in the ISR context.
Return values
Not Applicable.
Definition at line 247 of file dss_main.c.
References MmwDemo_DSS_DataPathObj_t::chirpCount, MmwDemo_DSS_STATS_t::chirpIntCounter, MmwDemo_DSS_STATS_t::chirpIntSkipCounter, MmwDemo_timingInfo::chirpProcessingEndMarginMax, MmwDemo_timingInfo::chirpProcessingEndMarginMin, MmwDemo_timingInfo::chirpProcessingEndTime, MmwDemo_DSS_dataPathContext_t_::chirpProcToken, MmwDemo_DSS_MCB_t::dataPathContext, MmwDemo_DSS_MCB_t::dataPathObj, MmwDemo_DSS_MCB_t::eventHandle, MmwDemo_timingInfo::interFrameProcessingEndMargin, MmwDemo_timingInfo::interFrameProcessingEndTime, MmwDemo_DSS_dataPathContext_t_::interFrameProcToken, MMWDEMO_CHIRP_EVT, MMWDEMO_DSS2MSS_CHIRP_PROC_DEADLINE_MISS_EXCEPTION, MmwDemo_DSS_STATE_STOPPED, MmwDemo_triggerDss2MssISR(), MmwDemo_DSS_DataPathObj_t::numChirpsPerChirpEvent, MmwDemo_DSS_MCB_t::numSubFrames, MmwDemo_DSS_MCB_t::state, MmwDemo_DSS_MCB_t::stats, MmwDemo_DSS_MCB_t::subFrameIndx, MmwDemo_timingInfo::subFrameSwitchingCycles, and MmwDemo_DSS_DataPathObj_t::timingInfo.
Referenced by MmwDemo_dssDataPathInit().
static int32_t MmwDemo_dssDataPathConfig (void) static
Description
Function to do Data Path Configuration on DSS.
Return values
Not Applicable.
Definition at line 2187 of file dss_main.c.
References MmwDemo_DSS_MCB_t::cfg, MmwDemo_Cfg_t::ctrlCfg, MmwDemo_DSS_MCB_t::dataPathObj, MmwDemo_dataPathComputeDerivedConfig(), MmwDemo_dataPathConfigBuffers(), MmwDemo_dssAssert, MmwDemo_dssDataPathConfigCQ(), MmwDemo_dssDataPathReconfig(), MmwDemo_parseAdcBufCfg(), MmwDemo_parseProfileAndChirpConfig(), MmwDemo_DSS_MCB_t::numSubFrames, SOC_XWR16XX_DSS_ADCBUF_BASE_ADDRESS, and MmwDemo_DSS_DataPathObj_t::subFrameIndx.
Referenced by MmwDemo_dssDataPathTask().
static int32_t MmwDemo_dssDataPathConfigAdcBuf (MmwDemo_DSS_DataPathObj * ptrDataPathObj) static
Description
Function to configure ADCBUF driver based on CLI inputs.
Parameters
[in] ptrDataPathObj Pointer to data path object.
Return values
0 if no error, else error (there will be system prints for these).
Definition at line 1597 of file dss_main.c.
References MmwDemo_CliCfg_t_::adcBufCfg, MmwDemo_DSS_dataPathContext_t_::adcbufHandle, MmwDemo_ADCBufCfg_t::adcFmt, MmwDemo_DSS_MCB_t::cfg, MmwDemo_ADCBufCfg_t::chInterleave, MmwDemo_DSS_DataPathObj_t::cliCfg, MmwDemo_DSS_DataPathObj_t::context, MmwDemo_ADCBufCfg_t::iqSwapSel, MmwDemo_dssAssert, MmwDemo_DSS_DataPathObj_t::numAdcSamples, MmwDemo_DSS_DataPathObj_t::numBytePerSample, MmwDemo_DSS_DataPathObj_t::numChirpsPerChirpEvent, MmwDemo_Cfg_t::openCfg, and SYS_COMMON_NUM_RX_CHANNEL.
Referenced by MmwDemo_dssDataPathReconfig().
static int32_t MmwDemo_dssDataPathConfigCQ (MmwDemo_DSS_DataPathObj * ptrDataPathObj) static
Description
Function to configure CQ.
Parameters
[in] ptrDataPathObj Pointer to data path object.
Return values
0 if no error, else error (there will be system prints for these).
Definition at line 1480 of file dss_main.c.
References MmwDemo_DSS_dataPathContext_t_::adcbufHandle, MmwDemo_DSS_DataPathCQConfig_t::anaMonCfg, MmwDemo_CliCommonCfg_t_::anaMonCfg, MmwDemo_DSS_DataPathObj_t::cliCommonCfg, MmwDemo_DSS_DataPathObj_t::context, MmwDemo_CliCommonCfg_t_::cqSatMonCfg, MmwDemo_CliCommonCfg_t_::cqSigImgMonCfg, MmwDemo_DSS_DataPathObj_t::datapathCQ, gCQRxSatMonMemory, gCQRxSigImgMemory, MMW_DEMO_CQ_DATA_ALIGNMENT, MMW_DEMO_CQ_RXSAT_ADDR_OFFSET, MMW_DEMO_CQ_SIGIMG_ADDR_OFFSET, MmwDemo_dssAssert, MmwDemo_DSS_DataPathObj_t::numChirpsPerChirpEvent, MmwDemo_DSS_DataPathCQConfig_t::rxSatData, MmwDemo_DSS_DataPathCQConfig_t::rxSatMonCfg, MmwDemo_AnaMonitorCfg_t::rxSatMonEn, MmwDemo_DSS_DataPathCQConfig_t::satMonAddr, MmwDemo_DSS_DataPathCQConfig_t::satMonDataSizePerChirp, MmwDemo_DSS_DataPathCQConfig_t::satMonTotalSize, MmwDemo_DSS_DataPathCQConfig_t::sigImgData, MmwDemo_DSS_DataPathCQConfig_t::sigImgMonAddr, MmwDemo_DSS_DataPathCQConfig_t::sigImgMonCfg, MmwDemo_DSS_DataPathCQConfig_t::sigImgMonDataSizePerChirp, MmwDemo_AnaMonitorCfg_t::sigImgMonEn, MmwDemo_DSS_DataPathCQConfig_t::sigImgMonTotalSize, and MmwDemo_DSS_DataPathObj_t::validProfileIdx.
Referenced by MmwDemo_dssDataPathConfig().
int32_t MmwDemo_dssDataPathInit (void)
Description
Function to do Data Path Initialization on DSS.
Return values
Not Applicable.
Definition at line 1404 of file dss_main.c.
References _MmwDemo_fastCode_L1PSRAM_copy_table, MmwDemo_DSS_MCB_t::cfg, MmwDemo_DSS_MCB_t::cliCfg, MmwDemo_DSS_MCB_t::cliCommonCfg, MmwDemo_DSS_MCB_t::dataPathContext, MmwDemo_DSS_MCB_t::dataPathObj, MmwDemo_DSS_dataPathContext_t_::edmaHandle, MmwDemo_DSS_MCB_t::loggingBufferAvailable, MmwDemo_copyTable(), MmwDemo_dataPathAdcBufInit(), MmwDemo_dataPathInit1Dstate(), MmwDemo_dataPathInitEdma(), MmwDemo_dataPathObjInit(), MmwDemo_dssChirpIntHandler(), MmwDemo_dssFrameStartIntHandler(), SOC_XWR16XX_DSS_INTC_EVENT_CHIRP_AVAIL, SOC_XWR16XX_DSS_INTC_EVENT_FRAME_START, and MmwDemo_DSS_MCB_t::socHandle.
Referenced by MmwDemo_dssInitTask().
void MmwDemo_dssDataPathOutputLogging (MmwDemo_DSS_DataPathObj * dataPathObj)
Description
Function to send data path detection output.
Return values
Not Applicable.
Definition at line 1183 of file dss_main.c.
References MmwDemo_DSS_DataPathObj_t::cliCfg, MmwDemo_HSRAM_t_::dataPathDetectionPayload, MmwDemo_DSS_STATS_t::detObjLoggingErr, MmwDemo_DSS_STATS_t::detObjLoggingSkip, MmwDemo_LVDSUserDataHeader::detObjNum, MmwDemo_LVDSUserDataHeader::frameNum, MmwDemo_DSS_STATS_t::frameStartEvt, MmwDemo_LvdsStreamCfg_t::isSwEnabled, MmwDemo_DSS_MCB_t::loggingBufferAvailable, MmwDemo_DSS_MCB_t::lvdsStream, MmwDemo_CliCfg_t_::lvdsStreamCfg, MMW_DATAPATH_DET_PAYLOAD_SIZE, MmwDemo_dssSendProcessOutputToMSS(), MmwDemo_LVDSStreamDeleteSwSession(), MmwDemo_LVDSStreamSwConfig(), MmwDemo_DSS_DataPathObj_t::numDetObj, MmwDemo_LVDSUserDataHeader::reserved, MmwDemo_DSS_MCB_t::stats, MmwDemo_LVDSStream_MCB::swSessionHandle, and MmwDemo_LVDSStream_MCB::userDataHeader.
Referenced by MmwDemo_dssDataPathProcessEvents().
static int32_t MmwDemo_dssDataPathProcessEvents (UInt event) static
Description
Function to process Data Path events at runtime.
Parameters
[in] event Data Path Event
Return values
Not Applicable.
Definition at line 2306 of file dss_main.c.
References MmwDemo_timingInfo::activeFrameCPULoad, MmwDemo_DSS_DataPathObj_t::chirpCount, MmwDemo_DSS_STATS_t::chirpEvt, MmwDemo_timingInfo::chirpProcessingEndTime, MmwDemo_DSS_dataPathContext_t_::chirpProcToken, MmwDemo_DSS_DataPathObj_t::cliCommonCfg, MmwDemo_DSS_DataPathObj_t::cycleLog, MmwDemo_DSS_MCB_t::dataPathContext, MmwDemo_DSS_MCB_t::dataPathObj, MmwDemo_measureRxChannelBiasCfg_t_::enabled, MmwDemo_DSS_STATS_t::frameStartEvt, MmwDemo_DSS_STATS_t::frameTrigEvt, cycleLog_t_::interChirpProcessingTime, cycleLog_t_::interChirpWaitTime, MmwDemo_timingInfo::interFrameCPULoad, MmwDemo_timingInfo::interFrameProcCycles, MmwDemo_timingInfo::interFrameProcessingEndTime, cycleLog_t_::interFrameProcessingTime, cycleLog_t_::interFrameWaitTime, MmwDemo_CliCommonCfg_t_::measureRxChanCfg, MMWDEMO_BSS_FRAME_TRIGGER_READY_EVT, MMWDEMO_CHIRP_EVT, MmwDemo_dssAssert, MmwDemo_dssDataPathOutputLogging(), MmwDemo_dssDataPathStartCQEdma(), MMWDEMO_FRAMESTART_EVT, MmwDemo_interFrameProcessing(), MmwDemo_measurementResultOutput(), MmwDemo_processChirp(), MmwDemo_waitEndOfChirps(), MmwDemo_DSS_DataPathObj_t::numChirpsPerChirpEvent, MmwDemo_DSS_MCB_t::stats, MmwDemo_DSS_MCB_t::subFrameIndx, and MmwDemo_DSS_DataPathObj_t::timingInfo.
Referenced by MmwDemo_dssDataPathTask().
static int32_t MmwDemo_dssDataPathReconfig (MmwDemo_DSS_DataPathObj * obj) static
Description
Function to do Data Path Re-Configuration on DSS. This is used when switching between sub-frames.
Return values
-1 if error, 0 otherwise.
Definition at line 2135 of file dss_main.c.
References MmwDemo_DSS_DataPathObj_t::cliCfg, MmwDemo_LvdsStreamCfg_t::dataFmt, MmwDemo_LVDSStream_MCB::hwSessionHandle, MmwDemo_DSS_MCB_t::lvdsStream, MmwDemo_CliCfg_t_::lvdsStreamCfg, MmwDemo_dataPathConfigEdma(), MmwDemo_dataPathConfigFFTs(), MmwDemo_dssDataPathConfigAdcBuf(), MmwDemo_LVDSStreamDeleteHwSession(), and MmwDemo_LVDSStreamHwConfig().
Referenced by MmwDemo_dssDataPathConfig(), and MmwDemo_mboxReadTask().
static int32_t MmwDemo_dssDataPathStart (bool doRFStart) static
Description
Function to start Data Path on DSS.
Return values
Not Applicable.
Definition at line 2261 of file dss_main.c.
References MmwDemo_DSS_MCB_t::cfg, MmwDemo_DSS_dataPathContext_t_::chirpProcToken, MmwDemo_Cfg_t::ctrlCfg, MmwDemo_DSS_MCB_t::ctrlHandle, MmwDemo_DSS_MCB_t::dataPathContext, MmwDemo_LVDSStream_MCB::hwFrameDoneCount, MmwDemo_DSS_dataPathContext_t_::interFrameProcToken, MmwDemo_DSS_MCB_t::lvdsStream, and MmwDemo_LVDSStream_MCB::swFrameDoneCount.
Referenced by MmwDemo_dssDataPathTask().
static int32_t MmwDemo_dssDataPathStop (void) static
Description
Function to stop Data Path on DSS. Assume BSS has been stopped by mmWave already. This also sends the STOP done message back to MSS to signal the procssing chain has come to a stop.
Return values
Not Applicable.
Definition at line 2402 of file dss_main.c.
References MmwDemo_DSS_STATS_t::chirpEvt, MmwDemo_DSS_STATS_t::frameStartEvt, MmwDemo_DSS_STATS_t::frameTrigEvt, MmwDemo_LVDSStream_MCB::hwSessionHandle, MmwDemo_DSS_MCB_t::lvdsStream, MMWDEMO_DSS2MSS_STOPDONE, MmwDemo_DSS_STATE_STOPPED, MmwDemo_dssAssert, MmwDemo_LVDSStreamDeleteHwSession(), MmwDemo_LVDSStreamDeleteSwSession(), MmwDemo_mboxWrite(), MmwDemo_DSS_STATS_t::numCalibrationReports, MmwDemo_DSS_STATS_t::numFailedTimingReports, MmwDemo_DSS_MCB_t::state, MmwDemo_DSS_MCB_t::stats, MmwDemo_DSS_STATS_t::stopEvt, MmwDemo_LVDSStream_MCB::swSessionHandle, and MmwDemo_message_t::type.
Referenced by MmwDemo_dssDataPathTask().
static void MmwDemo_dssDataPathTask (UArg arg0, UArg arg1) static
Description
Data Path main task that handles events from remote and do dataPath processing. This task is created when MSS is responsible for the mmwave Link and DSS is responsible for data path processing.
Return values
Not Applicable.
Definition at line 2489 of file dss_main.c.
References MmwDemo_DSS_MCB_t::eventHandle, MMWDEMO_BSS_STOP_COMPLETE_EVT, MmwDemo_bssStopDone(), MMWDEMO_CHIRP_EVT, MMWDEMO_CONFIG_EVT, MmwDemo_DSS_STATE_STARTED, MmwDemo_DSS_STATE_STOP_PENDING, MmwDemo_DSS_STATE_STOPPED, MmwDemo_dssDataPathConfig(), MmwDemo_dssDataPathProcessEvents(), MmwDemo_dssDataPathStart(), MmwDemo_dssDataPathStop(), MMWDEMO_FRAMESTART_EVT, MMWDEMO_START_EVT, MMWDEMO_STOP_COMPLETE_EVT, and MmwDemo_DSS_MCB_t::state.
Referenced by MmwDemo_dssInitTask().
static void MmwDemo_dssFrameStartIntHandler (uintptr_t arg) static
Description
Interrupt handler callback for frame start ISR.
Return values
Not Applicable.
Definition at line 331 of file dss_main.c.
References MmwDemo_DSS_MCB_t::dataPathContext, MmwDemo_DSS_MCB_t::eventHandle, MmwDemo_DSS_STATS_t::frameIntSkipCounter, MmwDemo_DSS_STATS_t::frameStartIntCounter, MmwDemo_DSS_dataPathContext_t_::interFrameProcToken, MMWDEMO_DSS2MSS_FRAME_PROC_DEADLINE_MISS_EXCEPTION, MmwDemo_DSS_STATE_STOPPED, MMWDEMO_FRAMESTART_EVT, MmwDemo_triggerDss2MssISR(), MmwDemo_DSS_MCB_t::state, MmwDemo_DSS_MCB_t::stats, and MmwDemo_DSS_MCB_t::subFrameIndx.
Referenced by MmwDemo_dssDataPathInit().
static void MmwDemo_dssInitTask (UArg arg0, UArg arg1) static
Description
System Initialization Task which initializes the various components in the system.
Return values
Not Applicable.
Definition at line 2647 of file dss_main.c.
References MmwDemo_message_t::body, MmwDemo_DSS_MCB_t::cfg, MmwDemo_DSS_MCB_t::ctrlHandle, MmwDemo_HSRAM_t_::dss2MssIsrInfo, MmwDemo_message_body_u::dss2mssISRinfoAddress, DSS_SYS_VCLK, MmwDemo_DSS_MCB_t::eventHandle, MmwDemo_Cfg_t::loggingBaudRate, MmwDemo_DSS_MCB_t::loggingUartHandle, MmwDemo_DSS_MCB_t::mboxSemHandle, MMWDEMO_DSS2MSS_ISR_INFO_ADDRESS, MmwDemo_DSS_STATE_INIT, MmwDemo_dssDataPathInit(), MmwDemo_dssDataPathTask(), MmwDemo_dssMmwaveCloseCallbackFxn(), MmwDemo_dssMmwaveConfigCallbackFxn(), MmwDemo_dssMMWaveCtrlTask(), MmwDemo_dssMmwaveEventCallbackFxn(), MmwDemo_dssMmwaveOpenCallbackFxn(), MmwDemo_dssMmwaveStartCallbackFxn(), MmwDemo_dssMmwaveStopCallbackFxn(), MmwDemo_LVDSStreamInit(), MmwDemo_mboxCallback(), MmwDemo_mboxReadTask(), MmwDemo_mboxWrite(), MmwDemo_DSS_MCB_t::peerMailbox, MmwDemo_DSS_MCB_t::socHandle, MmwDemo_DSS_MCB_t::state, and MmwDemo_message_t::type.
Referenced by main().
static void MmwDemo_dssMmwaveCloseCallbackFxn (void) static
Description
Registered close callback function which is invoked when the mmWave module has been close on the MSS
Return values
Not applicable
Definition at line 513 of file dss_main.c.
References MmwDemo_DSS_STATS_t::closeEvt, and MmwDemo_DSS_MCB_t::stats.
Referenced by MmwDemo_dssInitTask().
static void MmwDemo_dssMmwaveConfigCallbackFxn (MMWave_CtrlCfg * ptrCtrlCfg) static
Description
Registered config callback function on DSS which is invoked by MMWAVE library when the remote side has finished configure mmWaveLink and BSS. The configuration need to be saved on DSS and used for DataPath.
Parameters
[in] ptrCtrlCfg Pointer to the control configuration
Return values
Not applicable
Definition at line 471 of file dss_main.c.
References MmwDemo_DSS_MCB_t::cfg, MmwDemo_DSS_STATS_t::configEvt, MmwDemo_Cfg_t::ctrlCfg, MmwDemo_DSS_MCB_t::eventHandle, MMWDEMO_CONFIG_EVT, and MmwDemo_DSS_MCB_t::stats.
Referenced by MmwDemo_dssInitTask().
static void MmwDemo_dssMMWaveCtrlTask (UArg arg0, UArg arg1) static
Description
The task is used to provide an execution context for the mmWave control task
Return values
Not Applicable.
Definition at line 2467 of file dss_main.c.
References MmwDemo_DSS_MCB_t::ctrlHandle.
Referenced by MmwDemo_dssInitTask().
static int32_t MmwDemo_dssMmwaveEventCallbackFxn (uint16_t msgId, uint16_t sbId, uint16_t sbLen, uint8_t * payload) static
Description
Registered event callback function on DSS which is invoked by MMWAVE library when an event from the BSS is received.
Parameters
[in] msgId Message Identifier
[in] sbId Subblock identifier
[in] sbLen Length of the subblock
[in] payload Pointer to the payload buffer
Return values
Always return 0. [Pass the event to the remote domain]
Definition at line 376 of file dss_main.c.
References MmwDemo_DSS_STATS_t::bssStopAsyncEvt, MmwDemo_DSS_MCB_t::eventHandle, MMWDEMO_BSS_FRAME_TRIGGER_READY_EVT, MMWDEMO_BSS_STOP_COMPLETE_EVT, MmwDemo_dssAssert, MmwDemo_DSS_STATS_t::numCalibrationReports, MmwDemo_DSS_STATS_t::numFailedTimingReports, and MmwDemo_DSS_MCB_t::stats.
Referenced by MmwDemo_dssInitTask().
static void MmwDemo_dssMmwaveOpenCallbackFxn (MMWave_OpenCfg * ptrOpenCfg) static
Description
Registered open callback function which is invoked when the mmWave module has been opened on the MSS
Parameters
[in] ptrOpenCfg Pointer to the open configuration
Return values
Not applicable
Definition at line 496 of file dss_main.c.
References MmwDemo_DSS_MCB_t::cfg, MmwDemo_Cfg_t::openCfg, MmwDemo_DSS_STATS_t::openEvt, and MmwDemo_DSS_MCB_t::stats.
Referenced by MmwDemo_dssInitTask().
static void MmwDemo_dssMmwaveStartCallbackFxn (MMWave_CalibrationCfg * ptrCalibrationCfg) static
Description
Registered Start callback function on DSS which is invoked by MMWAVE library when the remote side has started mmWaveLink and BSS. This Callback function passes the event to DataPath task.
Parameters
[in] ptrCalibrationCfg Pointer to the calibration configuration
Return values
Not applicable
Definition at line 532 of file dss_main.c.
References MmwDemo_DSS_MCB_t::eventHandle, MMWDEMO_START_EVT, MmwDemo_DSS_STATS_t::startEvt, and MmwDemo_DSS_MCB_t::stats.
Referenced by MmwDemo_dssInitTask().
static void MmwDemo_dssMmwaveStopCallbackFxn (void) static
Description
Registered Start callback function on DSS which is invoked by MMWAVE library when the remote side has stop mmWaveLink and BSS. This Callback function passes the event to DataPath task.
Return values
Not applicable
Definition at line 550 of file dss_main.c.
References MmwDemo_DSS_MCB_t::stats, and MmwDemo_DSS_STATS_t::stopEvt.
Referenced by MmwDemo_dssInitTask().
int32_t MmwDemo_dssSendProcessOutputToMSS (uint8_t * ptrHsmBuffer, uint32_t outputBufSize, MmwDemo_DSS_DataPathObj * obj) static
Description
Function to send detected objects to MSS logger.
Parameters
[in] ptrHsmBuffer Pointer to the output buffer
[in] outputBufSize Size of the output buffer
[in] obj Handle to the Data Path Object
Return values
=0 Success <0 Failed
Definition at line 945 of file dss_main.c.
References MmwDemo_output_message_stats_t::activeFrameCPULoad, MmwDemo_timingInfo::activeFrameCPULoad, MmwDemo_msgTlv_t::address, MmwDemo_DSS_DataPathObj_t::azimuthStaticHeatMap, MmwDemo_message_t::body, MmwDemo_timingInfo::chirpProcessingEndMarginMin, MmwDemo_DSS_DataPathObj_t::cliCfg, MmwDemo_GuiMonSel_t::detectedObjects, MmwDemo_DSS_DataPathObj_t::detMatrix, MmwDemo_message_body_u::detObj, MmwDemo_DSS_DataPathObj_t::detObj2D, DSP_CLOCK_MHZ, MmwDemo_output_message_header_t::frameNumber, MmwDemo_DSS_STATS_t::frameStartIntCounter, MmwDemo_CliCfg_t_::guiMonSel, MmwDemo_detObjMsg_t::header, MmwDemo_output_message_stats_t::interChirpProcessingMargin, MmwDemo_output_message_stats_t::interFrameCPULoad, MmwDemo_timingInfo::interFrameCPULoad, MmwDemo_timingInfo::interFrameProcCycles, MmwDemo_timingInfo::interFrameProcessingEndMargin, MmwDemo_output_message_stats_t::interFrameProcessingMargin, MmwDemo_output_message_stats_t::interFrameProcessingTime, MmwDemo_msgTlv_t::length, MmwDemo_GuiMonSel_t::logMagRange, MmwDemo_output_message_header_t::magicWord, MMWDEMO_DSS2MSS_DETOBJ_READY, MmwDemo_mboxWrite(), MMWDEMO_OUTPUT_MSG_AZIMUT_STATIC_HEAT_MAP, MMWDEMO_OUTPUT_MSG_DETECTED_POINTS, MMWDEMO_OUTPUT_MSG_NOISE_PROFILE, MMWDEMO_OUTPUT_MSG_RANGE_DOPPLER_HEAT_MAP, MMWDEMO_OUTPUT_MSG_RANGE_PROFILE, MMWDEMO_OUTPUT_MSG_SEGMENT_LEN, MMWDEMO_OUTPUT_MSG_STATS, MmwDemo_GuiMonSel_t::noiseProfile, MmwDemo_output_message_header_t::numDetectedObj, MmwDemo_output_message_dataObjDescr_t::numDetetedObj, MmwDemo_DSS_DataPathObj_t::numDetObj, MmwDemo_DSS_DataPathObj_t::numDopplerBins, MmwDemo_DSS_DataPathObj_t::numRangeBins, MmwDemo_output_message_header_t::numTLVs, MmwDemo_DSS_DataPathObj_t::numVirtualAntAzim, MmwDemo_output_message_header_t::platform, MmwDemo_GuiMonSel_t::rangeAzimuthHeatMap, MmwDemo_GuiMonSel_t::rangeDopplerHeatMap, MmwDemo_DSS_MCB_t::stats, MmwDemo_GuiMonSel_t::statsInfo, MmwDemo_DSS_MCB_t::subFrameIndx, MmwDemo_output_message_header_t::subFrameNumber, MmwDemo_output_message_header_t::timeCpuCycles, MmwDemo_DSS_DataPathObj_t::timingInfo, MmwDemo_detObjMsg_t::tlv, MmwDemo_output_message_header_t::totalPacketLen, MmwDemo_timingInfo::transmitOutputCycles, MmwDemo_output_message_stats_t::transmitOutputTime, MmwDemo_msgTlv_t::type, MmwDemo_message_t::type, MmwDemo_output_message_header_t::version, MmwDemo_DSS_DataPathObj_t::xyzOutputQFormat, and MmwDemo_output_message_dataObjDescr_t::xyzQFormat.
Referenced by MmwDemo_dssDataPathOutputLogging(), and MmwDemo_mboxCallback().
static void MmwDemo_edmaBlockCopy (EDMA_Handle handle, uint32_t loadAddr, uint32_t runAddr, uint16_t size) static
Description
Performs simple block copy using EDMA. Used for the purpose of copying linker table for L3 to L1PSRAM copy. memcpy cannot be used because there is no data bus access to L1PSRAM.
Parameters
[in] handle EDMA handle
[in] loadAddr load address
[in] runAddr run address
[in] size size in bytes
Return values
Not Applicable.
Definition at line 1328 of file dss_main.c.
References EDMA_TPCC0_REQ_FREE_0, and MmwDemo_dssAssert.
Referenced by MmwDemo_copyTable().
static uint16_t MmwDemo_getChirpEndIdx (MMWave_CtrlCfg * cfg, uint8_t subFrameIndx) static
Definition at line 1695 of file dss_main.c.
Referenced by MmwDemo_parseProfileAndChirpConfig().
static uint16_t MmwDemo_getChirpStartIdx (MMWave_CtrlCfg * cfg, uint8_t subFrameIndx) static
Definition at line 1683 of file dss_main.c.
Referenced by MmwDemo_parseProfileAndChirpConfig().
static uint16_t MmwDemo_getNumLoops (MMWave_CtrlCfg * cfg, uint8_t subFrameIndx) static
Definition at line 1708 of file dss_main.c.
Referenced by MmwDemo_parseProfileAndChirpConfig().
static MMWave_ProfileHandle MmwDemo_getProfileHandle (MMWave_CtrlCfg * cfg, uint32_t profileLoopIdx) static
Definition at line 1720 of file dss_main.c.
Referenced by MmwDemo_parseProfileAndChirpConfig().
void MmwDemo_mboxCallback (Mbox_Handle handle, Mailbox_Type peer)
Description
This function is a callback funciton that invoked when a message is received from the peer.
Parameters
[in] handle Handle to the Mailbox on which data was received
[in] peer Peer from which data was received
Return values
Not Applicable.
Definition at line 917 of file dss_main.c.
References MmwDemo_DSS_MCB_t::mboxSemHandle, and MmwDemo_dssSendProcessOutputToMSS().
Referenced by MmwDemo_dssInitTask(), and MmwDemo_mboxReadTask().
static void MmwDemo_mboxReadTask (UArg arg0, UArg arg1) static
Description
The Task is used to handle the mmw demo messages received from Mailbox virtual channel.
Parameters
[in] arg0 arg0 of the Task. Not used
[in] arg1 arg1 of the Task. Not used
Return values
Not Applicable.
Definition at line 645 of file dss_main.c.
References MmwDemo_message_body_u::adcBufCfg, MmwDemo_message_body_u::anaMonCfg, MmwDemo_CliCommonCfg_t_::anaMonCfg, MmwDemo_message_t::body, MmwDemo_message_body_u::bpmCfg, MmwDemo_message_body_u::calibDcRangeSigCfg, MmwDemo_message_body_u::cfarCfg, MmwDemo_DSS_MCB_t::cfg, MmwDemo_DSS_MCB_t::cliCommonCfg, MmwDemo_message_body_u::clutterRemovalCfg, MmwDemo_message_body_u::compRxChanCfg, MmwDemo_CliCommonCfg_t_::compRxChanCfg, MmwDemo_message_body_u::cqSatMonCfg, MmwDemo_CliCommonCfg_t_::cqSatMonCfg, MmwDemo_message_body_u::cqSigImgMonCfg, MmwDemo_CliCommonCfg_t_::cqSigImgMonCfg, MmwDemo_message_body_u::dataLogger, MmwDemo_Cfg_t::dataLogger, MmwDemo_DSS_MCB_t::dataPathContext, MmwDemo_DSS_MCB_t::dataPathObj, MmwDemo_DSS_DataPathObj_t::dcRangeSigCalibCntr, MmwDemo_DSS_MCB_t::eventHandle, MmwDemo_message_body_u::extendedMaxVelocityCfg, MmwDemo_message_body_u::guiMonSel, MmwDemo_timingInfo::interFrameProcessingEndTime, MmwDemo_DSS_dataPathContext_t_::interFrameProcToken, MmwDemo_DSS_DataPathObj_t::log2NumAvgChirps, MmwDemo_DSS_MCB_t::loggingBufferAvailable, MmwDemo_message_body_u::lvdsStreamCfg, MmwDemo_DSS_MCB_t::mboxSemHandle, MmwDemo_message_body_u::measureRxChanCfg, MmwDemo_CliCommonCfg_t_::measureRxChanCfg, MmwDemo_cfgUpdate(), MmwDemo_checkDynamicConfigErrors(), MmwDemo_DSS_STATE_STOP_PENDING, MmwDemo_dssAssert, MmwDemo_dssDataPathReconfig(), MmwDemo_floorLog2(), MmwDemo_mboxCallback(), MMWDEMO_MSS2DSS_ADCBUFCFG, MMWDEMO_MSS2DSS_ANALOG_MONITOR, MMWDEMO_MSS2DSS_BPM_CFG, MMWDEMO_MSS2DSS_CALIB_DC_RANGE_SIG, MMWDEMO_MSS2DSS_CFAR_DOPPLER_CFG, MMWDEMO_MSS2DSS_CFAR_RANGE_CFG, MMWDEMO_MSS2DSS_CLUTTER_REMOVAL, MMWDEMO_MSS2DSS_COMP_RANGE_BIAS_AND_RX_CHAN_PHASE, MMWDEMO_MSS2DSS_CQ_SATURATION_MONITOR, MMWDEMO_MSS2DSS_CQ_SIGIMG_MONITOR, MMWDEMO_MSS2DSS_DETOBJ_SHIPPED, MMWDEMO_MSS2DSS_EXTENDED_MAX_VELOCITY, MMWDEMO_MSS2DSS_GUIMON_CFG, MMWDEMO_MSS2DSS_LVDSSTREAM_CFG, MMWDEMO_MSS2DSS_MEASURE_RANGE_BIAS_AND_RX_CHAN_PHASE, MMWDEMO_MSS2DSS_MULTI_OBJ_BEAM_FORM, MMWDEMO_MSS2DSS_NEAR_FIELD_CFG, MMWDEMO_MSS2DSS_PEAK_GROUPING_CFG, MMWDEMO_MSS2DSS_SET_DATALOGGER, MMWDEMO_STOP_COMPLETE_EVT, MMWDEMO_SUBFRAME_NUM_FRAME_LEVEL_CONFIG, MmwDemo_message_body_u::multiObjBeamFormingCfg, MmwDemo_message_body_u::nearFieldCorrectionCfg, MmwDemo_CalibDcRangeSigCfg_t::numAvgChirps, MmwDemo_DSS_MCB_t::numSubFrames, MmwDemo_message_body_u::peakGroupingCfg, MmwDemo_DSS_MCB_t::peerMailbox, MmwDemo_DSS_MCB_t::state, MmwDemo_DSS_MCB_t::subFrameIndx, MmwDemo_message_t::subFrameNum, MmwDemo_timingInfo::subFrameSwitchingCycles, MmwDemo_DSS_DataPathObj_t::timingInfo, MmwDemo_timingInfo::transmitOutputCycles, and MmwDemo_message_t::type.
Referenced by MmwDemo_dssInitTask().
static int32_t MmwDemo_mboxWrite (MmwDemo_message * message) static
Description
Function to send a message to peer through Mailbox virtural channel
Parameters
[in] message Pointer to the Captuere demo message.
Return values
Success - 0 Fail < -1
Definition at line 568 of file dss_main.c.
References MmwDemo_DSS_MCB_t::peerMailbox.
Referenced by _MmwDemo_dssAssert(), MmwDemo_dssDataPathStop(), MmwDemo_dssInitTask(), MmwDemo_dssSendProcessOutputToMSS(), and MmwDemo_measurementResultOutput().
void MmwDemo_measurementResultOutput (MmwDemo_DSS_DataPathObj * obj) static
Description
Sends DSS range bias and rx channel phase offset measurement information to MSS
Return values
Not Applicable.
Definition at line 2884 of file dss_main.c.
References MmwDemo_message_t::body, MmwDemo_DSS_DataPathObj_t::cliCommonCfg, MmwDemo_message_body_u::compRxChanCfg, MmwDemo_CliCommonCfg_t_::compRxChanCfg, MMWDEMO_DSS2MSS_MEASUREMENT_INFO, MmwDemo_mboxWrite(), and MmwDemo_message_t::type.
Referenced by MmwDemo_dssDataPathProcessEvents().
void MmwDemo_parseAdcBufCfg (MmwDemo_DSS_DataPathObj * dataPathObj)
Description
This function ADCBuf configuration and save info in datapath object to be used by data path modules.
Definition at line 2044 of file dss_main.c.
References MmwDemo_CliCfg_t_::adcBufCfg, MmwDemo_ADCBufCfg_t::adcFmt, MmwDemo_DSS_DataPathObj_t::cfg, MmwDemo_ADCBufCfg_t::chInterleave, MmwDemo_ADCBufCfg_t::chirpThreshold, MmwDemo_DSS_DataPathObj_t::cliCfg, MmwDemo_dssAssert, MmwDemo_DSS_DataPathObj_t::numAdcSamples, MmwDemo_DSS_DataPathObj_t::numBytePerSample, MmwDemo_DSS_DataPathObj_t::numChirpsPerChirpEvent, MmwDemo_DSS_DataPathObj_t::numChirpsPerFrame, MmwDemo_DSS_DataPathObj_t::numRxAntennas, MmwDemo_Cfg_t::openCfg, SOC_XWR16XX_DSS_ADCBUF_SIZE, and SYS_COMMON_CQ_MAX_CHIRP_THRESHOLD.
Referenced by MmwDemo_dssDataPathConfig().
bool MmwDemo_parseProfileAndChirpConfig (MmwDemo_DSS_DataPathObj * dataPathObj, MMWave_CtrlCfg * ptrCtrlCfg, uint8_t subFrameIndx)
Description
parses Profile, Chirp and Frame config and extracts parameters needed for processing chain configuration
Definition at line 1738 of file dss_main.c.
References MmwDemo_CliCfg_t_::bpmCfg, MmwDemo_DSS_MCB_t::cfg, MmwDemo_DSS_DataPathObj_t::cliCfg, MmwDemo_DSS_DataPathObj_t::cliCommonCfg, MmwDemo_CliCommonCfg_t_::compRxChanCfg, MmwDemo_DSS_DataPathObj_t::compRxChanCfg, MmwDemo_MultiObjBeamFormingCfg_t::enabled, MmwDemo_ExtendedMaxVelocityCfg_t::enabled, MmwDemo_CliCfg_t_::extendedMaxVelocityCfg, cmplx16ImRe_t_::imag, MmwDemo_BpmCfg_t::isEnabled, MMW_NUM_ANGLE_BINS, MmwDemo_dssAssert, MmwDemo_floorLog2(), MmwDemo_getChirpEndIdx(), MmwDemo_getChirpStartIdx(), MmwDemo_getNumLoops(), MmwDemo_getProfileHandle(), MmwDemo_pow2roundup(), MMWDEMO_SPEED_OF_LIGHT_IN_METERS_PER_SEC, MmwDemo_CliCfg_t_::multiObjBeamFormingCfg, MmwDemo_DSS_DataPathObj_t::numAdcSamples, MmwDemo_DSS_DataPathObj_t::numAngleBins, MmwDemo_DSS_DataPathObj_t::numChirpsPerFrame, MmwDemo_DSS_DataPathObj_t::numDopplerBins, MmwDemo_DSS_DataPathObj_t::numRangeBins, MmwDemo_DSS_DataPathObj_t::numRxAntennas, MmwDemo_DSS_DataPathObj_t::numTxAntennas, MmwDemo_DSS_DataPathObj_t::numVirtualAntAzim, MmwDemo_DSS_DataPathObj_t::numVirtualAntElev, MmwDemo_DSS_DataPathObj_t::numVirtualAntennas, MmwDemo_Cfg_t::openCfg, MmwDemo_DSS_DataPathObj_t::rangeResolution, cmplx16ImRe_t_::real, MmwDemo_compRxChannelBiasCfg_t_::rxChPhaseComp, SYS_COMMON_NUM_RX_CHANNEL, SYS_COMMON_NUM_TX_ANTENNAS, MmwDemo_DSS_DataPathObj_t::validProfileIdx, and MmwDemo_DSS_DataPathObj_t::xyzOutputQFormat.
Referenced by MmwDemo_dssDataPathConfig().
void MmwDemo_sleep (void)
Description
Function to sleep the DSP using IDLE instruction. When DSP has no work left to do, the BIOS will be in Idle thread and will call this function. The DSP will wake-up on any interrupt (e.g chirp interrupt).
Return values
Not Applicable.
Description
Function to sleep the R4F using WFI (Wait For Interrupt) instruction. When R4F has no work left to do, the BIOS will be in Idle thread and will call this function. The R4F will wake-up on any interrupt (e.g chirp interrupt).
Return values
Not Applicable.
Definition at line 2840 of file dss_main.c.
static void MmwDemo_triggerDss2MssISR (uint8_t dss2MssIsrInfo) static
Description
Function to trigger DSS to MSS ISR for fast signalling
Return values
Not Applicable.
Definition at line 1162 of file dss_main.c.
References MmwDemo_HSRAM_t_::dss2MssIsrInfo, MMWDEMO_DSS2MSS_EXCEPTION_SIGNALLING_SW_INT_DSS, and MmwDemo_DSS_MCB_t::socHandle.
Referenced by MmwDemo_dssChirpIntHandler(), and MmwDemo_dssFrameStartIntHandler().
Variable Documentation
far COPY_TABLE _MmwDemo_fastCode_L1PSRAM_copy_table
Referenced by MmwDemo_dssDataPathInit().
uint8_t gCQRxSatMonMemory[SYS_COMMON_CQ_MAX_CHIRP_THRESHOLD *(RL_NUM_MON_SLICES_MAX+1)]
Definition at line 139 of file dss_main.c.
Referenced by MmwDemo_dssDataPathConfigCQ().
uint16_t gCQRxSigImgMemory[SYS_COMMON_CQ_MAX_CHIRP_THRESHOLD *(RL_NUM_MON_SLICES_MAX+1)]
Definition at line 145 of file dss_main.c.
Referenced by MmwDemo_dssDataPathConfigCQ().
volatile cycleLog_t gCycleLog
Definition at line 175 of file dss_main.c.
MmwDemo_HSRAM_t gHSRAM
Definition at line 133 of file dss_main.c.
MmwDemo_DSS_MCB gMmwDssMCB
Global Variable for tracking information required by the mmw Demo.
Definition at line 173 of file dss_main.c.
Copyright 2018, Texas Instruments Incorporated