xwr16xx/mmw/dss/dss_data_path.h File Reference
dss_data_path.h File Reference
This is the data path processing header.
#include <ti/sysbios/knl/Semaphore.h>
#include <ti/common/sys_common.h>
#include <ti/common/mmwave_error.h>
#include <ti/demo/io_interface/mmw_config.h>
#include <ti/drivers/adcbuf/ADCBuf.h>
#include <ti/drivers/edma/edma.h>
#include <ti/demo/io_interface/detected_obj.h>
Data Structures
struct cycleLog_t_
DSP cycle profiling structure to accumulate different processing times in chirp and frame processing periods.
struct MmwDemo_objRaw
Parameters of CFAR detected object during the first round of CFAR detections.
struct MmwDemo_1D_DopplerLines
Active Doppler lines, lines (bins) on which the CFAR detector detected objects during the detections in Doppler direction.
struct MmwDemo_timingInfo
Timing information.
struct MmwDemo_DSS_dataPathContext_t_
Millimeter Wave Demo Data Path Context.
struct MmwDemo_DSS_DataPathCQConfig_t
Millimeter Wave Demo Data Path CQ configuration.
struct MmwDemo_DSS_DataPathObj_t
Millimeter Wave Demo Data Path Information.
Macros
#define BYTES_PER_SAMP_1D (2*sizeof(int16_t)) /*16 bit real, 16 bit imaginary => 4 bytes */
#define BYTES_PER_SAMP_2D (2*sizeof(int32_t)) /*32 bit real, 32 bit imaginary => 8 bytes */
#define BYTES_PER_SAMP_DET sizeof(uint16_t) /*pre-detection matrix is 16 bit unsigned =>2 bytes*/
#define MMW_MAX_OBJ_OUT 100
#define MAX_DET_OBJECTS_RAW 2048 /* same as xwr14xx, should not exceed 65536 */
#define DET_THRESH_MULT 25
#define DET_THRESH_SHIFT 5
#define DET_GUARD_LEN 4
#define DET_NOISE_LEN 16
#define PI_ 3.1415926535897
#define ONE_Q15 (1 << 15)
#define ONE_Q19 (1 << 19)
#define ONE_Q8 (1 << 8)
#define MMW_PEAK_GROUPING_DET_MATRIX_BASED 1
#define MMW_PEAK_GROUPING_CFAR_PEAK_BASED 2
#define MMW_NOISE_AVG_MODE_CFAR_CA ((uint8_t)0U)
#define MMW_NOISE_AVG_MODE_CFAR_CAGO ((uint8_t)1U)
#define MMW_NOISE_AVG_MODE_CFAR_CASO ((uint8_t)2U)
Typedefs
typedef struct cycleLog_t_ cycleLog_t
DSP cycle profiling structure to accumulate different processing times in chirp and frame processing periods.
typedef struct MmwDemo_objRaw MmwDemo_objRaw_t
Parameters of CFAR detected object during the first round of CFAR detections.
typedef struct MmwDemo_1D_DopplerLines MmwDemo_1D_DopplerLines_t
Active Doppler lines, lines (bins) on which the CFAR detector detected objects during the detections in Doppler direction.
typedef struct MmwDemo_timingInfo MmwDemo_timingInfo_t
Timing information.
typedef struct MmwDemo_DSS_dataPathContext_t_ MmwDemo_DSS_dataPathContext_t
Millimeter Wave Demo Data Path Context.
typedef struct MmwDemo_DSS_DataPathCQConfig_t MmwDemo_DSS_DataPathCQ
Millimeter Wave Demo Data Path CQ configuration.
typedef struct MmwDemo_DSS_DataPathObj_t MmwDemo_DSS_DataPathObj
Millimeter Wave Demo Data Path Information.
Functions
void MmwDemo_dataPathObjInit (MmwDemo_DSS_DataPathObj *obj, MmwDemo_DSS_dataPathContext_t *context, MmwDemo_CliCfg_t *cliCfg, MmwDemo_CliCommonCfg_t *cliCommonCfg, MmwDemo_Cfg *cfg)
void MmwDemo_dataPathInit1Dstate (MmwDemo_DSS_DataPathObj *obj)
void MmwDemo_dataPathDeleteSemaphore (MmwDemo_DSS_dataPathContext_t *context)
int32_t MmwDemo_dataPathInitEdma (MmwDemo_DSS_dataPathContext_t *context)
int32_t MmwDemo_dataPathConfigEdma (MmwDemo_DSS_DataPathObj *obj)
int32_t MmwDemo_dataPathConfigCQEdma (MmwDemo_DSS_DataPathObj *obj)
void MmwDemo_dataPathConfigBuffers (MmwDemo_DSS_DataPathObj *obj, uint32_t adcBufAddress)
void MmwDemo_dataPathComputeDerivedConfig (MmwDemo_DSS_DataPathObj *obj)
void MmwDemo_dataPathConfigFFTs (MmwDemo_DSS_DataPathObj *obj)
void MmwDemo_waitEndOfChirps (MmwDemo_DSS_DataPathObj *obj)
void MmwDemo_processChirp (MmwDemo_DSS_DataPathObj *obj, uint16_t chirpIndxInMultiChirp)
void MmwDemo_interFrameProcessing (MmwDemo_DSS_DataPathObj *obj)
uint32_t MmwDemo_pow2roundup (uint32_t x)
void MmwDemo_checkDynamicConfigErrors (MmwDemo_DSS_DataPathObj *obj)
void MmwDemo_dssDataPathStartCQEdma (MmwDemo_DSS_DataPathObj *ptrDataPathObj)
Detailed Description
This is the data path processing header.
NOTE: (C) Copyright 2016 Texas Instruments, Inc.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Texas Instruments Incorporated nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file dss_data_path.h.
Macro Definition Documentation
#define BYTES_PER_SAMP_1D (2*sizeof(int16_t)) /*16 bit real, 16 bit imaginary => 4 bytes */
Definition at line 55 of file dss_data_path.h.
Referenced by MmwDemo_dataPathConfigEdma().
#define BYTES_PER_SAMP_2D (2*sizeof(int32_t)) /*32 bit real, 32 bit imaginary => 8 bytes */
Definition at line 56 of file dss_data_path.h.
#define BYTES_PER_SAMP_DET sizeof(uint16_t) /*pre-detection matrix is 16 bit unsigned =>2 bytes*/
Definition at line 57 of file dss_data_path.h.
Referenced by MmwDemo_dataPathConfigEdma().
#define DET_GUARD_LEN 4
Definition at line 64 of file dss_data_path.h.
#define DET_NOISE_LEN 16
Definition at line 65 of file dss_data_path.h.
#define DET_THRESH_MULT 25
Definition at line 62 of file dss_data_path.h.
#define DET_THRESH_SHIFT 5
Definition at line 63 of file dss_data_path.h.
#define MAX_DET_OBJECTS_RAW 2048 /* same as xwr14xx, should not exceed 65536 */
Definition at line 61 of file dss_data_path.h.
Referenced by MmwDemo_dataPathConfigBuffers(), and MmwDemo_interFrameProcessing().
#define MMW_MAX_OBJ_OUT 100
Definition at line 60 of file dss_data_path.h.
#define MMW_NOISE_AVG_MODE_CFAR_CA ((uint8_t)0U)
cumulative average of the side (left or right) that is greater
Definition at line 78 of file dss_data_path.h.
#define MMW_NOISE_AVG_MODE_CFAR_CAGO ((uint8_t)1U)
cumulative average of the side (left or right) that is smaller
Definition at line 80 of file dss_data_path.h.
#define MMW_NOISE_AVG_MODE_CFAR_CASO ((uint8_t)2U)
Definition at line 82 of file dss_data_path.h.
#define MMW_PEAK_GROUPING_CFAR_PEAK_BASED 2
cumulative average of left+right
Definition at line 75 of file dss_data_path.h.
Referenced by MmwDemo_interFrameProcessing().
#define MMW_PEAK_GROUPING_DET_MATRIX_BASED 1
Peak grouping scheme of CFAR detected objects based only on peaks of neighboring cells that are already detected by CFAR
Definition at line 73 of file dss_data_path.h.
Referenced by MmwDemo_interFrameProcessing().
#define ONE_Q15 (1 << 15)
Definition at line 68 of file dss_data_path.h.
Referenced by MmwDemo_dataPathConfigFFTs(), and MmwDemo_genDftSinCosTable().
#define ONE_Q19 (1 << 19)
Definition at line 69 of file dss_data_path.h.
Referenced by MmwDemo_dataPathConfigFFTs().
#define ONE_Q8 (1 << 8)
Peak grouping scheme of CFAR detected objects based on peaks of neighboring cells taken from detection matrix
Definition at line 70 of file dss_data_path.h.
#define PI_ 3.1415926535897
Definition at line 67 of file dss_data_path.h.
Referenced by MmwDemo_genDftSinCosTable(), MmwDemo_genWindow(), and MmwDemo_nearFieldCorrection().
Typedef Documentation
typedef struct cycleLog_t_ cycleLog_t
DSP cycle profiling structure to accumulate different processing times in chirp and frame processing periods.
typedef struct MmwDemo_1D_DopplerLines MmwDemo_1D_DopplerLines_t
Active Doppler lines, lines (bins) on which the CFAR detector detected objects during the detections in Doppler direction.
typedef struct MmwDemo_DSS_dataPathContext_t_ MmwDemo_DSS_dataPathContext_t
Millimeter Wave Demo Data Path Context.
The structure is used to hold common context among data path objects.
typedef struct MmwDemo_DSS_DataPathCQConfig_t MmwDemo_DSS_DataPathCQ
Millimeter Wave Demo Data Path CQ configuration.
The structure is used to hold all the relevant information for the data path CQ.
typedef struct MmwDemo_DSS_DataPathObj_t MmwDemo_DSS_DataPathObj
Millimeter Wave Demo Data Path Information.
The structure is used to hold all the relevant information for the data path.
typedef struct MmwDemo_objRaw MmwDemo_objRaw_t
Parameters of CFAR detected object during the first round of CFAR detections.
typedef struct MmwDemo_timingInfo MmwDemo_timingInfo_t
Timing information.
Function Documentation
void MmwDemo_checkDynamicConfigErrors (MmwDemo_DSS_DataPathObj * obj)
Description
Perform error checking for configurations that can change dynamically after start sensor has been issued e.g multi object, peakGrouping etc Ideally these checks should be done when the configuration commands are issued but this blows up code size because for each command there needs to be checking with current state related to other commands. So doing it in run-time (real-time) is cheaper with some expenditure of cycles to do the checks. If there is error exception message will be generated.
Return values
None
Definition at line 3947 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::cliCfg, MmwDemo_MultiObjBeamFormingCfg_t::enabled, MmwDemo_ExtendedMaxVelocityCfg_t::enabled, MmwDemo_NearFieldCorrectionCfg_t::enabled, MmwDemo_CliCfg_t_::extendedMaxVelocityCfg, MmwDemo_dssAssert, MmwDemo_CliCfg_t_::multiObjBeamFormingCfg, MmwDemo_CliCfg_t_::nearFieldCorrectionCfg, and MmwDemo_DSS_DataPathObj_t::numTxAntennas.
Referenced by MmwDemo_mboxReadTask().
void MmwDemo_dataPathComputeDerivedConfig (MmwDemo_DSS_DataPathObj * obj)
Description
Configures azimuth heat map related processing.
Return values
Not Applicable.
Definition at line 3484 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::log2NumDopplerBins, MmwDemo_dssAssert, MmwDemo_floorLog2(), and MmwDemo_DSS_DataPathObj_t::numDopplerBins.
Referenced by MmwDemo_dssDataPathConfig().
void MmwDemo_dataPathConfigBuffers (MmwDemo_DSS_DataPathObj * obj, uint32_t adcBufAddress)
Description
Creates heap in L2 and L3 and allocates data path buffers, The heap is destroyed at the end of the function.
Return values
Not Applicable.
Definition at line 3496 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::ADCdataBuf, MmwDemo_DSS_DataPathObj_t::adcDataIn, ALIGN, MmwDemo_CliCfg_t_::bpmCfg, MmwDemo_DSS_DataPathObj_t::cliCfg, DC_RANGE_SIGNATURE_COMP_MAX_BIN_SIZE, MmwDemo_DSS_DataPathObj_t::detDopplerLines, MmwDemo_1D_DopplerLines::dopplerLineMask, MmwDemo_1D_DopplerLines::dopplerLineMaskLen, gMmwL1, gMmwL2, gMmwL3, MmwDemo_BpmCfg_t::isEnabled, MAX, MAX_DET_OBJECTS_RAW, MMW_ALLOC_BUF, MMW_L1_HEAP_SIZE, MMW_L2_HEAP_SIZE, MMW_MAX_OBJ_OUT, MmwDemo_dssAssert, MMWDEMO_MEMORY_ALLOC_DOUBLE_WORD_ALIGN, MMWDEMO_MEMORY_ALLOC_MAX_STRUCT_ALIGN, MmwDemo_printHeapStats(), MmwDemo_DSS_DataPathObj_t::numAdcSamples, MmwDemo_DSS_DataPathObj_t::numAngleBins, MmwDemo_DSS_DataPathObj_t::numDopplerBins, MmwDemo_DSS_DataPathObj_t::numRangeBins, MmwDemo_DSS_DataPathObj_t::numRxAntennas, MmwDemo_DSS_DataPathObj_t::numTxAntennas, MmwDemo_DSS_DataPathObj_t::numVirtualAntAzim, SOC_MAX_NUM_RX_ANTENNAS, SOC_MAX_NUM_TX_ANTENNAS, and SOC_XWR16XX_DSS_L3RAM_SIZE.
Referenced by MmwDemo_dssDataPathConfig().
int32_t MmwDemo_dataPathConfigCQEdma (MmwDemo_DSS_DataPathObj * obj)
Description
Configures EDMA driver for data path CQ processing.
Return values
Not Applicable.
Description
Configures all EDMA channels and param sets used in data path processing
Parameters
[in] obj Pointer to data path object
Return values
-1 if error, 0 for no error
Definition at line 1262 of file dss_data_path.c.
References MmwDemo_DSS_DataPathCQConfig_t::anaMonCfg, MmwDemo_DSS_DataPathObj_t::context, MmwDemo_DSS_DataPathObj_t::datapathCQ, MmwDemo_DSS_dataPathContext_t_::edmaHandle, EDMAutil_configType1(), MMW_DATA_PATH_EDMA_INSTANCE, MMW_EDMA_CH_RX_SATURATION_MON, MMW_EDMA_CH_SIGIMG_MON, MmwDemo_EDMA_CQTransferCompletionCallbackFxn(), MmwDemo_DSS_DataPathCQConfig_t::rxSatData, MmwDemo_AnaMonitorCfg_t::rxSatMonEn, MmwDemo_DSS_DataPathCQConfig_t::satMonAddr, MmwDemo_DSS_DataPathCQConfig_t::satMonTotalSize, MmwDemo_DSS_DataPathCQConfig_t::sigImgData, MmwDemo_DSS_DataPathCQConfig_t::sigImgMonAddr, MmwDemo_AnaMonitorCfg_t::sigImgMonEn, and MmwDemo_DSS_DataPathCQConfig_t::sigImgMonTotalSize.
Referenced by MmwDemo_dataPathConfigEdma().
int32_t MmwDemo_dataPathConfigEdma (MmwDemo_DSS_DataPathObj * obj)
Description
Configures EDMA driver for all of the data path processing.
Return values
Not Applicable.
Description
Configures all EDMA channels and param sets used in data path processing
Parameters
[in] obj Pointer to data path object
Return values
-1 if error, 0 for no error
Definition at line 1355 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::ADCdataBuf, MmwDemo_DSS_DataPathObj_t::adcDataIn, BYTES_PER_SAMP_1D, BYTES_PER_SAMP_DET, MmwDemo_DSS_DataPathObj_t::context, MmwDemo_DSS_dataPathContext_t_::edmaHandle, EDMAutil_configType1(), EDMAutil_configType2b(), EDMAutil_configType3(), MAX, MMW_DATA_PATH_EDMA_INSTANCE, MMW_EDMA_CH_1D_IN_PING, MMW_EDMA_CH_1D_IN_PING_SHADOW, MMW_EDMA_CH_1D_IN_PONG, MMW_EDMA_CH_1D_IN_PONG_SHADOW, MMW_EDMA_CH_1D_OUT_PING, MMW_EDMA_CH_1D_OUT_PING_SHADOW, MMW_EDMA_CH_1D_OUT_PONG, MMW_EDMA_CH_1D_OUT_PONG_SHADOW, MMW_EDMA_CH_2D_IN_PING, MMW_EDMA_CH_2D_IN_PING_SHADOW, MMW_EDMA_CH_2D_IN_PONG, MMW_EDMA_CH_2D_IN_PONG_SHADOW, MMW_EDMA_CH_3D_IN_PING, MMW_EDMA_CH_3D_IN_PING_SHADOW, MMW_EDMA_CH_3D_IN_PONG, MMW_EDMA_CH_3D_IN_PONG_SHADOW, MMW_EDMA_CH_DET_MATRIX, MMW_EDMA_CH_DET_MATRIX2, MMW_EDMA_CH_DET_MATRIX2_SHADOW, MMW_EDMA_CH_DET_MATRIX_SHADOW, MmwDemo_dataPathConfigCQEdma(), MmwDemo_DSS_DataPathObj_t::numAdcSamples, MmwDemo_DSS_DataPathObj_t::numChirpsPerChirpEvent, MmwDemo_DSS_DataPathObj_t::numRxAntennas, MmwDemo_AnaMonitorCfg_t::rxSatMonEn, and MmwDemo_AnaMonitorCfg_t::sigImgMonEn.
Referenced by MmwDemo_dssDataPathReconfig().
void MmwDemo_dataPathConfigFFTs (MmwDemo_DSS_DataPathObj * obj)
Description
Configures FFTs (twiddle tables etc) involved in 1D, 2D and Azimuth processing.
Return values
Not Applicable.
Definition at line 3796 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::azimuthModCoefs, MmwDemo_DSS_DataPathObj_t::azimuthModCoefsHalfBin, MmwDemo_DSS_DataPathObj_t::azimuthTwiddle32x32, FFT_WINDOW_INT16, FFT_WINDOW_INT32, MMW_WIN_BLACKMAN, MMW_WIN_HANNING, MmwDemo_gen_twiddle_fft16x16_fast(), MmwDemo_gen_twiddle_fft32x32_fast(), MmwDemo_genDftSinCosTable(), MmwDemo_genWindow(), MmwDemo_DSS_DataPathObj_t::numAdcSamples, MmwDemo_DSS_DataPathObj_t::numAngleBins, MmwDemo_DSS_DataPathObj_t::numDopplerBins, MmwDemo_DSS_DataPathObj_t::numRangeBins, ONE_Q15, ONE_Q19, MmwDemo_DSS_DataPathObj_t::twiddle16x16_1D, MmwDemo_DSS_DataPathObj_t::twiddle32x32_2D, MmwDemo_DSS_DataPathObj_t::window1D, and MmwDemo_DSS_DataPathObj_t::window2D.
Referenced by MmwDemo_dssDataPathReconfig().
void MmwDemo_dataPathDeleteSemaphore (MmwDemo_DSS_dataPathContext_t * context)
Description
Delete Semaphores which are created in MmwDemo_dataPathInitEdma().
Return values
Not Applicable.
Definition at line 3383 of file dss_data_path.c.
void MmwDemo_dataPathInit1Dstate (MmwDemo_DSS_DataPathObj * obj)
Description
Initializes data path state variables for 1D processing.
Return values
Not Applicable.
Definition at line 3373 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::chirpCount, MmwDemo_DSS_DataPathObj_t::dopplerBinCount, and MmwDemo_DSS_DataPathObj_t::txAntennaCount.
Referenced by MmwDemo_dssDataPathInit().
int32_t MmwDemo_dataPathInitEdma (MmwDemo_DSS_dataPathContext_t * context)
Description
Initializes EDMA driver.
Return values
Not Applicable.
Definition at line 3409 of file dss_data_path.c.
References MmwDemo_DSS_dataPathContext_t_::edmaHandle, MmwDemo_edmaErrorCallbackFxn(), and MmwDemo_edmaTransferControllerErrorCallbackFxn().
Referenced by MmwDemo_dssDataPathInit().
void MmwDemo_dataPathObjInit (MmwDemo_DSS_DataPathObj * obj, MmwDemo_DSS_dataPathContext_t * context, MmwDemo_CliCfg_t * cliCfg, MmwDemo_CliCommonCfg_t * cliCommonCfg, MmwDemo_Cfg * cfg)
Description
Initializes data path object with supplied context and cli Config. The context and cli config point to permanent storage outside of data path object that data path object can refer to anytime during the lifetime of data path object. Data path default values that are not required to come through CLI commands are set in this function.
Return values
Not Applicable.
Definition at line 3360 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::cfg, MmwDemo_DSS_DataPathObj_t::cliCfg, MmwDemo_DSS_DataPathObj_t::cliCommonCfg, and MmwDemo_DSS_DataPathObj_t::context.
Referenced by MmwDemo_dssDataPathInit().
void MmwDemo_dssDataPathStartCQEdma (MmwDemo_DSS_DataPathObj * ptrDataPathObj)
Description
Start CQ EDMA
Parameters
[in] obj Pointer to data path object
Return values
None Description
Function to configure CQ.
Parameters
[in] ptrDataPathObj Pointer to data path object.
Return values
0 if no error, else error (there will be system prints for these).
Definition at line 1326 of file dss_data_path.c.
References MmwDemo_DSS_DataPathCQConfig_t::anaMonCfg, MmwDemo_DSS_DataPathObj_t::context, MmwDemo_DSS_DataPathObj_t::datapathCQ, MmwDemo_DSS_dataPathContext_t_::edmaHandle, MMW_DATA_PATH_EDMA_INSTANCE, MMW_EDMA_CH_RX_SATURATION_MON, MMW_EDMA_CH_SIGIMG_MON, MmwDemo_AnaMonitorCfg_t::rxSatMonEn, and MmwDemo_AnaMonitorCfg_t::sigImgMonEn.
Referenced by MmwDemo_dssDataPathProcessEvents().
void MmwDemo_interFrameProcessing (MmwDemo_DSS_DataPathObj * obj)
Description
Interframe processing. It is called from MmwDemo_dssDataPathProcessEvents after all chirps of the frame have been received and 1D FFT processing on them has been completed.
Return values
Not Applicable.
Definition at line 2550 of file dss_data_path.c.
References MmwDemo_CfarCfg_t::averageMode, MmwDemo_DSS_DataPathObj_t::azimuthIn, MmwDemo_DSS_DataPathObj_t::azimuthMagSqr, MmwDemo_DSS_DataPathObj_t::azimuthModCoefs, MmwDemo_DSS_DataPathObj_t::azimuthModCoefsHalfBin, MmwDemo_DSS_DataPathObj_t::azimuthOut, MmwDemo_DSS_DataPathObj_t::azimuthStaticHeatMap, MmwDemo_DSS_DataPathObj_t::azimuthTwiddle32x32, MmwDemo_CliCfg_t_::bpmCfg, MmwDemo_CliCfg_t_::cfarCfgDoppler, MmwDemo_CliCfg_t_::cfarCfgRange, MmwDemo_DSS_DataPathObj_t::cfarDetObjIndexBuf, MmwDemo_DSS_DataPathObj_t::cliCfg, MmwDemo_DSS_DataPathObj_t::cliCommonCfg, MmwDemo_CliCfg_t_::clutterRemovalCfg, MmwDemo_CliCommonCfg_t_::compRxChanCfg, MmwDemo_DSS_DataPathObj_t::compRxChanCfg, MmwDemo_DSS_DataPathObj_t::context, MmwDemo_DSS_DataPathObj_t::detDopplerLines, MmwDemo_DSS_DataPathObj_t::detMatrix, MmwDemo_DSS_DataPathObj_t::detObj2D, MmwDemo_DSS_DataPathObj_t::detObj2DRaw, DOPPLER_IDX_TO_UNSIGNED, MmwDemo_objRaw::dopplerIdx, MmwDemo_DSS_DataPathObj_t::dstPingPong, MmwDemo_DSS_dataPathContext_t_::edmaHandle, EDMAutil_triggerType3(), MmwDemo_ExtendedMaxVelocityCfg_t::enabled, MmwDemo_NearFieldCorrectionCfg_t::enabled, MmwDemo_ClutterRemovalCfg_t::enabled, MmwDemo_measureRxChannelBiasCfg_t_::enabled, MmwDemo_NearFieldCorrectionCfg_t::endRangeIdx, MmwDemo_CliCfg_t_::extendedMaxVelocityCfg, MmwDemo_DSS_DataPathObj_t::fftOut2D, MmwDemo_CfarCfg_t::guardLen, cmplx16ReIm_t_::imag, cmplx16ImRe_t_::imag, cmplx32ReIm_t_::imag, MmwDemo_PeakGroupingCfg_t::inDopplerDirectionEn, MmwDemo_PeakGroupingCfg_t::inRangeDirectionEn, cycleLog_t_::interFrameProcessingTime, cycleLog_t_::interFrameWaitTime, MmwDemo_BpmCfg_t::isEnabled, isPong, MmwDemo_DSS_DataPathObj_t::log2NumDopplerBins, MAX_DET_OBJECTS_RAW, MmwDemo_PeakGroupingCfg_t::maxRangeIndex, MmwDemo_CliCommonCfg_t_::measureRxChanCfg, MmwDemo_PeakGroupingCfg_t::minRangeIndex, MMW_DATA_PATH_EDMA_INSTANCE, MMW_EDMA_CH_2D_IN_PING, MMW_EDMA_CH_2D_IN_PONG, MMW_EDMA_CH_3D_IN_PING, MMW_EDMA_CH_3D_IN_PONG, MMW_EDMA_CH_DET_MATRIX, MMW_EDMA_CH_DET_MATRIX2, MMW_EDMA_TRIGGER_DISABLE, MMW_EDMA_TRIGGER_ENABLE, MMW_PEAK_GROUPING_CFAR_PEAK_BASED, MMW_PEAK_GROUPING_DET_MATRIX_BASED, MmwDemo_addDopplerCompensation(), MmwDemo_cfarPeakGrouping(), MmwDemo_cfarPeakGroupingCfarQualified(), MmwDemo_dataPathWait2DInputData(), MmwDemo_dataPathWait3DInputData(), MmwDemo_dataPathWaitTransDetMatrix(), MmwDemo_dataPathWaitTransDetMatrix2(), MmwDemo_decodeBPM(), MmwDemo_dssAssert, MmwDemo_getDopplerLine(), MmwDemo_isSetDopplerLine(), MmwDemo_log2AbsAccum(), MmwDemo_magnitudeSquared(), MmwDemo_nearFieldCorrection(), MmwDemo_rangeBiasRxChPhaseMeasure(), MmwDemo_resetDopplerLines(), MmwDemo_rxChanPhaseBiasCompensation(), MmwDemo_setDopplerLine(), MmwDemo_XYestimation(), MmwDemo_Yestimation(), MmwDemo_CliCfg_t_::nearFieldCorrectionCfg, MmwDemo_CfarCfg_t::noiseDivShift, MmwDemo_DSS_DataPathObj_t::numAngleBins, MmwDemo_DSS_DataPathObj_t::numDetObj, MmwDemo_DSS_DataPathObj_t::numDetObjRaw, MmwDemo_DSS_DataPathObj_t::numDopplerBins, MmwDemo_DSS_DataPathObj_t::numRangeBins, MmwDemo_DSS_DataPathObj_t::numRxAntennas, MmwDemo_DSS_DataPathObj_t::numTxAntennas, MmwDemo_DSS_DataPathObj_t::numVirtualAntAzim, MmwDemo_DSS_DataPathObj_t::numVirtualAntennas, MmwDemo_CliCfg_t_::peakGroupingCfg, MmwDemo_objRaw::peakVal, pingPongId, MmwDemo_DSS_DataPathObj_t::radarCube, MmwDemo_objRaw::rangeIdx, MmwDemo_DSS_DataPathObj_t::rangeResolution, cmplx16ReIm_t_::real, cmplx16ImRe_t_::real, cmplx32ReIm_t_::real, MmwDemo_compRxChannelBiasCfg_t_::rxChPhaseComp, MmwDemo_PeakGroupingCfg_t::scheme, MmwDemo_measureRxChannelBiasCfg_t_::searchWinSize, MmwDemo_NearFieldCorrectionCfg_t::startRangeIdx, MmwDemo_DSS_DataPathObj_t::sumAbs, MmwDemo_DSS_DataPathObj_t::sumAbsRange, SYS_COMMON_NUM_TX_ANTENNAS, MmwDemo_measureRxChannelBiasCfg_t_::targetDistance, MmwDemo_CfarCfg_t::thresholdScale, MmwDemo_DSS_DataPathObj_t::twiddle32x32_2D, MmwDemo_DSS_DataPathObj_t::window2D, MmwDemo_DSS_DataPathObj_t::windowingBuf2D, and MmwDemo_CfarCfg_t::winLen.
Referenced by MmwDemo_dssDataPathProcessEvents().
uint32_t MmwDemo_pow2roundup (uint32_t x)
Description
Power of 2 round up function.
Definition at line 575 of file dss_data_path.c.
Referenced by MmwDemo_parseProfileAndChirpConfig().
void MmwDemo_processChirp (MmwDemo_DSS_DataPathObj * obj, uint16_t chirpIndxInMultiChirp)
Description
Chirp processing. It is called from MmwDemo_dssDataPathProcessEvents. It is executed per chirp
Return values
Not Applicable.
Definition at line 3195 of file dss_data_path.c.
References MmwDemo_DSS_DataPathObj_t::ADCdataBuf, MmwDemo_DSS_DataPathObj_t::chirpCount, MmwDemo_DSS_DataPathObj_t::context, MmwDemo_DSS_DataPathObj_t::dopplerBinCount, MmwDemo_DSS_dataPathContext_t_::edmaHandle, cycleLog_t_::interChirpWaitTime, isPong, MMW_DATA_PATH_EDMA_INSTANCE, MMW_EDMA_CH_1D_IN_PING, MMW_EDMA_CH_1D_IN_PONG, MMW_EDMA_CH_1D_OUT_PING, MMW_EDMA_CH_1D_OUT_PONG, MmwDemo_dataPathWait1DOutputData(), MmwDemo_interChirpProcessing(), MmwDemo_DSS_DataPathObj_t::numAdcSamples, MmwDemo_DSS_DataPathObj_t::numChirpsPerChirpEvent, MmwDemo_DSS_DataPathObj_t::numDopplerBins, MmwDemo_DSS_DataPathObj_t::numRangeBins, MmwDemo_DSS_DataPathObj_t::numRxAntennas, MmwDemo_DSS_DataPathObj_t::numTxAntennas, pingPongId, MmwDemo_DSS_DataPathObj_t::radarCube, and MmwDemo_DSS_DataPathObj_t::txAntennaCount.
Referenced by MmwDemo_dssDataPathProcessEvents().
void MmwDemo_waitEndOfChirps (MmwDemo_DSS_DataPathObj * obj)
Description
Wait for transfer of data corresponding to the last 2 chirps (ping/pong) to the radarCube matrix before starting interframe processing.
Return values
Not Applicable.
Definition at line 3262 of file dss_data_path.c.
References cycleLog_t_::interChirpWaitTime, and MmwDemo_dataPathWait1DOutputData().
Referenced by MmwDemo_dssDataPathProcessEvents().
Copyright 2018, Texas Instruments Incorporated