xwr16xx/mmw/dss/dss_lvds_stream.c File Reference
dss_lvds_stream.c File Reference
Implements LVDS stream functionality.
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include <xdc/std.h>
#include <xdc/cfg/global.h>
#include <xdc/runtime/IHeap.h>
#include <xdc/runtime/System.h>
#include <xdc/runtime/Error.h>
#include <xdc/runtime/Memory.h>
#include <ti/sysbios/BIOS.h>
#include <ti/sysbios/knl/Task.h>
#include <ti/sysbios/knl/Event.h>
#include <ti/sysbios/knl/Semaphore.h>
#include <ti/sysbios/knl/Clock.h>
#include <ti/sysbios/heaps/HeapBuf.h>
#include <ti/sysbios/heaps/HeapMem.h>
#include <ti/sysbios/family/c64p/Cache.h>
#include <ti/sysbios/family/c64p/Hwi.h>
#include <ti/sysbios/family/c64p/EventCombiner.h>
#include <ti/sysbios/utils/Load.h>
#include <ti/drivers/soc/soc.h>
#include <ti/common/sys_common.h>
#include <ti/drivers/osal/DebugP.h>
#include <ti/drivers/osal/MemoryP.h>
#include <ti/drivers/adcbuf/ADCBuf.h>
#include <ti/drivers/edma/edma.h>
#include <ti/drivers/cbuff/cbuff.h>
#include <ti/utils/hsiheader/hsiheader.h>
#include <ti/demo/xwr16xx/mmw/dss/dss_mmw.h>
#include <ti/demo/xwr16xx/mmw/dss/dss_data_path.h>
#include <ti/demo/xwr16xx/mmw/dss/dss_resources.h>
Functions
void MmwDemo_LVDSStream_EDMAInit (void)
int32_t MmwDemo_LVDSStreamInit (void)
static void MmwDemo_LVDSStream_EDMAAllocateCBUFFChannel (CBUFF_EDMAInfo *ptrEDMAInfo, CBUFF_EDMAChannelCfg *ptrEDMACfg)
static int32_t MmwDemo_LVDSStream_EDMAAllocateCBUFFHwChannel (CBUFF_EDMAInfo *ptrEDMAInfo, CBUFF_EDMAChannelCfg *ptrEDMACfg)
static int32_t MmwDemo_LVDSStream_EDMAAllocateCBUFFSwChannel (CBUFF_EDMAInfo *ptrEDMAInfo, CBUFF_EDMAChannelCfg *ptrEDMACfg)
static void MmwDemo_LVDSStream_EDMAFreeCBUFFHwChannel (CBUFF_EDMAChannelCfg *ptrEDMACfg)
static void MmwDemo_LVDSStream_EDMAFreeCBUFFSwChannel (CBUFF_EDMAChannelCfg *ptrEDMACfg)
void MmwDemo_LVDSStreamDeleteHwSession (CBUFF_SessionHandle sessionHandle)
void MmwDemo_LVDSStreamDeleteSwSession (CBUFF_SessionHandle sessionHandle)
static void MmwDemo_LVDSStream_HwTriggerFrameDone (CBUFF_SessionHandle sessionHandle)
static void MmwDemo_LVDSStream_SwTriggerFrameDone (CBUFF_SessionHandle sessionHandle)
int32_t MmwDemo_LVDSStreamHwConfig (MmwDemo_DSS_DataPathObj *datPathObj)
int32_t MmwDemo_LVDSStreamSwConfig (MmwDemo_DSS_DataPathObj *datPathObj)
Variables
MmwDemo_DSS_MCB gMmwDssMCB
Global Variable for tracking information required by the mmw Demo.
Detailed Description
Implements LVDS stream functionality.
NOTE: (C) Copyright 2016 Texas Instruments, Inc.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Texas Instruments Incorporated nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file dss_lvds_stream.c.
Function Documentation
static void MmwDemo_LVDSStream_EDMAAllocateCBUFFChannel (CBUFF_EDMAInfo * ptrEDMAInfo, CBUFF_EDMAChannelCfg * ptrEDMACfg) static
Description
Function that allocates CBUFF-EDMA channel
Parameters
[in] ptrEDMAInfo Pointer to the EDMA Information
[out] ptrEDMACfg Populated EDMA channel configuration
Definition at line 216 of file dss_lvds_stream.c.
References MMW_LVDS_STREAM_CBUFF_EDMA_CH_0, MMW_LVDS_STREAM_CBUFF_EDMA_CH_1, MMW_LVDS_STREAM_CBUFF_EDMA_SHADOW_CH_0, MMW_LVDS_STREAM_CBUFF_EDMA_SHADOW_CH_1, MmwDemo_dssAssert, and MmwDemo_LVDSStream_EDMAAllocateCBUFFHwChannel().
Referenced by MmwDemo_LVDSStream_EDMAAllocateCBUFFHwChannel(), MmwDemo_LVDSStream_EDMAAllocateCBUFFSwChannel(), and MmwDemo_LVDSStreamInit().
static int32_t MmwDemo_LVDSStream_EDMAAllocateCBUFFHwChannel (CBUFF_EDMAInfo * ptrEDMAInfo, CBUFF_EDMAChannelCfg * ptrEDMACfg) static
Description
This is the registered CBUFF EDMA channel allocation function which allocates EDMA channels for CBUFF HW Session
Parameters
[in] ptrEDMAInfo Pointer to the EDMA Information
[out] ptrEDMACfg Populated EDMA channel configuration
Return values
Success - 0
Error - <0
Definition at line 255 of file dss_lvds_stream.c.
References MmwDemo_LVDSStream_MCB::hwSessionEDMAChannelAllocatorIndex, MmwDemo_LVDSStream_MCB::hwSessionEDMAChannelTable, MmwDemo_DSS_MCB_t::lvdsStream, MINUS_ONE, MMWDEMO_LVDS_STREAM_HW_SESSION_MAX_EDMA_CHANNEL, MmwDemo_LVDSStream_EDMAAllocateCBUFFChannel(), and MmwDemo_LVDSStream_EDMAAllocateCBUFFSwChannel().
Referenced by MmwDemo_LVDSStream_EDMAAllocateCBUFFChannel(), and MmwDemo_LVDSStreamHwConfig().
static int32_t MmwDemo_LVDSStream_EDMAAllocateCBUFFSwChannel (CBUFF_EDMAInfo * ptrEDMAInfo, CBUFF_EDMAChannelCfg * ptrEDMACfg) static
Description
This is the registered CBUFF EDMA channel allocation function which allocates EDMA channels for CBUFF SW Session
Parameters
[in] ptrEDMAInfo Pointer to the EDMA Information
[out] ptrEDMACfg Populated EDMA channel configuration
Return values
Success - 0
Error - <0
Definition at line 313 of file dss_lvds_stream.c.
References MmwDemo_DSS_MCB_t::lvdsStream, MINUS_ONE, MMWDEMO_LVDS_STREAM_SW_SESSION_MAX_EDMA_CHANNEL, MmwDemo_LVDSStream_EDMAAllocateCBUFFChannel(), MmwDemo_LVDSStream_MCB::swSessionEDMAChannelAllocatorIndex, and MmwDemo_LVDSStream_MCB::swSessionEDMAChannelTable.
Referenced by MmwDemo_LVDSStream_EDMAAllocateCBUFFHwChannel(), and MmwDemo_LVDSStreamSwConfig().
static void MmwDemo_LVDSStream_EDMAFreeCBUFFHwChannel (CBUFF_EDMAChannelCfg * ptrEDMACfg) static
Description
This is the registered CBUFF EDMA channel free function which frees EDMA channels which had been allocated for use by a CBUFF HW Session
Return values
Not applicable
Definition at line 362 of file dss_lvds_stream.c.
References MmwDemo_LVDSStream_MCB::hwSessionEDMAChannelAllocatorIndex, MmwDemo_LVDSStream_MCB::hwSessionEDMAChannelTable, MmwDemo_DSS_MCB_t::lvdsStream, MMW_LVDS_STREAM_CBUFF_EDMA_CH_0, MMW_LVDS_STREAM_CBUFF_EDMA_CH_1, MmwDemo_dssAssert, and MMWDEMO_LVDS_STREAM_HW_SESSION_MAX_EDMA_CHANNEL.
Referenced by MmwDemo_LVDSStreamHwConfig().
static void MmwDemo_LVDSStream_EDMAFreeCBUFFSwChannel (CBUFF_EDMAChannelCfg * ptrEDMACfg) static
Description
This is the registered CBUFF EDMA channel free function which frees EDMA channels which had been allocated for use by a CBUFF SW Session
Return values
Not applicable
Definition at line 405 of file dss_lvds_stream.c.
References MmwDemo_DSS_MCB_t::lvdsStream, MMW_LVDS_STREAM_CBUFF_EDMA_CH_0, MMW_LVDS_STREAM_CBUFF_EDMA_CH_1, MmwDemo_dssAssert, MMWDEMO_LVDS_STREAM_SW_SESSION_MAX_EDMA_CHANNEL, MmwDemo_LVDSStream_MCB::swSessionEDMAChannelAllocatorIndex, and MmwDemo_LVDSStream_MCB::swSessionEDMAChannelTable.
Referenced by MmwDemo_LVDSStreamSwConfig().
void MmwDemo_LVDSStream_EDMAInit (void)
Description
This function initializes/configures the LVDS streaming EDMA resources.
Return values
Success - 0
Error - <0
Definition at line 95 of file dss_lvds_stream.c.
References MmwDemo_LVDSStream_MCB::hwSessionEDMAChannelAllocatorIndex, MmwDemo_LVDSStream_MCB::hwSessionEDMAChannelTable, MmwDemo_DSS_MCB_t::lvdsStream, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_0, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_1, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_10, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_11, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_12, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_13, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_14, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_2, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_3, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_4, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_5, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_6, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_7, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_8, MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_9, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_0, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_1, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_10, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_11, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_12, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_13, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_14, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_2, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_3, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_4, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_5, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_6, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_7, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_8, MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_9, MMW_LVDS_STREAM_SW_SESSION_EDMA_CH_0, MMW_LVDS_STREAM_SW_SESSION_EDMA_CH_1, MMW_LVDS_STREAM_SW_SESSION_EDMA_SHADOW_CH_0, MMW_LVDS_STREAM_SW_SESSION_EDMA_SHADOW_CH_1, MmwDemo_LVDSStream_MCB::swSessionEDMAChannelAllocatorIndex, and MmwDemo_LVDSStream_MCB::swSessionEDMAChannelTable.
Referenced by MmwDemo_LVDSStreamInit().
static void MmwDemo_LVDSStream_HwTriggerFrameDone (CBUFF_SessionHandle sessionHandle) static
Description
This is the registered callback function which is invoked after the frame done interrupt is received for the hardware session.
Parameters
[in] sessionHandle Handle to the session
Return values
Not applicable
Definition at line 536 of file dss_lvds_stream.c.
References MmwDemo_DSS_DataPathObj_t::cliCfg, MmwDemo_DSS_MCB_t::dataPathObj, MmwDemo_LVDSStream_MCB::hwFrameDoneCount, MmwDemo_LvdsStreamCfg_t::isSwEnabled, MmwDemo_DSS_MCB_t::lvdsStream, MmwDemo_CliCfg_t_::lvdsStreamCfg, and MmwDemo_DSS_MCB_t::numSubFrames.
Referenced by MmwDemo_LVDSStreamHwConfig().
static void MmwDemo_LVDSStream_SwTriggerFrameDone (CBUFF_SessionHandle sessionHandle) static
Description
This is the registered callback function which is invoked after the frame done interrupt is received for the SW session.
Parameters
[in] sessionHandle Handle to the session
Return values
Not applicable
Definition at line 586 of file dss_lvds_stream.c.
References MmwDemo_LVDSStream_MCB::hwSessionHandle, MmwDemo_DSS_MCB_t::lvdsStream, MmwDemo_DSS_MCB_t::numSubFrames, and MmwDemo_LVDSStream_MCB::swFrameDoneCount.
Referenced by MmwDemo_LVDSStreamSwConfig().
Variable Documentation
MmwDemo_DSS_MCB gMmwDssMCB
Global Variable for tracking information required by the mmw Demo.
Definition at line 173 of file dss_main.c.
Copyright 2018, Texas Instruments Incorporated