DSS_LVDS_STREAM
DSS_LVDS_STREAM
Data Structures
struct MmwDemo_LVDSUserDataHeader
LVDS streaming user data header.
struct MmwDemo_LVDSStream_MCB
LVDS streaming MCB.
Macros
#define MMWDEMO_LVDS_STREAM_HW_SESSION_MAX_EDMA_CHANNEL 15U
This is the maximum number of EDMA Channels which is used by the HW Session.
#define MMWDEMO_LVDS_STREAM_SW_SESSION_MAX_EDMA_CHANNEL 2U
This is the maximum number of EDMA Channels which is used by the SW Session.
Typedefs
typedef struct MmwDemo_LVDSUserDataHeader MmwDemo_LVDSUserDataHeader_t
LVDS streaming user data header.
typedef struct MmwDemo_LVDSStream_MCB MmwDemo_LVDSStream_MCB_t
LVDS streaming MCB.
Functions
int32_t MmwDemo_LVDSStreamInit (void)
int32_t MmwDemo_LVDSStreamHwConfig (MmwDemo_DSS_DataPathObj *datPathObj)
int32_t MmwDemo_LVDSStreamSwConfig (MmwDemo_DSS_DataPathObj *datPathObj)
void MmwDemo_LVDSStreamDeleteHwSession (CBUFF_SessionHandle sessionHandle)
void MmwDemo_LVDSStreamDeleteSwSession (CBUFF_SessionHandle sessionHandle)
Detailed Description
Macro Definition Documentation
#define MMWDEMO_LVDS_STREAM_HW_SESSION_MAX_EDMA_CHANNEL 15U
This is the maximum number of EDMA Channels which is used by the HW Session.
Definition at line 53 of file dss_lvds_stream.h.
Referenced by MmwDemo_LVDSStream_EDMAAllocateCBUFFHwChannel(), and MmwDemo_LVDSStream_EDMAFreeCBUFFHwChannel().
#define MMWDEMO_LVDS_STREAM_SW_SESSION_MAX_EDMA_CHANNEL 2U
This is the maximum number of EDMA Channels which is used by the SW Session.
Definition at line 59 of file dss_lvds_stream.h.
Referenced by MmwDemo_LVDSStream_EDMAAllocateCBUFFSwChannel(), and MmwDemo_LVDSStream_EDMAFreeCBUFFSwChannel().
Typedef Documentation
typedef struct MmwDemo_LVDSStream_MCB MmwDemo_LVDSStream_MCB_t
LVDS streaming MCB.
The LVDS streaming MCB
typedef struct MmwDemo_LVDSUserDataHeader MmwDemo_LVDSUserDataHeader_t
LVDS streaming user data header.
The LVDS SW streaming user data header
Function Documentation
void MmwDemo_LVDSStreamDeleteHwSession (CBUFF_SessionHandle sessionHandle)
Description
This function deletes the hardware session and any HSI header associated with it.
Parameters
[in] sessionHandle Handle to the session
Return values
Not applicable
Definition at line 452 of file dss_lvds_stream.c.
References MmwDemo_DSS_MCB_t::cliCfg, MmwDemo_LVDSStream_MCB::hwSessionHandle, MmwDemo_LVDSStream_MCB::hwSessionHSIHeader, MmwDemo_LvdsStreamCfg_t::isHeaderEnabled, MmwDemo_DSS_MCB_t::lvdsStream, MmwDemo_CliCfg_t_::lvdsStreamCfg, MmwDemo_dssAssert, and MmwDemo_DSS_MCB_t::subFrameIndx.
Referenced by MmwDemo_dssDataPathReconfig(), and MmwDemo_dssDataPathStop().
void MmwDemo_LVDSStreamDeleteSwSession (CBUFF_SessionHandle sessionHandle)
Description
This function deletes the SW session and any HSI header associated with it.
Parameters
[in] sessionHandle Handle to the session
Return values
Not applicable
Definition at line 494 of file dss_lvds_stream.c.
References MmwDemo_DSS_MCB_t::cliCfg, MmwDemo_LvdsStreamCfg_t::isHeaderEnabled, MmwDemo_DSS_MCB_t::lvdsStream, MmwDemo_CliCfg_t_::lvdsStreamCfg, MmwDemo_dssAssert, MmwDemo_DSS_MCB_t::subFrameIndx, MmwDemo_LVDSStream_MCB::swSessionHandle, and MmwDemo_LVDSStream_MCB::swSessionHSIHeader.
Referenced by MmwDemo_dssDataPathOutputLogging(), and MmwDemo_dssDataPathStop().
int32_t MmwDemo_LVDSStreamHwConfig (MmwDemo_DSS_DataPathObj * datPathObj)
Description
This is the LVDS streaming config function. It configures the sessions for the LVDS streaming.
Return values
Success - 0
Error - <0
Definition at line 637 of file dss_lvds_stream.c.
References MmwDemo_CliCfg_t_::adcBufCfg, MmwDemo_DSS_dataPathContext_t_::adcbufHandle, MmwDemo_LVDSStream_MCB::cbuffHandle, MmwDemo_ADCBufCfg_t::chInterleave, MmwDemo_DSS_DataPathObj_t::cliCfg, MmwDemo_LvdsStreamCfg_t::dataFmt, MmwDemo_DSS_MCB_t::dataPathContext, MmwDemo_DSS_DataPathObj_t::datapathCQ, MmwDemo_DSS_dataPathContext_t_::edmaHandle, HSIHeader_getHeaderSize(), HSIHeader_toCBUFFUnits(), MmwDemo_LVDSStream_MCB::hwSessionHandle, MmwDemo_LVDSStream_MCB::hwSessionHSIHeader, MmwDemo_LvdsStreamCfg_t::isHeaderEnabled, MmwDemo_DSS_MCB_t::lvdsStream, MmwDemo_CliCfg_t_::lvdsStreamCfg, MINUS_ONE, MMW_LVDS_STREAM_EDMA_INSTANCE, MmwDemo_dssAssert, MmwDemo_LVDSStream_EDMAAllocateCBUFFHwChannel(), MmwDemo_LVDSStream_EDMAFreeCBUFFHwChannel(), MmwDemo_LVDSStream_HwTriggerFrameDone(), MmwDemo_DSS_DataPathObj_t::numAdcSamples, MmwDemo_DSS_DataPathObj_t::numChirpsPerChirpEvent, MmwDemo_DSS_DataPathObj_t::numChirpsPerFrame, MmwDemo_DSS_DataPathCQConfig_t::satMonTotalSize, and MmwDemo_DSS_DataPathCQConfig_t::sigImgMonTotalSize.
Referenced by MmwDemo_dssDataPathReconfig().
int32_t MmwDemo_LVDSStreamInit (void)
Description
This is the LVDS streaming init function. It initializes the necessary modules that implement the streaming.
Return values
Success - 0
Error - <0
Definition at line 151 of file dss_lvds_stream.c.
References MmwDemo_LVDSStream_MCB::cbuffHandle, MmwDemo_DSS_MCB_t::lvdsStream, MINUS_ONE, MmwDemo_LVDSStream_EDMAAllocateCBUFFChannel(), MmwDemo_LVDSStream_EDMAInit(), and MmwDemo_DSS_MCB_t::socHandle.
Referenced by MmwDemo_dssInitTask().
int32_t MmwDemo_LVDSStreamSwConfig (MmwDemo_DSS_DataPathObj * datPathObj)
Description
This is the LVDS streaming config function. It configures the sessions for the LVDS streaming.
Return values
Success - 0
Error - <0
Definition at line 728 of file dss_lvds_stream.c.
References MmwDemo_LVDSStream_MCB::cbuffHandle, MmwDemo_DSS_DataPathObj_t::cliCfg, MmwDemo_DSS_MCB_t::dataPathContext, MmwDemo_DSS_DataPathObj_t::detObj2D, MmwDemo_DSS_dataPathContext_t_::edmaHandle, HSIHeader_getHeaderSize(), HSIHeader_toCBUFFUnits(), MmwDemo_LvdsStreamCfg_t::isHeaderEnabled, MmwDemo_DSS_MCB_t::lvdsStream, MmwDemo_CliCfg_t_::lvdsStreamCfg, MINUS_ONE, MMW_LVDS_STREAM_EDMA_INSTANCE, MmwDemo_LVDSStream_EDMAAllocateCBUFFSwChannel(), MmwDemo_LVDSStream_EDMAFreeCBUFFSwChannel(), MmwDemo_LVDSStream_SwTriggerFrameDone(), MmwDemo_DSS_DataPathObj_t::numDetObj, MmwDemo_LVDSStream_MCB::swSessionHandle, MmwDemo_LVDSStream_MCB::swSessionHSIHeader, and MmwDemo_LVDSStream_MCB::userDataHeader.
Referenced by MmwDemo_dssDataPathOutputLogging().
Copyright 2018, Texas Instruments Incorporated