xwr16xx/mmw/mss/mss_main.c File Reference
mss_main.c File Reference
MSS main implementation of the millimeter wave Demo.
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <xdc/std.h>
#include <xdc/cfg/global.h>
#include <xdc/runtime/IHeap.h>
#include <xdc/runtime/System.h>
#include <xdc/runtime/Error.h>
#include <xdc/runtime/Memory.h>
#include <ti/sysbios/BIOS.h>
#include <ti/sysbios/knl/Task.h>
#include <ti/sysbios/knl/Event.h>
#include <ti/sysbios/knl/Semaphore.h>
#include <ti/sysbios/knl/Clock.h>
#include <ti/sysbios/heaps/HeapBuf.h>
#include <ti/sysbios/heaps/HeapMem.h>
#include <ti/sysbios/family/arm/v7a/Pmu.h>
#include <ti/sysbios/family/arm/v7r/vim/Hwi.h>
#include <ti/common/sys_common.h>
#include <ti/drivers/soc/soc.h>
#include <ti/drivers/esm/esm.h>
#include <ti/drivers/crc/crc.h>
#include <ti/drivers/uart/UART.h>
#include <ti/drivers/gpio/gpio.h>
#include <ti/drivers/mailbox/mailbox.h>
#include <ti/control/mmwave/mmwave.h>
#include <ti/utils/cli/cli.h>
#include <ti/drivers/osal/DebugP.h>
#include <ti/drivers/osal/HwiP.h>
#include <ti/utils/hsiheader/hsiheader.h>
#include "mss_mmw.h"
#include "ti/demo/xwr16xx/mmw/common/mmw_messages.h"
Functions
void MmwDemo_CLIInit (void)
int32_t MmwDemo_mssDataPathConfig (void)
int32_t MmwDemo_mssDataPathStart (void)
int32_t MmwDemo_mssDataPathStop (void)
void MmwDemo_mssMmwaveConfigCallbackFxn (MMWave_CtrlCfg *ptrCtrlCfg)
void MmwDemo_mssMmwaveStartCallbackFxn (MMWave_CalibrationCfg *ptrCalibrationCfg)
static void MmwDemo_mssMmwaveOpenCallbackFxn (MMWave_OpenCfg *ptrOpenCfg)
static void MmwDemo_mssMmwaveCloseCallbackFxn (void)
void MmwDemo_mssMmwaveStopcallbackFxn (void)
int32_t MmwDemo_mssMmwaveEventCallbackFxn (uint16_t msgId, uint16_t sbId, uint16_t sbLen, uint8_t *payload)
void MmwDemo_mssInitTask (UArg arg0, UArg arg1)
void MmwDemo_mmWaveCtrlTask (UArg arg0, UArg arg1)
void MmwDemo_mssCtrlPathTask (UArg arg0, UArg arg1)
void MmwDemo_gpioSwitchTask (UArg arg0, UArg arg1)
void MmwDemo_sleep (void)
static void MmwDemo_installDss2MssExceptionSignallingISR (void)
void MmwDemo_mssMmwaveStopCallbackFxn (void)
int32_t MmwDemo_mboxWrite (MmwDemo_message *message)
static void MmwDemo_mboxReadTask (UArg arg0, UArg arg1)
void MmwDemo_mboxCallback (Mbox_Handle handle, Mailbox_Type peer)
int32_t MmwDemo_bpmConfig (void)
int32_t MmwDemo_mssSetHsiClk (void)
void MmwDemo_notifySensorStart (bool doReconfig)
void MmwDemo_notifySensorStop (void)
int32_t MmwDemo_waitSensorStartComplete (void)
void MmwDemo_waitSensorStopComplete (void)
static void MmwDemo_switchPressFxn (unsigned int index)
void MmwDemo_Dss2MssISR (uintptr_t arg)
void _MmwDemo_mssAssert (int32_t expression, const char *file, int32_t line)
int main (void)
Variables
MmwDemo_MCB gMmwMssMCB
Global Variable for tracking information required by the mmw Demo.
Detailed Description
MSS main implementation of the millimeter wave Demo.
NOTE: (C) Copyright 2016 Texas Instruments, Inc.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Texas Instruments Incorporated nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file mss_main.c.
Function Documentation
void _MmwDemo_mssAssert (int32_t expression, const char * file, int32_t line)
Description
Send MSS assert information through CLI.
Definition at line 2460 of file mss_main.c.
References CLI_write().
int main (void)
Description
Entry point into the Millimeter Wave Demo
Return values
Not Applicable.
Definition at line 2475 of file mss_main.c.
References MmwDemo_MCB_t::cfg, MmwDemo_Cfg_t::commandBaudRate, MmwDemo_Cfg_t::loggingBaudRate, MmwDemo_mssInitTask(), MSS_SYS_VCLK, MmwDemo_MCB_t::socHandle, and MmwDemo_Cfg_t::sysClockFrequency.
int32_t MmwDemo_bpmConfig (void)
Description
Function that configures the BPM chirps based on the stored BPM CLI commands. The MMW demo supports only a fixed BPM scheme and this scheme is implemented by this function.
Return values
0 - Success. <0 - Failed with errors
Definition at line 1486 of file mss_main.c.
References MmwDemo_CliCfg_t_::bpmCfg, MmwDemo_MCB_t::cfg, MmwDemo_BpmCfg_t::chirp0Idx, MmwDemo_BpmCfg_t::chirp1Idx, MmwDemo_MCB_t::cliCfg, MmwDemo_Cfg_t::ctrlCfg, MmwDemo_MCB_t::ctrlHandle, and MmwDemo_BpmCfg_t::isEnabled.
Referenced by MmwDemo_mssDataPathConfig().
void MmwDemo_CLIInit (void)
Description
This is the CLI Execution Task
Return values
Not Applicable.
Definition at line 1206 of file cli.c.
References CLI_open(), MmwDemo_MCB_t::commandUartHandle, MmwDemo_MCB_t::ctrlHandle, MmwDemo_CLIADCBufCfg(), MmwDemo_CLIAnalogMonitorCfg(), MmwDemo_CLIBpmCfg(), MmwDemo_CLICalibDcRangeSig(), MmwDemo_CLICfarCfg(), MmwDemo_CLIChirpQualityRxSatMonCfg(), MmwDemo_CLIChirpQualitySigImgMonCfg(), MmwDemo_CLIClutterRemoval(), MmwDemo_CLICompRangeBiasAndRxChanPhaseCfg(), MmwDemo_CLIExtendedMaxVelocity(), MmwDemo_CLIGuiMonSel(), MmwDemo_CLILvdsStreamCfg(), MmwDemo_CLIMeasureRangeBiasAndRxChanPhaseCfg(), MmwDemo_CLIMultiObjBeamForming(), MmwDemo_CLINearFieldCorrection(), MmwDemo_CLIPeakGroupingCfg(), MmwDemo_CLISensorStart(), MmwDemo_CLISensorStop(), and MmwDemo_CLISetDataLogger().
Referenced by MmwDemo_mssInitTask().
void MmwDemo_Dss2MssISR (uintptr_t arg)
Description
DSS to MSS ISR used for direct signalling of things like urgent exception events from DSS. Posts deadline miss events to MmwDemo_mssCtrlPathTask.
Return values
Not Applicable.
Definition at line 2163 of file mss_main.c.
References MmwDemo_MCB_t::dss2mssIsrInfoAddress, MmwDemo_MCB_t::eventHandle, MMWDEMO_DSS2MSS_CHIRP_PROC_DEADLINE_MISS_EXCEPTION, MMWDEMO_DSS2MSS_FRAME_PROC_DEADLINE_MISS_EXCEPTION, MMWDEMO_DSS_CHIRP_PROC_DEADLINE_MISS_EVT, MMWDEMO_DSS_FRAME_PROC_DEADLINE_MISS_EVT, and MmwDemo_mssAssert.
Referenced by MmwDemo_installDss2MssExceptionSignallingISR().
void MmwDemo_gpioSwitchTask (UArg arg0, UArg arg1)
Description
The task is used to process events related to pressing the GPIO switch
Return values
Not Applicable.
Definition at line 2126 of file mss_main.c.
References MmwDemo_MCB_t::gpioSemHandle, MmwDemo_MCB_t::isSensorStarted, MmwDemo_mssAssert, MmwDemo_notifySensorStart(), MmwDemo_notifySensorStop(), MmwDemo_waitSensorStartComplete(), and MmwDemo_waitSensorStopComplete().
Referenced by MmwDemo_mssInitTask().
static void MmwDemo_installDss2MssExceptionSignallingISR (void) static
Description
Installs DSS to MSS Software Interrupt ISR for exception signalling.
Return values
Not Applicable.
Definition at line 2189 of file mss_main.c.
References MMWDEMO_DSS2MSS_EXCEPTION_SIGNALLING_SW_INT_MSS, and MmwDemo_Dss2MssISR().
Referenced by MmwDemo_mboxReadTask().
void MmwDemo_mboxCallback (Mbox_Handle handle, Mailbox_Type peer)
Description
This function is a callback funciton that invoked when a message is received from the peer.
Parameters
[in] handle Handle to the Mailbox on which data was received
[in] peer Peer from which data was received
Return values
Not Applicable.
Definition at line 1465 of file mss_main.c.
References MmwDemo_MCB_t::mboxSemHandle.
Referenced by MmwDemo_mboxReadTask(), and MmwDemo_mssInitTask().
static void MmwDemo_mboxReadTask (UArg arg0, UArg arg1) static
Description
The Task is used to handle the mmw demo messages received from Mailbox virtual channel.
Parameters
[in] arg0 arg0 of the Task. Not used
[in] arg1 arg1 of the Task. Not used
Return values
Not Applicable.
Definition at line 1334 of file mss_main.c.
References MmwDemo_msgTlv_t::address, MmwDemo_message_body_u::assertInfo, MmwDemo_message_t::body, CLI_write(), MmwDemo_message_body_u::compRxChanCfg, MmwDemo_message_body_u::detObj, MmwDemo_MCB_t::dss2mssIsrInfoAddress, MmwDemo_message_body_u::dss2mssISRinfoAddress, MmwDemo_MSS_STATS_t::dssSensorStop, MmwDemo_MCB_t::eventHandleNotify, MmwDemo_dssAssertInfoMsg_t::file, MmwDemo_detObjMsg_t::header, cmplx16ImRe_t_::imag, MmwDemo_msgTlv_t::length, MmwDemo_dssAssertInfoMsg_t::line, MmwDemo_MCB_t::loggingUartHandle, MmwDemo_MCB_t::mboxSemHandle, MMWDEMO_DSS2MSS_ASSERT_INFO, MMWDEMO_DSS2MSS_DETOBJ_READY, MMWDEMO_DSS2MSS_ISR_INFO_ADDRESS, MMWDEMO_DSS2MSS_MEASUREMENT_INFO, MMWDEMO_DSS2MSS_STOPDONE, MMWDEMO_DSS_STOP_COMPLETED_EVT, MmwDemo_installDss2MssExceptionSignallingISR(), MmwDemo_mboxCallback(), MmwDemo_mboxWrite(), MMWDEMO_MSS2DSS_DETOBJ_SHIPPED, MMWDEMO_OUTPUT_MSG_SEGMENT_LEN, MmwDemo_output_message_header_t::numTLVs, MmwDemo_MCB_t::peerMailbox, MmwDemo_compRxChannelBiasCfg_t_::rangeBias, cmplx16ImRe_t_::real, MmwDemo_compRxChannelBiasCfg_t_::rxChPhaseComp, MmwDemo_MCB_t::stats, SYS_COMMON_NUM_RX_CHANNEL, SYS_COMMON_NUM_TX_ANTENNAS, MmwDemo_detObjMsg_t::tlv, and MmwDemo_message_t::type.
Referenced by MmwDemo_mssInitTask().
int32_t MmwDemo_mboxWrite (MmwDemo_message * message)
Description
Function to send a message to peer through Mailbox virtural channel
Parameters
[in] message Pointer to the MMW demo message.
Return values
Success - 0 Fail < -1
Definition at line 1308 of file mss_main.c.
References MmwDemo_MCB_t::peerMailbox.
Referenced by MmwDemo_CLIADCBufCfg(), MmwDemo_CLIAnalogMonitorCfg(), MmwDemo_CLIBpmCfg(), MmwDemo_CLICalibDcRangeSig(), MmwDemo_CLICfarCfg(), MmwDemo_CLIChirpQualityRxSatMonCfg(), MmwDemo_CLIChirpQualitySigImgMonCfg(), MmwDemo_CLIClutterRemoval(), MmwDemo_CLICompRangeBiasAndRxChanPhaseCfg(), MmwDemo_CLIExtendedMaxVelocity(), MmwDemo_CLIGuiMonSel(), MmwDemo_CLILvdsStreamCfg(), MmwDemo_CLIMeasureRangeBiasAndRxChanPhaseCfg(), MmwDemo_CLIMultiObjBeamForming(), MmwDemo_CLINearFieldCorrection(), MmwDemo_CLIPeakGroupingCfg(), MmwDemo_CLISetDataLogger(), and MmwDemo_mboxReadTask().
void MmwDemo_mmWaveCtrlTask (UArg arg0, UArg arg1)
Description
The task is used to provide an execution context for the mmWave control task
Return values
Not Applicable.
Definition at line 1790 of file mss_main.c.
References MmwDemo_MCB_t::ctrlHandle.
Referenced by MmwDemo_mssInitTask().
void MmwDemo_mssCtrlPathTask (UArg arg0, UArg arg1)
Description
The task is used to process data path events control task
Return values
Not Applicable.
Definition at line 1961 of file mss_main.c.
References CLI_write(), MmwDemo_MCB_t::eventHandle, MmwDemo_MCB_t::eventHandleNotify, MmwDemo_MCB_t::isSensorStarted, MMWDEMO_BSS_ANALOGFAULT_EVT, MMWDEMO_BSS_CPUFAULT_EVT, MMWDEMO_BSS_ESMFAULT_EVT, MMWDEMO_BSS_FAULT_EVENTS, MMWDEMO_CLI_EVENTS, MMWDEMO_CLI_FRAMESTART_EVT, MMWDEMO_CLI_SENSORSTART_EVT, MMWDEMO_CLI_SENSORSTOP_EVT, MMWDEMO_DSS_CHIRP_PROC_DEADLINE_MISS_EVT, MMWDEMO_DSS_EXCEPTION_EVENTS, MMWDEMO_DSS_FRAME_PROC_DEADLINE_MISS_EVT, MMWDEMO_DSS_START_COMPLETED_EVT, MMWDEMO_DSS_START_FAILED_EVT, MMWDEMO_DSS_STOP_COMPLETED_EVT, MMWDEMO_MSS_STOP_COMPLETED_EVT, MmwDemo_mssAssert, MmwDemo_mssDataPathConfig(), MmwDemo_mssDataPathStart(), MmwDemo_mssDataPathStop(), MmwDemo_switchPressFxn(), SOC_XWR16XX_GPIO_1, and SOC_XWR16XX_GPIO_2.
Referenced by MmwDemo_mssInitTask().
int32_t MmwDemo_mssDataPathConfig (void)
Description
Function to do Data Path Configuration on MSS. After received Configuration from CLI, this function will start the system configuration process, inclucing mmwaveLink, BSS and DSS.
Return values
0 - Success. <0 - Failed with errors
Definition at line 1607 of file mss_main.c.
References MmwDemo_MCB_t::cfg, CLI_getMMWaveExtensionConfig(), CLI_getMMWaveExtensionOpenConfig(), MmwDemo_Cfg_t::ctrlCfg, MmwDemo_MCB_t::ctrlHandle, MmwDemo_MCB_t::eventHandleNotify, MmwDemo_MCB_t::isMMWaveOpen, MmwDemo_bpmConfig(), MMWDEMO_DSS_START_FAILED_EVT, MmwDemo_mssAssert, MmwDemo_mssSetHsiClk(), and MmwDemo_Cfg_t::openCfg.
Referenced by MmwDemo_mssCtrlPathTask().
int32_t MmwDemo_mssDataPathStart (void)
Description
Function to do Data Path Start on MSS. After received SensorStart command, MSS will start all data path componets including mmwaveLink, BSS and DSS.
Return values
0 - Success. <0 - Failed with errors
Definition at line 1716 of file mss_main.c.
References MmwDemo_MCB_t::cfg, MmwDemo_Cfg_t::ctrlCfg, and MmwDemo_MCB_t::ctrlHandle.
Referenced by MmwDemo_mssCtrlPathTask().
int32_t MmwDemo_mssDataPathStop (void)
Description
Function to do Data Path Start on MSS. After received SensorStart command, MSS will start all data path componets including mmwaveLink, BSS and DSS.
Return values
0 - Success. <0 - Failed with errors
Definition at line 1752 of file mss_main.c.
References MmwDemo_MCB_t::ctrlHandle.
Referenced by MmwDemo_mssCtrlPathTask().
void MmwDemo_mssInitTask (UArg arg0, UArg arg1)
Description
System Initialization Task which initializes the various components in the system.
Return values
Not Applicable.
Definition at line 2209 of file mss_main.c.
References MmwDemo_MCB_t::cfg, MmwDemo_Cfg_t::commandBaudRate, MmwDemo_MCB_t::commandUartHandle, MmwDemo_MCB_t::ctrlHandle, MmwDemo_MCB_t::eventHandle, MmwDemo_MCB_t::eventHandleNotify, MmwDemo_MCB_t::gpioSemHandle, MmwDemo_Cfg_t::loggingBaudRate, MmwDemo_MCB_t::loggingUartHandle, MmwDemo_MCB_t::mboxSemHandle, MmwDemo_CLIInit(), MmwDemo_gpioSwitchTask(), MmwDemo_mboxCallback(), MmwDemo_mboxReadTask(), MmwDemo_mmWaveCtrlTask(), MmwDemo_mssAssert, MmwDemo_mssCtrlPathTask(), MmwDemo_mssMmwaveCloseCallbackFxn(), MmwDemo_mssMmwaveConfigCallbackFxn(), MmwDemo_mssMmwaveEventCallbackFxn(), MmwDemo_mssMmwaveOpenCallbackFxn(), MmwDemo_mssMmwaveStartCallbackFxn(), MmwDemo_mssMmwaveStopCallbackFxn(), MmwDemo_MCB_t::peerMailbox, MmwDemo_MCB_t::socHandle, and MmwDemo_Cfg_t::sysClockFrequency.
Referenced by main().
static void MmwDemo_mssMmwaveCloseCallbackFxn (void) static
Description
Application registered callback function which is invoked the mmWave link on BSS has been closed.
Return values
Not applicable
Definition at line 1247 of file mss_main.c.
Referenced by MmwDemo_mssInitTask().
void MmwDemo_mssMmwaveConfigCallbackFxn (MMWave_CtrlCfg * ptrCtrlCfg)
Description
Application registered callback function which is invoked after the configuration has been used to configure the mmWave link and the BSS. This is applicable only for the XWR16xx. The BSS can be configured only by the MSS or DSS. The callback API is triggered on the remote execution domain (which did not configure the BSS)
Parameters
[in] ptrCtrlCfg Pointer to the control configuration
Return values
Not applicable
Definition at line 1213 of file mss_main.c.
References MmwDemo_MSS_STATS_t::datapathConfigEvt, and MmwDemo_MCB_t::stats.
Referenced by MmwDemo_mssInitTask().
int32_t MmwDemo_mssMmwaveEventCallbackFxn (uint16_t msgId, uint16_t sbId, uint16_t sbLen, uint8_t * payload)
Description
Registered event function which is invoked when an event from the BSS is received.
Parameters
[in] msgId Message Identifier
[in] sbId Subblock identifier
[in] sbLen Length of the subblock
[in] payload Pointer to the payload buffer
Return values
Always returns 0 [Continue passing the event to the peer domain]
Definition at line 1094 of file mss_main.c.
References CLI_write(), MmwDemo_MCB_t::eventHandle, MMWDEMO_BSS_ANALOGFAULT_EVT, MMWDEMO_BSS_CALIBRATION_REP_EVT, MMWDEMO_BSS_CPUFAULT_EVT, MMWDEMO_BSS_ESMFAULT_EVT, MMWDEMO_BSS_MONITORING_REP_EVT, MmwDemo_MSS_STATS_t::numCalibrationReports, MmwDemo_MSS_STATS_t::numFailedTimingReports, and MmwDemo_MCB_t::stats.
Referenced by MmwDemo_mssInitTask().
static void MmwDemo_mssMmwaveOpenCallbackFxn (MMWave_OpenCfg * ptrOpenCfg) static
Description
Application registered callback function which is invoked the mmWave link on BSS has been opened.
Parameters
[in] ptrOpenCfg Pointer to the open configuration
Return values
Not applicable
Definition at line 1233 of file mss_main.c.
Referenced by MmwDemo_mssInitTask().
void MmwDemo_mssMmwaveStartCallbackFxn (MMWave_CalibrationCfg * ptrCalibrationCfg)
Description
Application registered callback function which is invoked the mmWave link on BSS has been started. This is applicable only for the XWR16xx. The BSS can be configured only by the MSS or DSS. The callback API is triggered on the remote execution domain (which did not configure the BSS)
Parameters
[in] ptrCalibrationCfg Pointer to the calibration configuration
Return values
Not applicable
Definition at line 1266 of file mss_main.c.
References MmwDemo_MSS_STATS_t::datapathStartEvt, MmwDemo_MCB_t::eventHandleNotify, MMWDEMO_DSS_START_COMPLETED_EVT, and MmwDemo_MCB_t::stats.
Referenced by MmwDemo_mssInitTask().
void MmwDemo_mssMmwaveStopcallbackFxn (void)
void MmwDemo_mssMmwaveStopCallbackFxn (void)
Description
Application registered callback function which is invoked the mmWave link on BSS has been stopped. This is applicable only for the XWR16xx. The BSS can be configured only by the MSS or DSS. The callback API is triggered on the remote execution domain (which did not configure the BSS)
Return values
Not applicable
Definition at line 1287 of file mss_main.c.
References MmwDemo_MSS_STATS_t::datapathStopEvt, and MmwDemo_MCB_t::stats.
Referenced by MmwDemo_mssInitTask().
int32_t MmwDemo_mssSetHsiClk (void)
Description
Function to Setup the HSI Clock. Required for LVDS streaming.
Return values
0 - Success. <0 - Failed with errors
Definition at line 1565 of file mss_main.c.
References HSI_DCA_MIN_DELAY_MSEC.
Referenced by MmwDemo_mssDataPathConfig().
void MmwDemo_notifySensorStart (bool doReconfig)
Description
This is a utility function which can be invoked from the CLI or the Switch press to start the sensor. This sends an event to the sensor management task where the actual start procedure is implemented.
Return values
Not applicable
Definition at line 1813 of file mss_main.c.
References MmwDemo_MSS_STATS_t::cliSensorStartEvt, MmwDemo_MCB_t::eventHandle, MMWDEMO_CLI_FRAMESTART_EVT, MMWDEMO_CLI_SENSORSTART_EVT, and MmwDemo_MCB_t::stats.
Referenced by MmwDemo_CLISensorStart(), and MmwDemo_gpioSwitchTask().
void MmwDemo_notifySensorStop (void)
Description
This is a utility function which can be invoked from the CLI or the Switch press to start the sensor. This sends an event to the sensor management task where the actual start procedure is implemented.
Return values
Not applicable
Definition at line 1839 of file mss_main.c.
References MmwDemo_MSS_STATS_t::cliSensorStopEvt, MmwDemo_MCB_t::eventHandle, MMWDEMO_CLI_SENSORSTOP_EVT, and MmwDemo_MCB_t::stats.
Referenced by MmwDemo_CLISensorStop(), and MmwDemo_gpioSwitchTask().
void MmwDemo_sleep (void)
Description
Function to sleep the R4F using WFI (Wait For Interrupt) instruction. When R4F has no work left to do, the BIOS will be in Idle thread and will call this function. The R4F will wake-up on any interrupt (e.g chirp interrupt).
Return values
Not Applicable.
Definition at line 2449 of file mss_main.c.
static void MmwDemo_switchPressFxn (unsigned int index) static
Description
Callback function invoked when the GPIO switch is pressed. This is invoked from interrupt context.
Parameters
[in] index GPIO index configured as input
Return values
Not applicable
Definition at line 1946 of file mss_main.c.
References MmwDemo_MCB_t::gpioSemHandle.
Referenced by MmwDemo_mssCtrlPathTask().
int32_t MmwDemo_waitSensorStartComplete (void)
Description
This is a utility function which can be used by the CLI to pend for start complete (after MmwDemo_notifySensorStart is called)
Return values
Not applicable
Definition at line 1856 of file mss_main.c.
References MmwDemo_MCB_t::eventHandleNotify, MmwDemo_MCB_t::isSensorStarted, MMWDEMO_DSS_START_COMPLETED_EVT, MMWDEMO_DSS_START_FAILED_EVT, MmwDemo_mssAssert, and SOC_XWR16XX_GPIO_2.
Referenced by MmwDemo_CLISensorStart(), and MmwDemo_gpioSwitchTask().
void MmwDemo_waitSensorStopComplete (void)
Description
This is a utility function which can be used by the CLI to pend for stop complete (after MmwDemo_notifySensorStart is called)
Return values
Not applicable
Definition at line 1902 of file mss_main.c.
References MmwDemo_MCB_t::eventHandleNotify, MmwDemo_MCB_t::isSensorStarted, MMWDEMO_DSS_STOP_COMPLETED_EVT, MMWDEMO_MSS_STOP_COMPLETED_EVT, MmwDemo_mssAssert, and SOC_XWR16XX_GPIO_2.
Referenced by MmwDemo_CLISensorStop(), and MmwDemo_gpioSwitchTask().
Variable Documentation
MmwDemo_MCB gMmwMssMCB
Global Variable for tracking information required by the mmw Demo.
Definition at line 1034 of file mss_main.c.
Copyright 2018, Texas Instruments Incorporated