/*
 *  Do not modify this file; it is automatically 
 *  generated and any modifications will be overwritten.
 *
 * @(#) xdc-D20
 */

#ifndef ti_sysbios_family_arm_v7a_Pmu__INTERNAL__
#define ti_sysbios_family_arm_v7a_Pmu__INTERNAL__

#ifndef ti_sysbios_family_arm_v7a_Pmu__internalaccess
#define ti_sysbios_family_arm_v7a_Pmu__internalaccess
#endif

#include <ti/sysbios/family/arm/v7a/Pmu.h>

#undef xdc_FILE__
#ifndef xdc_FILE
#define xdc_FILE__ NULL
#else
#define xdc_FILE__ xdc_FILE
#endif

/* setInterruptFunc */
#undef ti_sysbios_family_arm_v7a_Pmu_setInterruptFunc
#define ti_sysbios_family_arm_v7a_Pmu_setInterruptFunc ti_sysbios_family_arm_v7a_Pmu_setInterruptFunc__E

/* startCounter */
#undef ti_sysbios_family_arm_v7a_Pmu_startCounter
#define ti_sysbios_family_arm_v7a_Pmu_startCounter ti_sysbios_family_arm_v7a_Pmu_startCounter__E

/* stopCounter */
#undef ti_sysbios_family_arm_v7a_Pmu_stopCounter
#define ti_sysbios_family_arm_v7a_Pmu_stopCounter ti_sysbios_family_arm_v7a_Pmu_stopCounter__E

/* resetCount */
#undef ti_sysbios_family_arm_v7a_Pmu_resetCount
#define ti_sysbios_family_arm_v7a_Pmu_resetCount ti_sysbios_family_arm_v7a_Pmu_resetCount__E

/* setCount */
#undef ti_sysbios_family_arm_v7a_Pmu_setCount
#define ti_sysbios_family_arm_v7a_Pmu_setCount ti_sysbios_family_arm_v7a_Pmu_setCount__E

/* configureCounter */
#undef ti_sysbios_family_arm_v7a_Pmu_configureCounter
#define ti_sysbios_family_arm_v7a_Pmu_configureCounter ti_sysbios_family_arm_v7a_Pmu_configureCounter__E

/* enableInterrupt */
#undef ti_sysbios_family_arm_v7a_Pmu_enableInterrupt
#define ti_sysbios_family_arm_v7a_Pmu_enableInterrupt ti_sysbios_family_arm_v7a_Pmu_enableInterrupt__E

/* disableInterrupt */
#undef ti_sysbios_family_arm_v7a_Pmu_disableInterrupt
#define ti_sysbios_family_arm_v7a_Pmu_disableInterrupt ti_sysbios_family_arm_v7a_Pmu_disableInterrupt__E

/* clearOverflowStatus */
#undef ti_sysbios_family_arm_v7a_Pmu_clearOverflowStatus
#define ti_sysbios_family_arm_v7a_Pmu_clearOverflowStatus ti_sysbios_family_arm_v7a_Pmu_clearOverflowStatus__E

/* getCount */
#undef ti_sysbios_family_arm_v7a_Pmu_getCount
#define ti_sysbios_family_arm_v7a_Pmu_getCount ti_sysbios_family_arm_v7a_Pmu_getCount__E

/* getNumCounters */
#undef ti_sysbios_family_arm_v7a_Pmu_getNumCounters
#define ti_sysbios_family_arm_v7a_Pmu_getNumCounters ti_sysbios_family_arm_v7a_Pmu_getNumCounters__E

/* getOverflowStatus */
#undef ti_sysbios_family_arm_v7a_Pmu_getOverflowStatus
#define ti_sysbios_family_arm_v7a_Pmu_getOverflowStatus ti_sysbios_family_arm_v7a_Pmu_getOverflowStatus__E

/* getEnabled */
#undef ti_sysbios_family_arm_v7a_Pmu_getEnabled
#define ti_sysbios_family_arm_v7a_Pmu_getEnabled ti_sysbios_family_arm_v7a_Pmu_getEnabled__E

/* startCounterI */
#undef ti_sysbios_family_arm_v7a_Pmu_startCounterI
#define ti_sysbios_family_arm_v7a_Pmu_startCounterI ti_sysbios_family_arm_v7a_Pmu_startCounterI__E

/* stopCounterI */
#undef ti_sysbios_family_arm_v7a_Pmu_stopCounterI
#define ti_sysbios_family_arm_v7a_Pmu_stopCounterI ti_sysbios_family_arm_v7a_Pmu_stopCounterI__E

/* resetCountI */
#undef ti_sysbios_family_arm_v7a_Pmu_resetCountI
#define ti_sysbios_family_arm_v7a_Pmu_resetCountI ti_sysbios_family_arm_v7a_Pmu_resetCountI__E

/* setCountI */
#undef ti_sysbios_family_arm_v7a_Pmu_setCountI
#define ti_sysbios_family_arm_v7a_Pmu_setCountI ti_sysbios_family_arm_v7a_Pmu_setCountI__E

/* enableInterruptI */
#undef ti_sysbios_family_arm_v7a_Pmu_enableInterruptI
#define ti_sysbios_family_arm_v7a_Pmu_enableInterruptI ti_sysbios_family_arm_v7a_Pmu_enableInterruptI__E

/* disableInterruptI */
#undef ti_sysbios_family_arm_v7a_Pmu_disableInterruptI
#define ti_sysbios_family_arm_v7a_Pmu_disableInterruptI ti_sysbios_family_arm_v7a_Pmu_disableInterruptI__E

/* clearOverflowStatusI */
#undef ti_sysbios_family_arm_v7a_Pmu_clearOverflowStatusI
#define ti_sysbios_family_arm_v7a_Pmu_clearOverflowStatusI ti_sysbios_family_arm_v7a_Pmu_clearOverflowStatusI__E

/* getCountI */
#undef ti_sysbios_family_arm_v7a_Pmu_getCountI
#define ti_sysbios_family_arm_v7a_Pmu_getCountI ti_sysbios_family_arm_v7a_Pmu_getCountI__E

/* getOverflowStatusI */
#undef ti_sysbios_family_arm_v7a_Pmu_getOverflowStatusI
#define ti_sysbios_family_arm_v7a_Pmu_getOverflowStatusI ti_sysbios_family_arm_v7a_Pmu_getOverflowStatusI__E

/* configureCounterI */
#define Pmu_configureCounterI ti_sysbios_family_arm_v7a_Pmu_configureCounterI__I

/* clearOverflowStatusReg */
#define Pmu_clearOverflowStatusReg ti_sysbios_family_arm_v7a_Pmu_clearOverflowStatusReg__I

/* getOverflowStatusReg */
#define Pmu_getOverflowStatusReg ti_sysbios_family_arm_v7a_Pmu_getOverflowStatusReg__I

/* initCounters */
#define Pmu_initCounters ti_sysbios_family_arm_v7a_Pmu_initCounters__I

/* interruptHandler */
#define Pmu_interruptHandler ti_sysbios_family_arm_v7a_Pmu_interruptHandler__I

/* Module_startup */
#undef ti_sysbios_family_arm_v7a_Pmu_Module_startup
#define ti_sysbios_family_arm_v7a_Pmu_Module_startup ti_sysbios_family_arm_v7a_Pmu_Module_startup__E

/* Instance_init */
#undef ti_sysbios_family_arm_v7a_Pmu_Instance_init
#define ti_sysbios_family_arm_v7a_Pmu_Instance_init ti_sysbios_family_arm_v7a_Pmu_Instance_init__E

/* Instance_finalize */
#undef ti_sysbios_family_arm_v7a_Pmu_Instance_finalize
#define ti_sysbios_family_arm_v7a_Pmu_Instance_finalize ti_sysbios_family_arm_v7a_Pmu_Instance_finalize__E

/* module */
#ifdef ti_sysbios_family_arm_v7a_Pmu_Module__state__VR
#define Pmu_module ((ti_sysbios_family_arm_v7a_Pmu_Module_State *)(xdcRomStatePtr + ti_sysbios_family_arm_v7a_Pmu_Module__state__V_offset))
#define module ((ti_sysbios_family_arm_v7a_Pmu_Module_State *)(xdcRomStatePtr + ti_sysbios_family_arm_v7a_Pmu_Module__state__V_offset))
#else
#define Pmu_module ((ti_sysbios_family_arm_v7a_Pmu_Module_State *)(xdc__MODOBJADDR__(ti_sysbios_family_arm_v7a_Pmu_Module__state__V)))
#if !defined(__cplusplus) ||!defined(ti_sysbios_family_arm_v7a_Pmu__cplusplus)
#define module ((ti_sysbios_family_arm_v7a_Pmu_Module_State *)(xdc__MODOBJADDR__(ti_sysbios_family_arm_v7a_Pmu_Module__state__V)))
#endif
#endif

/* per-module runtime symbols */
#undef Module__MID
#ifdef ti_sysbios_family_arm_v7a_Pmu_Module__id__CR
#define Module__MID (*((CT__ti_sysbios_family_arm_v7a_Pmu_Module__id *)(xdcRomConstPtr + ti_sysbios_family_arm_v7a_Pmu_Module__id__C_offset)))
#else
#define Module__MID ti_sysbios_family_arm_v7a_Pmu_Module__id__C
#endif

#undef Module__DGSINCL
#ifdef ti_sysbios_family_arm_v7a_Pmu_Module__diagsIncluded__CR
#define Module__DGSINCL (*((CT__ti_sysbios_family_arm_v7a_Pmu_Module__diagsIncluded *)(xdcRomConstPtr + ti_sysbios_family_arm_v7a_Pmu_Module__diagsIncluded__C_offset)))
#else
#define Module__DGSINCL ti_sysbios_family_arm_v7a_Pmu_Module__diagsIncluded__C
#endif

#undef Module__DGSENAB
#ifdef ti_sysbios_family_arm_v7a_Pmu_Module__diagsEnabled__CR
#define Module__DGSENAB (*((CT__ti_sysbios_family_arm_v7a_Pmu_Module__diagsEnabled *)(xdcRomConstPtr + ti_sysbios_family_arm_v7a_Pmu_Module__diagsEnabled__C_offset)))
#else
#define Module__DGSENAB ti_sysbios_family_arm_v7a_Pmu_Module__diagsEnabled__C
#endif

#undef Module__DGSMASK
#ifdef ti_sysbios_family_arm_v7a_Pmu_Module__diagsMask__CR
#define Module__DGSMASK (*((CT__ti_sysbios_family_arm_v7a_Pmu_Module__diagsMask *)(xdcRomConstPtr + ti_sysbios_family_arm_v7a_Pmu_Module__diagsMask__C_offset)))
#else
#define Module__DGSMASK ti_sysbios_family_arm_v7a_Pmu_Module__diagsMask__C
#endif

#undef Module__LOGDEF
#ifdef ti_sysbios_family_arm_v7a_Pmu_Module__loggerDefined__CR
#define Module__LOGDEF (*((CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerDefined *)(xdcRomConstPtr + ti_sysbios_family_arm_v7a_Pmu_Module__loggerDefined__C_offset)))
#else
#define Module__LOGDEF ti_sysbios_family_arm_v7a_Pmu_Module__loggerDefined__C
#endif

#undef Module__LOGOBJ
#ifdef ti_sysbios_family_arm_v7a_Pmu_Module__loggerObj__CR
#define Module__LOGOBJ ti_sysbios_family_arm_v7a_Pmu_Module__loggerObj__R
#define Module__LOGOBJ (*((CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerObj *)(xdcRomConstPtr + ti_sysbios_family_arm_v7a_Pmu_Module__loggerObj__C_offset)))
#else
#define Module__LOGOBJ ti_sysbios_family_arm_v7a_Pmu_Module__loggerObj__C
#endif

#undef Module__LOGFXN0
#ifdef ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn0__CR
#define Module__LOGFXN0 (*((CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn0 *)(xdcRomConstPtr + ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn0__C_offset)))
#else
#define Module__LOGFXN0 ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn0__C
#endif

#undef Module__LOGFXN1
#ifdef ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn1__CR
#define Module__LOGFXN1 (*((CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn1 *)(xdcRomConstPtr + ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn1__C_offset)))
#else
#define Module__LOGFXN1 ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn1__C
#endif

#undef Module__LOGFXN2
#ifdef ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn2__CR
#define Module__LOGFXN2 (*((CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn2 *)(xdcRomConstPtr + ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn2__C_offset)))
#else
#define Module__LOGFXN2 ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn2__C
#endif

#undef Module__LOGFXN4
#ifdef ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn4__CR
#define Module__LOGFXN4 (*((CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn4 *)(xdcRomConstPtr + ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn4__C_offset)))
#else
#define Module__LOGFXN4 ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn4__C
#endif

#undef Module__LOGFXN8
#ifdef ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn8__CR
#define Module__LOGFXN8 (*((CT__ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn8 *)(xdcRomConstPtr + ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn8__C_offset)))
#else
#define Module__LOGFXN8 ti_sysbios_family_arm_v7a_Pmu_Module__loggerFxn8__C
#endif

#undef Module__G_OBJ
#ifdef ti_sysbios_family_arm_v7a_Pmu_Module__gateObj__CR
#define Module__G_OBJ (*((CT__ti_sysbios_family_arm_v7a_Pmu_Module__gateObj *)(xdcRomConstPtr + ti_sysbios_family_arm_v7a_Pmu_Module__gateObj__C_offset)))
#else
#define Module__G_OBJ ti_sysbios_family_arm_v7a_Pmu_Module__gateObj__C
#endif

#undef Module__G_PRMS
#ifdef ti_sysbios_family_arm_v7a_Pmu_Module__gatePrms__CR
#define Module__G_PRMS (*((CT__ti_sysbios_family_arm_v7a_Pmu_Module__gatePrms *)(xdcRomConstPtr + ti_sysbios_family_arm_v7a_Pmu_Module__gatePrms__C_offset)))
#else
#define Module__G_PRMS ti_sysbios_family_arm_v7a_Pmu_Module__gatePrms__C
#endif

#undef Module__GP_create
#define Module__GP_create ti_sysbios_family_arm_v7a_Pmu_Module_GateProxy_create
#undef Module__GP_delete
#define Module__GP_delete ti_sysbios_family_arm_v7a_Pmu_Module_GateProxy_delete
#undef Module__GP_enter
#define Module__GP_enter ti_sysbios_family_arm_v7a_Pmu_Module_GateProxy_enter
#undef Module__GP_leave
#define Module__GP_leave ti_sysbios_family_arm_v7a_Pmu_Module_GateProxy_leave
#undef Module__GP_query
#define Module__GP_query ti_sysbios_family_arm_v7a_Pmu_Module_GateProxy_query


#endif /* ti_sysbios_family_arm_v7a_Pmu__INTERNAL____ */
